### ISSUE TITLE
Aggregare e validare informazioni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#1]
Con il caos che tutti abbiamo visto in giro occorre un unico punto di riferimento che funga da aggregatore e possa "validare" informazioni attendibili.

**Comment by olistik** [comment]
Ha senso provvedere a questi contesti di aggregazione:

- nazionale (1)
- locale (Regione) (n) e/o iperlocale (Comune) (n)

?

**Comment by iltempe** [comment]
direi che chiudo. lo scopo è chiaro.
