### ISSUE TITLE
Nelle segnalazioni sul sito non funziona il campo link 

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#101]
Tutti i campi link (fonti) delle segnalazioni non sono attivi.

**Comment by drizzt** [comment]
Puoi spiegarti meglio?

**Comment by cristigalas** [comment]
Il campo fonte che è un link non è attivo, se ci vado sopra non si apre.

**Comment by cristigalas** [comment]
Vedi ad es. qui https://www.covid19italia.info/issues/137/ ma vale per tutte.

**Comment by drizzt** [comment]
È stato rotto in 6714f5dda0b674404d782aa787614f696a26ddc9, assegnato al committer originale

**Comment by avivace** [comment]
@mfortini Ho sistemato, ma forse non è così sensato quello che ho fatto: se succede che qualsiasi campo abbia un link, viene linkato: se vengono inseriti link in altri campi vengono resi link anch'essi. Se non ti torna abilitiamo il link solo sullo specifico campo "fonte"
