### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by aurasphere** [emergenzeHack/covid19italia#104]
**Priorità**: bassa

## Testo della comunicazione
Sviluppatore Java in primis, ho anche qualche conoscenza frontend (js, typescript).

**Comment by avivace** [comment]
Ciao @aurasphere ! Ti ho aggiunto al gruppo Telegram degli sviluppatori e tecnici che stanno lavorando al progetto. Nel frattempo, guardati attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare faccelo sapere :)

**Comment by aurasphere** [comment]
Ciao @avivace grazie mille, mi faccio un giro!
