### ISSUE TITLE
Il dominio senza "www" punta ad un IP sbagliato

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia#105]
`covid19italia.help` non funziona perchè non punta all'indirizzo IP corretto. Dovrebbe sistemare chi ha accesso alla configurazione dei record DNS

**Comment by mfortini** [comment]
Sto cercando di fixare il DNS. Netlify ammette di gestire con i loro DNS un solo dominio, mentre gli altri sono redirect. Avevo configurato come primario covid19italia.info e ho paura a cambiarlo ora che siamo in corsa ;)

**Comment by avivace** [comment]
Mi sembrano tutti andare, ora
