### ISSUE TITLE
Ottimizzazione sito e navigabilità per soggetti non vedenti

### ISSUE THREAD

**Issue by tailot** [emergenzeHack/covid19italia#111]
**Priorità**: bassa

## Richiesta

Ottimizzare il più possibile il sito al fine di garantire una normale navigabilià e offrendo a soggetti non vedenti le funzionalità per cui il progetto è nato. Ho impostato la priorità bassa perchè non abbiamo richieste particolari (che io sappia). Se ne avete conoscenze @mfortini @iltempe servirebbe qualcuno che testi il tutto con tool di accessibilità.

https://www.wuhcag.com/wcag-checklist/
Tool chrome (multilingua) per testare navigazione:
https://chrome.google.com/webstore/detail/chromevox-classic-extensi/kgejglhpjiefppelpmljglcjbhoiplfn

Allo stato attuale:

* [x] Alt e aria-label vanno scritti in maniera più discorsiva un po come se stessivo parlando con qualcuno.
* [x] Alt del logo si chiama esattamente come il nome del brand, questo è molto noioso.
* [x] Risolvere errori gravi segnalati dal checker https://achecker.ca/checker/index.php

## Test

* [ ] Test effettuato

**Comment by iltempe** [comment]
chiudo?

**Comment by tailot** [comment]
@iltempe si riapriamo nel caso in cui la situazione si "scaldi" un po.

**Comment by drizzt** [comment]
Ho aggiustato qualche pagina per fare in modo che tutto il sito validi con w3 (dato che molti sistemi di accessibilità funzionano solo se il sito valida correttamente)
