### ISSUE TITLE
Verifica dati geografici disponibili

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#113]
**Priorità**:  alta

## Richiesta

Alcune issue hanno delle coordinate. Verifichiamo se quello è il formato che rimarrà definitivo per cominciare a fare una mappa.

**Comment by avivace** [comment]
Per me è okay questo standard

**Comment by iltempe** [comment]
possiamo scriverci qui lo standard?

**Comment by avivace** [comment]
Il dato arriva così:
`Posizione: 40.666968 16.603018 0 0`
in cui il formato è
`LATITUDINE LONGITUDINE ALTEZZA PRECISIONE`
Con altezza e precisione non obbligatori e da inserire a mano

**Comment by iltempe** [comment]
ok. quindi ci stiamo dicendo che lo standard sarà questo ok? @mfortini ? @napo ? altri?

**Comment by iltempe** [comment]
chiudo?
