### ISSUE TITLE
Urge attivare Bollettino! 

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#114]
Come per Tci, urge attivare il bollettino con l’invio automatico delle issue contrassegnate con label bollettino a Twitter e canale Telegram. È importante per dare massima diffusione alle segnalazioni e facilitare la gestione dei social p.
Come hashtag da usare abbiamo deciso #CoronavirusItalia, vedi #90.
@iltempe @mfortini che dite?

**Comment by avivace** [comment]
Posso lavorarci io, @mfortini mi sai indicare dov'è il codice che faceva questo su TCI?

**Comment by mfortini** [comment]
C'era un feed (si configurano da _config.yml) e poi IFTTT o Zapier. Mi pare che @aborruso abbia già configurato un account IFTTT

**Comment by iltempe** [comment]
l'account IFTTT esiste. l'ho fatto io. @aborruso puoi darci una mano su questo?

**Comment by aborruso** [comment]
Buongiorno. Stasera ci guardo.

Prima purtroppo non riesco :(

**Comment by Saraveg** [comment]
Volevo condividere una riflessione. Penso che questa volta dobbiamo fare un pensiero su bollettino. Potrebbe infatti essere che la mole di informazioni sia molto maggiore di quella che avevamo su TCI. E personalmente (ma immagino anche molte altre persone) sono già iscritta a svariati canali, mi scopro a scrollare l'ansa senza motivo. Le informazioni sono molte e il martellamento crea un ansiogeno rumore di fondo. Potremmo fare un ragionamento su cosa flaggare come bollettino? (P.e. ha senso la normativa? non ci so già i canali di informazione?)  e possiamo pensare di fare dei digest (anche più volte al giorno ma non più di due)?

**Comment by avivace** [comment]
@Saraveg sono d'accordo e suggerirei di applicare un preliminare filtro basato sulla localizzazione. Sono di Teramo, vorrei ricevere (eventualmente) le informazioni di carattere nazionale e poi quelle relative alla mia provincia, nient'altro.

**Comment by cristigalas** [comment]
@Saraveg si, certo un ragionamento sul bollettino va fatto perché non possiamo inviare tutto a Twitter e Telegram. Del resto non lo si faceva nemmeno con Tci. La normativa infatti non la invierei ma anche altro... 

Pensiamo però due cose: le nostre segnalazioni sono soprattutto ‘solidali’ e quindi in parte diverse rispetto alla tante notizie che circolano su social e media. Due: se non attiviamo una forma automatica di invio diventa più difficile dare visibilità alle segnalazioni che sono sul sito e alimentare i nostri canali. 

Comunque mi pare ottima l’idea di fare un digest giornaliero una o due volte al giorno che raccolga le segnalazioni contrassegnate con label bollettino. Poi ragioniamo come usare la label.

@avivace Mi pare, invece, difficile che l’utente possa scegliere quale bollettino ricevere, cioè con quali segnalazioni territoriali. Non c’è una iscrizione individuale al ‘bollettino’ ma è un sistema di invio automatico ai nostri canali Twitter e Telegram. Ma non sono una tecnica e se c’è un modo ben venga. Comunque la selezione territoriale delle segnalazioni potrebbe essere una modalità che possiamo introdurre nella ricerca sul sito e/o con gli RSS.

**Comment by aborruso** [comment]
@cristigalas allora procedo con il feed RSS di tutte le issue mappate come "bollettino" e "approvate".

Con l'RSS poi si pilota automatismo.

Ti chiedo però di darmi conferma sul criterio: "bollettino" e "approvate".

Grazie

**Comment by cristigalas** [comment]
Accettate sono tutte quelle ritenute diciamo valide. Quelle con label bollettino invece dobbiamo ancora decidere i criteri, ci sarà quindi una selezione, saranno solo una parte. Ma rispetto alla questione digest e selezione territoriale (vedi sopra) che ne pensi @aborruso?

**Comment by aborruso** [comment]
@cristigalas sono per fare piccoli passi.
Quindi per ora chiuderei il primo step: un modo per lanciare automaticamente nei social ciò che deve essere "bollettinizzato".

Aspetto un "Ok".

Grazie

**Comment by cristigalas** [comment]
> @cristigalas sono per fare piccoli passi.
> Quindi per ora chiuderei il primo step: un modo per lanciare automaticamente nei social ciò che deve essere "bollettinizzato".
> 
> Aspetto un "Ok".
> 
> Grazie

Sì sì hai ragione, per me è ok. Procediamo con il bollettino, poi decidiamo come gestirlo e se e come fare digest. @Saraveg @avivace che dite?

**Comment by Saraveg** [comment]
partiamo certo. nel frattempo ragioniamo ;)
@cristigalas cmq secondo me siamo d'accordo!

**Comment by cristigalas** [comment]
Allora @aborruso partiamo! Grazie!

**Comment by iltempe** [comment]
ciao a tutti quando avete il link al nostro feed me lo annotate qui ? grazie.

**Comment by aborruso** [comment]
@cristigalas questa è la prima versione del feed http://feeds.feedburner.com/covid19ita_segnalazioni

**Nota bene**: contiene tutte le attive, perché al momento nessuna ha la label "bollettino".

Quindi per ora è un RSS demo. Auto assegnati una issue (per me è un nome femminile) "segnalare ad Andrea avvio uso bollettino"

**Comment by aborruso** [comment]
@cristigalas ho scritto male: tutte le "accettato"

**Comment by iltempe** [comment]
@aborruso ma questo http://feeds.feedburner.com/covid19ita_segnalazioni è divulgabile ? Ha un senso metterlo come link sul sito per chi volesse agganciarsi al feed completo con tutte le accettate?

**Comment by aborruso** [comment]
@iltempe queste sono quelle con label "accettato" e le sto facendo puntare alla versione HTML (l'ho appena fatto, quindi aggiorna).

Puoi farne l'uso che vuoi, se per te va bene che ci siano tutte quelle "accettato".

Ne posso fare una versione clone per @cristigalas per tutte quelle che saranno "accettato" e anche "bollettino".

**Comment by iltempe** [comment]
ok. mi pare ottimo averli entrambi per me. le metterei come link in questa pagina. https://www.covid19italia.info/opendata/ oppure in questa https://www.covid19italia.info/canali/ o anche in entrambe.

**Comment by cristigalas** [comment]
@aborruso ok! Mi assegno issue ;)

**Comment by cristigalas** [comment]
@iltempe li segnalerei nella pagina Canali, cambiando però leggermente il testo introduttivo per renderlo più chiaro:

_Ecco i canali attraverso cui puoi contattarci, ricevere aggiornamenti, segnalare info utili o necessità:_

**Comment by iltempe** [comment]
@cristigalas ok per ora l'ho messo in CANALI. a posto.

**Comment by cristigalas** [comment]
> @cristigalas ok per ora l'ho messo in CANALI. a posto.

Il testo nella pagina però non è cambiato...

**Comment by cristigalas** [comment]
@Saraveg @chiccap @favoeva a questo punto dobbiamo ragionare su quali segnalazioni mettere label _bollettino_. 
Non ho ancora capito se tecnicamente sia fattibile inviare il bollettino sotto forma di digest giornaliero, però teniamo conto che se su Telegram può essere utile e fattibile, su Twitter invece sarebbe molto più complicato per via dei 240 caratteri. Quindi per ora lascerei un attimo da parte la questione e mi concentrerei su questione: **dove mettiamo la label?**

Proposta sulla quale ragionare insieme:
tutte le richieste e offerte di aiuto (che sono poche)
servizi a domicilio, almeno quelli offerti a livello nazionale da grandi organizzazioni (vedi CroceRossa) e quelli offerti in capoluoghi di provincia. Che dite?
Iniziative ricreative/culturali di un certo interesse (da valutare di volta in volta)
Notizie rilevanti (da valutare di volta in volta)
Bufale (tutte)
Raccolte fondi: qui è più difficile decidere uno o più criteri. Quelle verso gli ospedali? Quelle verso gli ospedali delle zone più colpite (nord Italia)? Quelle a sostegno di volontari è associazioni in campo contro emergenza? 

Comunque per capire come funziona la cosa dobbiamo, secondo me, partire in qualche modo e vedere, aggiustando semmai il tiro in corsa. Teniamo conto che fino a che non parte il bollettino Telegram e Twitter sono ‘sofferenti‘, così come la visibilità delle segnalazioni.

**Comment by iltempe** [comment]
@cristigalas quale testo? io ho aggiornato esattamente come mi hai scritto tu. fammi sapere.

**Comment by chiccap** [comment]
@cristigalas inizierei anche ioseguendo la logica inserimento label come da tuo elenco. Se non congestioniamo il sistema le reccolte fondi le metterei tutte, una volta validate.

**Comment by cristigalas** [comment]
> @cristigalas quale testo? io ho aggiornato esattamente come mi hai scritto tu. fammi sapere.

Sì, scusa ho visto, ieri non lo vedevo forse era ancora in aggiornamento...

**Comment by cristigalas** [comment]
@chiccap @Saraveg partiamo allora con la label bollettino? Per le raccolte intanto inizierei col segnalare quelle più rilevanti verso ospedali, per sostegno volontari e potenziamento servizi verso i più fragili. E vediamo quante sono, ok? 
Diciamoci quando iniziare. Io posso anche da subito... e poi vediamo se tra stasera e domani Andrea riesce ad attivare il tutto...

**Comment by Saraveg** [comment]
@cristigalas per me ok. ora mi metto su geolocalizzazione. quindi mano a mano che vedo posso mettere anche label bollettino. e poi vediamo come va giusto?

**Comment by chiccap** [comment]
@cristigalas @Saraveg mettiamo anche in issue vecchie giusto?

**Comment by cristigalas** [comment]
> @cristigalas @Saraveg mettiamo anche in issue vecchie giusto?

Sì certo, a patto che siano ancora valide o comunque significative.

**Comment by cristigalas** [comment]
Un’ultima avvertenza soprattutto per le nuove volontarie: lavoriamo con attenzione sui titoli delle issue, pensando che dal titolo si deve capire bene di cosa si tratta ma non deve essere troppo lungo e deve sempre contenere #Città ed eventualmente specificato anche Chi, soprattutto se grandi organizzazioni o enti pubblici.

**Comment by favoeva** [comment]
@cristigalas 
inseriamo in bollettino bufale così?
NON è vero che.... #coronavirusitalia #bufale

**Comment by favoeva** [comment]
Così può andare? 
![image](https://user-images.githubusercontent.com/9965333/76661659-4c610c00-657c-11ea-9f2f-93f8e9d0c434.png)

**Comment by cristigalas** [comment]
> @cristigalas
> inseriamo in bollettino bufale così?
> NON è vero che.... #coronavirusitalia #bufale

Avevo pensato anch’io ad un hashtag, però poi mi sono detta che quando sono pubblicate sul,sito nella sezione Bufale, è brutto è fastidioso vedere una sfilata di segnalazioni tutte con hashtag #bufale. Ecco perché ho pensato di inserire nei titoli qualcosa tipo Non è vero / È una bufala /Non crediamo a...  cercando di diversificare un po’.... Che ne dici? Chiedo anche a @chiccap e @Saraveg.

**Comment by chiccap** [comment]
@favoeva @cristigalas bella idea! Io voto “È una bufala” così è coerente con il pulsante e la label :)

**Comment by aborruso** [comment]
Ciao, abbiamo feed RSS delle issue "accettate", con label "Bollettino" https://script.google.com/macros/s/AKfycbxTuPFn9ePZOhI7et2f8nSPjkjlhd9zqHth9sOVYRZ6Va09zmE/exec

@cristigalas se si deve attivare qualche automatismo di pubblicazione, ho bisogno di sapere quale e di tutte le credenziali del caso da inviarmi per email.

Grazie

**Comment by favoeva** [comment]
> @favoeva @cristigalas bella idea! Io voto “È una bufala” così è coerente con il pulsante e la label :)

Procediamo così ? @cristigalas @Saraveg

**Comment by chiccap** [comment]
> > @favoeva @cristigalas bella idea! Io voto “È una bufala” così è coerente con il pulsante e la label :)
> 
> Procediamo così ? @cristigalas @Saraveg

Non mi ero però accorta che le 'vecchie' bufale sono ora fake news. Ritiro quanto detto. 'Non è vero che...' allora forse è il migliose.

**Comment by Saraveg** [comment]
scusate anche a voi per la latitanza. oggi ci sono. a me "non è vero che" come diceva @favoeva  piaceva. ma va bene anche "è una bufala". tra le due voto 1. non so stata molto utile ve'?

**Comment by cristigalas** [comment]
> Ciao, abbiamo feed RSS delle issue "accettate", con label "Bollettino" https://script.google.com/macros/s/AKfycbxTuPFn9ePZOhI7et2f8nSPjkjlhd9zqHth9sOVYRZ6Va09zmE/exec
> 
> @cristigalas se si deve attivare qualche automatismo di pubblicazione, ho bisogno di sapere quale e di tutte le credenziali del caso da inviarmi per email.
> 
> Grazie

Intendi password Twitter e Telegram, immagino... ti scrivo via email.

**Comment by aborruso** [comment]
Attivata pubblicazione automatica su Twitter e Canale Telegram

**Comment by iltempe** [comment]
chiudo. grazie.
