### ISSUE TITLE
APP COVID19

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/covid19italia#115]
Lo so che non è una priorità ma una APP per le segnalazioni sarebbe tanto bella!

**Comment by gorobey** [comment]
potremmo ovviare trasformando il sito in  PWA che dite?

**Comment by ElWildo** [comment]
Non son convinto.
Apple ha ristretto le politiche di molto e non credo lasci pubblicare app che sono pagine wrappate. (abbiamo avuto questo problema al lavoro) 

Piuttosto, farlo con react native é una cosa abbordabile secondo voi?

**Comment by chiccap** [comment]
@ElWildo react non è il massimo ma se è fattibile io procederei ma non sono un’esperta. Sentiamo @mfortini e @iltempe

**Comment by ElWildo** [comment]
@chiccap fa app pesanti ma almeno si fa sia per android che iPhone. Se serve ci ho lavorato un annetto circa perciò potrei accolarmelo in parte io.

**Comment by avivace** [comment]
Io direi di evitare proprio l'app per App Store. A quanto ne so, non abbiamo un account sviluppatore che costa una quota non irrisoria.
Anche se lo avessimo, tra tempi di sviluppo, pubblicazione e approvazione da parte di Apple perderemmo troppo tempo e forza lavoro che potremmo impiegare per migliorare l'esperienza web di cui usufruiscono tutti. Andrei di PWA.

**Comment by gorobey** [comment]
date un occhio a questo articole per la compatibilità:
https://it.goodbarber.com/blog/ios-apre-le-sue-porte-alle-progressive-web-app-a579/
dipende alla fine cosa si vuole farle fare, se l'idea è una maggiore diffusione vero, pubblicata negli store avrebbe più visibilità, ma secondo me nulla che non sia in grado di fare il caro buon vecchio spam (leggi: un po di buona e sana condivisione).

**Comment by ElWildo** [comment]
Per me è ok. Mi piacerebbe lavorarci però pwa non ne ho mai fatte (anche se leggevo che non divergono troppo da web app normali). Si può lavorare in più di uno sulla singola issue?

**Comment by avivace** [comment]
Direi di si, creiamo una chat e vi dividete / coordinate le cose da fare :)

**Comment by gorobey** [comment]
> 
> 
> Per me è ok. Mi piacerebbe lavorarci però pwa non ne ho mai fatte (anche se leggevo che non divergono troppo da web app normali). Si può lavorare in più di uno sulla singola issue?

io mi sono cimentato qualche volta, nulla di estremamente complicato, posso condividere uno scheletro

**Comment by avivace** [comment]
Va bene, coordiniamoci internamente allora.

**Comment by avivace** [comment]
Ci spostiamo su https://github.com/emergenzeHack/covid19italia_app per l'applicazione mobile
