### ISSUE TITLE
Inserire in sezione Iniziative Solidali anche quelle pubbliche e correggere titolo interno

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#117]
In [questa sezione](https://www.covid19italia.info/servizi-e-iniziative-solidali-private/) del sito mi sembra compaiono solo le **iniziative solidali private**, mentre ci dovrebbero andare tutte anche quelle con label **“Iniziative solidali pubbliche”**. E poi andrebbe corretto anche il titolo della sezione lasciando Iniziative solidali.

**Comment by drizzt** [comment]
Sembra ridondante con quello che c'è in https://www.covid19italia.info/issues/#servizi-e-iniziative-solidali o sbaglio? @cristigalas

**Comment by cristigalas** [comment]
> Sembra ridondante con quello che c'è in https://www.covid19italia.info/issues/#servizi-e-iniziative-solidali o sbaglio? @cristigalas
> Propongo di levare la pagina, lasciando l'icona che punta direttamente a https://www.covid19italia.info/issues/#servizi-e-iniziative-solidali

Mi sembra un’ottima idea! Grazie!

**Comment by drizzt** [comment]
Fatto, grazie
