### ISSUE TITLE
Layout del sito

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#12]
lasciamo quello di TCI? lo cambiamo con un nuovo tema?

**Comment by cristigalas** [comment]
Io cambierei un pochino...

**Comment by Pinzauti** [comment]
Anche io cambierei. Prenderei anche in considerazione [Hugo](https://github.com/gohugoio/hugo) come alternativa a Jekyll.

**Comment by mfortini** [comment]
Facciamo tutte le prove che volete, ma non ci perdiamo troppo tempo :)

**Comment by olistik** [comment]
Dobbiamo importare funzionalità integrate in TCI o partiamo da 0?

**Comment by iltempe** [comment]
@olistik ovviamente come hai visto si riusa TCI almeno di base ma possiamo migliorare o modificare il layout. Qui in questo issue discutiamo di cose graficamente da poter cambiare.
