### ISSUE TITLE
Problemi ridimensionamento bottoni pagina issue

### ISSUE THREAD

**Issue by aurasphere** [emergenzeHack/covid19italia#120]
**Priorità**: bassa

## Richiesta
I bottoni delle categorie sulla pagina https://www.covid19italia.info/issues sono troppo vicini tra di loro quando vanno a capo su uno schermo piccolo:

![image](https://user-images.githubusercontent.com/14991778/76532910-93b1a480-6477-11ea-87c0-59327636bf3b.png)

Inoltre il comportamento in generale dei bottoni sembra inconsistente in base al ridimensionamento della finestra:

- larghezza finestra > 1200px: 3 bottoni sulla stessa riga, 1 su nuova riga
- larghezza finestra > 1105px: tutti i 4 bottoni sulla stessa riga
- larghezza finestra > 990px: 3 bottoni sulla stessa riga, 1 su nuova riga
- larghezza finestra > 923px: tutti i 4 bottoni sulla stessa riga

Testato con Google Chrome.

## Come si riproduce il bug
Da Chrome, ridimensionando la finestra.

## Test
* [ ] Test effettuato

**Comment by aurasphere** [comment]
Se l'issue è verificato me ne occuperei io

**Comment by iltempe** [comment]
ragazzi è fatto? chiudo?

**Comment by aurasphere** [comment]
@iltempe io sulla pull vedo i check che stanno andando avanti da 3h e non sono completi... Apparte questo, quando viene mergiata quella pull per me si può chiudere

**Comment by avivace** [comment]
Direi molto meglio, grazie @aurasphere !
I check ogni tanto si impiantano ma è okay ignorarli se coprono parti non modificate dalla tua PR ;)
