### ISSUE TITLE
Pubblicare sul sito Iniziative culturali/ricreative, Notizie e tutte le segnalazioni. Ora non ci sono tutte!

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#123]
Attenzione! Sul sito le **iniziative ricreative e culturali** e le cosiddette **Notizie**, ma anche **bufale** e **richieste di aiuto** non compaiono perché non hanno label _iniziative solidali_ ma solo quella specifica o almeno credo che sia per questo motivo. Visto che anche questo tipo di segnalazioni sono tante e utili andrebbero caricate nell’archivio delle segnalazioni. Anzi bisognerebbe caricare in archivio tutte le segnalazioni e poi almeno bufale, news e iniziative culturali le evidenzierei con un bottone in home page, oltre che all’interno dell’archivio.

**Comment by Saraveg** [comment]
Ciao riapriamo questa issue e la rendiamo prioritaria?
Dai test fatti quest'oggi ci arriva il feedback univoco che non è comprensibile e usabile dall'home page.
Una proposta di ruorganizzazione puo' essere:
 - INIZIATIVE SOLIDALI che raccoglie (con questo metodo https://www.covid19italia.info/issues/) servizi e iniziative solidali, cosegne e commissioni, supporto psicologico
 - RACCOLTE FONDI 
 - NOTIZIE  (**anche perché questa label non appare da nessuna parte!**) 

Che dite è fattibile?

**Comment by cristigalas** [comment]
Si sì @Saraveg la issue è aperta... ora, secondo me, la priorità è **portare sul sito TUTTE le issue che accettiamo**. Adesso ci sono solo una parte, mentre tutte devono stare dentro l’archivio. E il bottone ‘archivio’ lo lascerei in home page semmai rinominandolo **“Tutte le segnalazioni”** perché la parola archivio può fare pensare che siano ‘archiviate’, cioè superate.

Poi per la **home page** ho pensato a **due proposte**.

1. Inserire in home, oltre ai bottoni Segnala, Partecipa, Fonti istituzionali, anche i bottoni:
- Iniziative solidali (con anche raccolte fondi)
- Iniziative culturali e creative (che sono molte)
- Notizie

2. Altra proposta: togliamo Fonti Istituzionali e le mettiamo nel menù in alto sotto una nuova voce Utilità (come in Tci) e, al loro posto, inseriamo in home page le raccolte fondi. Nel senso che le lasciamo dove sono ora (iniziative solidali) ma le evidenziamo anche con un bottone in home.

A dire il vero, ci sarebbe anche la **proposta 3**: lasciamo tutto in home page ;) cioè anche bottoni Fonti Istituzionali e Raccolte Fondi.

**Comment by Saraveg** [comment]
Allora...
d'accordo su priorità

Sulle proposte farei un match tra le tue prime 2.
Le fonti istituzionali possono andare sopra (ma non con menù a tendina perché poi di fatto scompare). 
Le raccolte fondi le terrei cmq separate (non sono la stessa cosa)
Sono d'accordo che sono molte le iniziative culturali quindi potremmo tenerle separate (anche se sono solidali)
notizie ok

che dici?

**Comment by cristigalas** [comment]
@Saraveg ok. Allora Fonti Istituzionali le mettiamo sopra senza menù a tendina, anche se forse più avanti un menù Utilità servirà. Stavamo, infatti, pensando ad una pagina Link e info utili, vedi qui #106.

Quindi in home mettiamo:

1. Segnala
2. Partecipa 
3. Iniziative solidali
4. Raccolte fondi 
5. Iniziative culturali e creative
6. Notizie
7. Tutte le segnalazioni

Anche se Partecipa mi sembra ridondante, se lo mettiamo nel menù in alto visto che qualcosa di simile già c’è? Basterebbe rivedere i link di questo menù... Che dici? Così i bottoni in home sarebbero solo 6.

**Comment by Saraveg** [comment]
ok, basta che si vede partecipa ;)

**Comment by cristigalas** [comment]
Riepilogo definitivo. Nel menù in alto aggiungiamo Fonti istituzionali, mentre nel menù Partecipa rinominiamo “Contribuisci su Github” in “Contribuisci” o “Contribuisci al progetto” e rimandiamo a [questa pagina](https://covid19italia.info/2020-03-10-sei-uno-sviluppatore-se-vuoi-aiutaci/) che è più completa. 

Per quanto riguarda, invece, i bottoni in home inseriamo nell’ordine:
- Segnala
- Iniziative solidali
- Raccolte fondi
- Iniziative culturali e creative
- Notizie
- Tutte le segnalazioni

@iltempe @mfortini @avivace possiamo fare così?

**Comment by iltempe** [comment]
se mi confermate che quanto dice @cristigalas è definitivo procedo. grazie.

**Comment by Saraveg** [comment]
per noi è ok proposta @cristigalas

**Comment by cristigalas** [comment]
@iltempe puoi quindi procedere, grazie!

**Comment by iltempe** [comment]
non posso concludere. mancano le pagine di Iniziative culturali e creative e Notizie. apro issue.

**Comment by cristigalas** [comment]
> non posso concludere. mancano le pagine di Iniziative culturali e creative e Notizie. apro issue.

Ah ok... Portare tutte le segnalazioni sul sito è importante e a questo punto urgente... gli utenti al momento vedono solo la metà di quello che processiamo e accettiamo.

**Comment by iltempe** [comment]
esatto. direi che lo stiamo facendo con #144 poi le rendiamo navigabili.

**Comment by iltempe** [comment]
direi che chiudo perchè abbiamo da decidere questo #163
