### ISSUE TITLE
Pagina Usa i nostri dati

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#127]
**Priorità**: medio

## Richiesta
Sarebbe molto utile tracciare chi usa i nostri dati. Qualche canale bot mi sta chiedendo ad esempio il link ai dataset/feed rss degli aggiornamenti. Due opzioni
O ci facciamo dare i riferimenti dei canali per inserirli in una pagina (e lo gestiamo a mano)
O facciamo un form ad hoc per inviare questa richiesta di uso dati e la gestiamo come tutti gli issue.

**Comment by favoeva** [comment]
form direi

**Comment by iltempe** [comment]
è un duplicato.
