### ISSUE TITLE
Pulizia label segnalazioni

### ISSUE THREAD

**Issue by claudiamazzantiact** [emergenzeHack/covid19italia#129]

**Comment by favoeva** [comment]
ho eliminato due label doppie 
ha senso per voi fare label specifica per consegne a domicilio? 
so che sono la maggior parte delle iniziative solidali in questo momento , ma più avanti potrebbero non esserlo più o magari avremo la necessità di chiuderle perchè non più attive (in questo caso il lavoro sarebbe facilitato)

**Comment by favoeva** [comment]
per le richieste di aiuto su ricerche in corso come ci comportiamo? es. questa che ho accettato ma con forti dubbi https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/315

**Comment by cristigalas** [comment]
@favoeva in questo momento label specifica consegne a domicilio è, secondo me, utile per facilitare la consultazione sul sito. Vengono infatti estratte in automatico e segnalate con specifico bottone in [questa sezione](https://covid19italia.info/issues/). Poi vedremo...

**Comment by favoeva** [comment]
si scusa @cristigalas vista ora label consegne commissioni 
me l'ero persa... :)

ok sono daccordo per studi e ricerche

**Comment by favoeva** [comment]
eliminerei label servizi e iniziative solidali 
lascerei solo:
servizi e iniziative solidali private / associazioni / cittadinanza attiva
servizi e iniziative solidali pubbliche

**Comment by cristigalas** [comment]
@favoeva sì, anche secondo me si può eliminare perché adesso mi pare che le segnalazioni di iniziative solidali private e pubbliche finiscono tutte nella [stessa sezione](https://covid19italia.info/issues/) del sito. 
Se anche @Saraveg e @chiccap sono d’accordo eliminiamo.

**Comment by avivace** [comment]
Non si rompe niente ma il software che si occupa di crearvi le Issue ve le continua a rimettere (e quindi ricreare la label)

Comunque la label `servizi e iniziative solidali` viene applicata automaticamente solo se non è specificato il tipo di soggeto, altrimenti mette sempre `Servizi e iniziative solidali private` o `Servizi e iniziative solidali pubbliche`

**Comment by favoeva** [comment]
> Non si rompe niente ma il software che si occupa di crearvi le Issue ve le continua a rimettere (e quindi ricreare la label)
> 
> Comunque la label `servizi e iniziative solidali` viene applicata automaticamente solo se non è specificato il tipo di soggeto, altrimenti mette sempre `Servizi e iniziative solidali private` o `Servizi e iniziative solidali pubbliche`
> 
> Eviterei anche di tenere una label lunga come `servizi e iniziative solidali private / associazioni / cittadinanza attiva`, se avete necessità di visualizzare questo titolo si può fare a livello di sito (esempio: la label `Servizi e iniziative solidali private` può venir visualizzata con un titolo più esteso, come `servizi e iniziative solidali private / associazioni / cittadinanza attiva` sulla lista finale)

ok ottimo grazie @avivace 
allora non tocco niente

**Comment by claudiamazzantiact** [comment]
Ciao, ritorno con una proposta. 

Eliminare:
Iniziative governo -> c'è label fonti istituzionali
Didattica a distanza -> c'è label didattica a distanza e e-learning
Giochi/intrattenimento bambini -> rientra comunque in servizi e iniziative solidali pubbliche o private
Smart working -> c'è label sostegno lavoro e imprese
Servizi e iniziative solidali -> ci sono le due label servizi e iniziative solidali pubbliche o private
Informazioni utili -> le tre label notizia, contatti utili e dati utili possono sostituire questa categoria

Vi torna?

**Comment by cristigalas** [comment]
@claudiamazzantiact allora non è che avere più label sia questo grande problema. Comunque al momento, oltre alle label più generali che rimandano alle categorie della form e del sito, servono anche quelle specifiche per due motivi: se vogliamo fare una estrazione di segnalazioni specifiche senza label è impossibile. Poi se sul sito attiviamo le label come tag aiutano l’utente a navigare tra le segnalazioni. 
Detto questo, a mio avviso servono tutte, toglierei solo label Didattica a distanza, verificando però se sotto quell’altra label ci siano issue. In tal caso prima di eliminarla devi attribuire a quelle segnalazioni la label che lascerai attiva, altrimenti le perdiamo...
Semmai scegliamo la label che ha più issue. Non so se mi sono spiegata bene...

**Comment by claudiamazzantiact** [comment]
Si, perfettamente. Grazie. La mia proposta cercava di facilitare anche nuove persone che si approcciano per la prima volta alla gestione delle segnalazioni e trovare molte etichette magari non aiuta. Tutto qui, mi taccio! : )

**Comment by avivace** [comment]
@claudiamazzantiact hai ragione! A tal proposito ho iniziato a stendere una guida qui: https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni

**Comment by cristigalas** [comment]
> Si, perfettamente. Grazie. La mia proposta cercava di facilitare anche nuove persone che si approcciano per la prima volta alla gestione delle segnalazioni e trovare molte etichette magari non aiuta. Tutto qui, mi taccio! : )

Certo, hai ragione! No problem! Diciamo che, in generale, meglio una label in più che in meno ;) ma andando avanti col numero di segnalazioni dovremmo senz'altro fare modifiche, aggiustamenti alle label. Appena ho un attimo sistemo la label Didattica.

**Comment by cristigalas** [comment]
@claudiamazzantiact @Saraveg @chiccap ho fatto un po’ di pulizia nelle label togliendo didattica e notizia e sistemando qualche altra cosetta.
