### ISSUE TITLE
Link a social da cambiare

### ISSUE THREAD

**Issue by Albertopi78** [emergenzeHack/covid19italia#132]
**Priorità**: medio

## Richiesta
Ci sono da cambiare i link a Facebook, sia nella pagina about https://www.covid19italia.info/about/
sia nella pagina canali https://www.covid19italia.info/canali/ 

I link corretti da mettere in entrambe le pagine sono:
Pagina Facebook: https://www.facebook.com/covid19italia.help/
Gruppo Facebook: https://www.facebook.com/groups/2921275147894653/

Grazie!

**Comment by iltempe** [comment]
dovrebbe essere a posto chiudo.
