### ISSUE TITLE
Segnalare ad Andrea avvio uso bollettino

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#133]
Non appena abbiamo assegnato label _bollettino_ alle segnalazioni, dobbiamo avvisare @aborruso.

Ps. Ricordiamoci che le segnalazioni che, via bollettino, verranno pubblicate su Twitter e canale Telegram dovranno contenere hashtag #CoronavirusItalia (così come abbiamo deciso qui #90).

**Comment by cristigalas** [comment]
@aborruso ci siamo! Puoi procedere con il bollettino, abbiamo messo tutte le label. Grazie!

**Comment by aborruso** [comment]
@cristigalas ecco qui il feed https://script.google.com/macros/s/AKfycbxTuPFn9ePZOhI7et2f8nSPjkjlhd9zqHth9sOVYRZ6Va09zmE/exec

Apro altra issue su come procedere
