### ISSUE TITLE
piattaforma per caffe sospesi

### ISSUE THREAD

**Issue by mirwari** [emergenzeHack/covid19italia#135]
**Priorità**:  alta

## Richiesta
 qualcuno sarebbe in grado di creare una piattaforma per bar e piccoli ristoranti attraverso la quale si possono comprare in questi giorni di quarantena, caffe o altri servizi? Si comprano oggi per sostenere tutte queste attività e si potranno poi consumare finito l'isolamento. Un caffe al giorno.. magari puo essere utile..

## Test

* [ ] Test effettuato

**Comment by cristigalas** [comment]
> **Priorità**: alta
> 
> ## Richiesta
> qualcuno sarebbe in grado di creare una piattaforma per bar e piccoli ristoranti attraverso la quale si possono comprare in questi giorni di quarantena, caffe o altri servizi? Si comprano oggi per sostenere tutte queste attività e si potranno poi consumare finito l'isolamento. Un caffe al giorno.. magari puo essere utile..

Richiesta ardita... Però segnalo che qui su Github si fanno richieste relative al progetto #Covid19Italia. Questo tipo di richiesta potrebbe essere inserita sulla nostra piattaforma attraverso la [web form Segnala](https://www.covid19italia.info/segnala/) (sotto la voce ‘chiedi aiuto”) come una sorta di suggerimento o invito a chi fosse interessato a realizzarla.

**Comment by iltempe** [comment]
concordo con @cristigalas chiudo.
