### ISSUE TITLE
Pulsanti troppo vicini in Fonti istituzionali

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia#136]
**Priorità**: medio

## Richiesta

Si può applicare #126 (che sistemava #120 ) anche alle pagine https://www.covid19italia.info/fonti-istituzionali/ ?

@aurasphere 

## Test

* [ ] Test effettuato

**Comment by aurasphere** [comment]
Yes! Assegna pure a me. Grazie!

**Comment by aurasphere** [comment]
@avivace questo può essere chiuso

**Comment by avivace** [comment]
Grazie!
