### ISSUE TITLE
HABEMUS MAPPA: GEORIFERIAMO LE SEGNALAZIONI GIA' INSERITE?

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#137]
**Priorità**: Media

## Richiesta
Come avete visto qui @mfortini ha abilitato una mappa. https://www.covid19italia.help/issues/
Molte segnalazioni sono però NON georiferite.
E' possibile secondo voi editare le segnalazioni già inserite per aggiungere georiferimenti in modo che tutte le segnalazioni siano visibili su mappa? Un modo potrebbe essere aprirle con un form ed editarle aggiungendo il tag di georeferenziazione. Che dite? Ce la facciamo?

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by avivace** [comment]
Si può fare, nel frattempo si possono semplicemente modificare le Issue esistenti e al campo posizione inserire latitudine e longitude, così come restituiti da un sito come questo: https://www.latlong.net/

```
...
Posizione: 50 60 0 0
...

```

**Comment by iltempe** [comment]
ok facciamo il metodo più semplice per tutti, lo scopo finale è rendere le informazioni visualizzabili su mappa...come preferite.

**Comment by mfortini** [comment]
https://github.com/emergenzeHack/covid19italia/wiki/Lavorare-sulle-segnalazioni#aggiungere-geolocalizzazione

**Comment by Saraveg** [comment]
hola. serve che ci spiegate l'action che ci manda github. significa che ok e che viene modificato CSV e JSON o significa che abbiamo sbagliato o peggio rotto qualcosa? metto in pausa aggiunta geolocalizzazione attendendo chiarimenti thanx @mfortini @avivace

**Comment by drizzt** [comment]
@Saraveg è una cosa che ho fatto io per avere l'aggiornamento del sito più veloce e per evitare che una issue con errori di sintassi possa rompere la generazione del sito. Nel caso in cui una issue dia noie il sistema leverà automaticamente la label "accettato", quindi finché vedete la label "accettato" su una issue va bene e potete ignorare il resto

**Comment by Saraveg** [comment]
ok, ho capito e il sistema funziona. l'unica cosa è che ci arrivano decine e decine di mail....

**Comment by iltempe** [comment]
@drizzt se possono disabilitare le notifiche?

**Comment by Saraveg** [comment]
stacco un attimo....sono arrivata (dall'inizio) alla 96 (se qualcuno volesse continuare)

**Comment by avivace** [comment]
Le notifiche vanno disattivate perchè arrivano troppe mail

**Comment by Saraveg** [comment]
Dovrei aver finito. Se qualcun* riesce a controllare....yuppi!

**Comment by iltempe** [comment]
direi che chiudo.
