### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by SilverSlytherin1** [emergenzeHack/covid19italia#139]
Ciao a tutti,
Sono un programmatore e in questi giorni ho un po' di tempo libero, se posso aiutare il mio Nick Telegram è @weareheatens

**Comment by avivace** [comment]
Ciao @SilverSlytherin1 ! Ti ho aggiunto al gruppo Telegram degli sviluppatori e tecnici che stanno lavorando al progetto. Nel frattempo, guardati attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare faccelo sapere :)
