### ISSUE TITLE
Issue che non viene renderizzata correttamente

### ISSUE THREAD

**Issue by aborruso** [emergenzeHack/covid19italia#143]
Ciao,
[questa](https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/337) viene renderizzata in [HTML](https://www.covid19italia.help/issues/337/) quasi senza contenuti.

**Comment by avivace** [comment]
Probabilmente le emoji rompono tutto? @mfortini ?

**Comment by drizzt** [comment]
Sembra a posto ora
