### ISSUE TITLE
Mancano alcune pagine del sito per alcune label delle segnalazioni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#144]
**Priorità**: Alta

## Richiesta
Per favore vanno fatte le pagine di Iniziative culturali e creative e Notizie.
Inoltre verificherei se tutte le altre LABEL sono state inserite nel sito come pagine.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by Jolsty** [comment]
@iltempe pagine nuove tipo /notizie/ oppure le mettiamo come bottoni sotto /issues ?

**Comment by Jolsty** [comment]
Per le label apri pure un'altra issue se vuoi, sto lavorando sulle pagine

**Comment by iltempe** [comment]
sulle label @cristigalas ci dici quali sono di cui mancano le pagine? grazie

**Comment by Jolsty** [comment]
Le label come vengono create? Sono predefinite o dipendono dai dati che arrivano?

**Comment by iltempe** [comment]
sono queste label https://github.com/emergenzeHack/covid19italia_segnalazioni/labels

**Comment by iltempe** [comment]
non appena hai fatto le pagine le posso linkare io sul sito secondo quanto definito in altri issue

**Comment by Jolsty** [comment]
ancora qualche minuto e faccio la PR :)

**Comment by Jolsty** [comment]
Per le label ("Inoltre verificherei se tutte le altre LABEL sono state inserite nel sito come pagine.") in ogni caso si apre un'altra issue, mi sembra giusto così

**Comment by iltempe** [comment]
ok. va benissimo.

**Comment by Jolsty** [comment]
@iltempe ho finito, dovresti vedere ora /issues/#notizie e /issues/#iniziative-culturali-e-ricreative con i relativi bottoni

Penso che per le iniziative culturali e ricreative serva un'altra icona da mettere in HP

Se va bene chiudi pure

**Comment by iltempe** [comment]
Le hai fatte tutte o solo quella?

**Comment by Jolsty** [comment]
Ho fatto /issues/#notizie e /issues/#initiative-culturali-e-ricreative così le puoi mettere in homepage, per le altre label pensiamoci dopo

**Comment by cristigalas** [comment]
> sulle label @cristigalas ci dici quali sono di cui mancano le pagine? grazie

Mancano*:
- Attività culturali
- Notizie
- Contatti utili
- Didattica a distanza
- Fake news
- Informazioni utili
- Intrattenimento/ giochi bambini
- Sostegno lavoro/imprese

Sotto label _Richieste di aiuto_ per ora c’è una sola richiesta, non ne farei una pagina quindi. Poi vedremo.. Intanto l’abbiamo inserita in bollettino, così comunque gira.

* **Attenzione**! Non per tutte le label va fatta una pagina! Quelle che ho segnalato invece hanno bisogno di una pagina.

**Comment by Jolsty** [comment]
> > sulle label @cristigalas ci dici quali sono di cui mancano le pagine? grazie
> 
> Mancano*:
> 
> * Attività culturali
> * Notizie
> * Contatti utili
> * Didattica a distanza
> * Fake news
> * Informazioni utili
> * Intrattenimento/ giochi bambini
> * Sostegno lavoro/imprese
> 
> Sotto label _Richieste di aiuto_ per ora c’è una sola richiesta, non ne farei una pagina quindi. Poi vedremo.. Intanto l’abbiamo inserita in bollettino, così comunque gira.
> 
> * **Attenzione**! Non per tutte le label va fatta una pagina! Quelle che ho segnalato invece hanno bisogno di una pagina.

Apri una issue con queste informazioni?

**Comment by cristigalas** [comment]
@Jolsty perché aprire un’altra issue?

**Comment by Jolsty** [comment]
Perchè in questa la priorità più alta era quella di avere le Notizie e le iniziative culturali e ricreative così da poterle mettere in homepage
E me la son già assegnata a me stesso, ma adesso non posso più lavorarci almeno fino a domani.

Pensavo di crearne una nuova (e quindi inizialmente non assegnata a nessuno) per le altre label così la gente se la può prendere in carico

**Comment by Jolsty** [comment]
@iltempe ho creato la nuova issue per le label mancanti, possiamo chiudere questa?

**Comment by cristigalas** [comment]
> Perchè in questa la priorità più alta era quella di avere le Notizie e le iniziative culturali e ricreative così da poterle mettere in homepage
> E me la son già assegnata a me stesso, ma adesso non posso più lavorarci almeno fino a domani.
> 
> Pensavo di crearne una nuova (e quindi inizialmente non assegnata a nessuno) per le altre label così la gente se la può prendere in carico

Ah ok, scusa... comunque vedo che l’hai aperta. Ci vediamo di la ;)

**Comment by iltempe** [comment]
yesse. chiudo.
