### ISSUE TITLE
Categorie in RICERCA

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/covid19italia#147]
Ciao! In RICERCA le categorie sono ancora quelle di TCI!

**Comment by iltempe** [comment]
per ora ho tolto le categorie. @avivace aggiorni te? o chiudiamo così?

**Comment by chiccap** [comment]
Secondo me inserire anche categorie è importante! @iltempe intendevi dire toglierle per sempre?

**Comment by iltempe** [comment]
no. ho fatto la cosa più rapida per non far vedere quel bug e per uniformare con home page. se vogliamo rimetterle le rimettiamo nessun problema.

**Comment by chiccap** [comment]
@iltempe hai fatto bene a toglierle se non erano funzionali però se possibile io le rimetterei, sono utili!

**Comment by iltempe** [comment]
chiudo ne esiste una duplicata.
