### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by gorobey** [emergenzeHack/covid19italia#149]
Ciao ragazzi,
mi piacerebbe poter collaborare e dare una mano in qualche modo.
Programmatore PHP Mysql, non so se può servire.
Magari posso dare una mano anche a livello social, o fact checking.
Su Telegram come @G_Goro
Buon lavoro

**Comment by avivace** [comment]
Ciao @gorobey  ! Ti ho aggiunto al gruppo Telegram degli sviluppatori e tecnici che stanno lavorando al progetto. Nel frattempo, guardati attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare faccelo sapere :)

**Comment by gorobey** [comment]
Ottimo Antonio! mi passo in rassegna gli issues e vedo cosa posso fare.
