### ISSUE TITLE
[richiesta iscrizione] 

### ISSUE THREAD

**Issue by ElWildo** [emergenzeHack/covid19italia#150]
Ciao sono Francesco Wild, sono Frontend dev a Londra ma ho lavorato anche come Backend.

Bazzico con php e js (e alcuni framework tipo react, react native, node, pixi per metterne alcuni a casaccio)
So qualcosina di python e java
So abbastanza di SQL e Postgresql 

Mi piacerebbe aiutare con il progetto

Il mio id telegram é @ElWildo

**Comment by avivace** [comment]
Ciao @ElWildo  ! Ti ho aggiunto al gruppo Telegram degli sviluppatori e tecnici che stanno lavorando al progetto. Nel frattempo, guardati attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare faccelo sapere :)
