### ISSUE TITLE
Aggiungere le label che mancano in /issues/

### ISSUE THREAD

**Issue by Jolsty** [emergenzeHack/covid19italia#152]
> sulle label @cristigalas ci dici quali sono di cui mancano le pagine? grazie

Mancano*:
- Attività culturali
- Notizie
- Contatti utili
- Didattica a distanza
- Fake news
- Informazioni utili
- Intrattenimento/ giochi bambini
- Sostegno lavoro/imprese

Sotto label _Richieste di aiuto_ per ora c’è una sola richiesta, non ne farei una pagina quindi. Poi vedremo.. Intanto l’abbiamo inserita in bollettino, così comunque gira.

* **Attenzione**! Non per tutte le label va fatta una pagina! Quelle che ho segnalato invece hanno bisogno di una pagina.

_Originally posted by @cristigalas in https://github.com/emergenzeHack/covid19italia/issues/144#issuecomment-598845392_

Inoltre, come consiglio di @cristigalas, aggiungere un altro bottone per tutte le label che non stanno nei bottoni 

Copio testo da telegram: "@Jolsty @matteotempestini @MatteoFortini nella pagina Tutte le Segnalazioni farei anche bottone ‘Altro’ dove finiscono tutte quelle che non stanno nei bottoni che abbiamo messo (in Altro ad es. potrebbe andare sostegno imprese/lavoro o didattica a distanza)."

**Comment by mfortini** [comment]
NB la nuova versione di issues.md ha una lista di categorie all'inizio, separata da ',' e ';', per permettere di indicare il titolo della categoria e la label esatta che è utilizzata.

**Comment by iltempe** [comment]
@Jolsty fammi sapere se ti sei già messo a lavorare su questo. o no. in caso affermativo assegnati issue in caso negativo lascialo così e posso farlo io.

**Comment by Jolsty** [comment]
@iltempe nope oggi no, se vuoi fallo te
Se lo trovo ancora aperto domani e non assegnato mi metterò a farlo io, ma oggi non posso

**Comment by iltempe** [comment]
Fake News ce l'abbiamo https://www.covid19italia.help/fake-news/

**Comment by Jolsty** [comment]
Non è meglio se le raggruppi sotto la pagina issues.md ?

**Comment by Jolsty** [comment]
Così come è stato fatto per le altre

**Comment by iltempe** [comment]
se ho capito bene si voleva avere pagine indipendenti...sbaglio?

**Comment by Jolsty** [comment]
Io avevo capito il contrario, vediamo di chiedere a qualcuno. Magari @mfortini lo sa?

**Comment by iltempe** [comment]
ok. mi fermo. ho fatto anche quelle culturali. (che nella pagina degli issue c'erano già) https://www.covid19italia.help/culturali/

**Comment by LeoEdo** [comment]
> se ho capito bene si voleva avere pagine indipendenti...sbaglio?

Secondo me, è piu ordinato e catalogato meglio, così!

**Comment by LeoEdo** [comment]
> Fake News ce l'abbiamo https://www.covid19italia.help/fake-news/

In quale MACRO CATEGORIA è stata inserita ( Notizie, Tutte le Segnalazioni) ?

**Comment by iltempe** [comment]
qui si deve decidere se continuare a mettere in lista tutte le segnalazioni in unica pagina o dividerle per categorie. Personalmente sarei per creare ANCHE le pagine separate di ogni categoria. Ed il motivo è legato al fatto che se si deve condividere una categoria via social lo trovo più agevole. La pagina ISSUE può comunque essere lasciata per tutto come archivio. Ma attendo di vedere un po' di commenti qui sotto per capire cosa sia meglio fare.

**Comment by cristigalas** [comment]
> qui si deve decidere se continuare a mettere in lista tutte le segnalazioni in unica pagina o dividerle per categorie. Personalmente sarei per creare ANCHE le pagine separate di ogni categoria. Ed il motivo è legato al fatto che se si deve condividere una categoria via social lo trovo più agevole. La pagina ISSUE può comunque essere lasciata per tutto come archivio. Ma attendo di vedere un po' di commenti qui sotto per capire cosa sia meglio fare.

Sì, pensandoci e rivedendo bene quanto fatto finora sul sito, credo anch’io che sia meglio fare pagine ad hoc, anche perché così eviteremo che le pagine siano tutte uguali. Mi spiego: se ad es. clicco sulla home “Iniziative solidali” e la esplodo mi si apre una pagina che si chiama Segnalazioni e che presenta lo stesso titolo e gli stessi bottoni della pagina Tutte le Segnalazioni. Stessa cosa per Raccolte fondi. Ciò può generare confusione in chi le consulta. Se, invece, clicco su Fonti Istituzionali mi si apre una pagina dedicata e tutto risulta più chiaro. Però è importante secondo me, così come era per Tci, che TUTTE le segnalazioni siano sul sito nella sezione Tutte le Segnalazioni. E in questa sezione archivio suggerivo di inserire anche il bottone Altro, così da dare un bottone anche alle segnalazioni (poche) che non hanno categoria. Non so se mi sono spiegata 🙄

**Comment by iltempe** [comment]
Allora. Ho creato una pagina dedicata per ogni LABEL. va rivisto il layout dei singoli post rispetto alla pagina issue perchè attualmente son diversi. ma direi che ci sono tutte le pagine adesso.

**Comment by iltempe** [comment]
a posto. ho creato tutte le pagine per ogni label presente. ad esempio https://www.covid19italia.help/bollettino/

**Comment by iltempe** [comment]
a questo punto chiudo e riapro un altro issue generale sui link del sito.
