### ISSUE TITLE
Landing page emergenzeHack

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia#153]
Come menzionavo a @cristigalas , sarebbe utile ripristinare una semplice landing page su emergenzehack.github.io per poter poi citare "emergenzeHack" come il progetto padre e gruppo di volontari collegato *anche* a TCI, per poter dare un nome (ed eventualmente dei volti) a questo lavoro.

Cosa ne pensate?

**Comment by cristigalas** [comment]
Anche secondo me sarebbe utile...

**Comment by iltempe** [comment]
@avivace ma serve davvero?

**Comment by iltempe** [comment]
c'ho pensato. effettivamente #emergenzehack secondo me è anche un buon modo per identificare la "community" di civic hackers italiani che ha operato in TCI e qui. C'è il sito, il logo e i contributori. Potremmo anche metterlo più in chiaro in About in modo che sia un po' più evidente il soggetto.

**Comment by avivace** [comment]
Yay! Ti sei convinto, ci lavoro nei prossimi giorni

**Comment by iltempe** [comment]
@avivace direi che lo chiudo, poi col tempo e senza fretta ci lavoriamo. posso darti mano

**Comment by avivace** [comment]
@iltempe Ops, mi ero dimenticato di chiudere. La pagina è online qui: https://emergenzehack.github.io/
