### ISSUE TITLE
Marker delle segnalazioni su mappa con icone

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#154]
In fondo al file issues.md sono definiti alcuni marker usando fontawesome (vedi esempio sotto).

Attualmente le issue vengono messe su mappa come semplice marker.

Definire delle icone e dei colori sensati e usarli per i marker.

Esempio:
```
var alloggiMarker = L.AwesomeMarkers.icon({
icon: 'home',
prefix: 'fa',
markerColor: 'green'
});
var fabbisogniMarker = L.AwesomeMarkers.icon({
icon: 'child',
prefix: 'fa',
markerColor: 'blue'
});
var notizieutiliMarker = L.AwesomeMarkers.icon({
icon: 'newspaper-o',
prefix: 'fa',
markerColor: 'orange'
});
var donazioniMarker = L.AwesomeMarkers.icon({
icon: 'handshake-o',
prefix: 'fa',
markerColor: 'red'
});
var raccoltefondiMarker = L.AwesomeMarkers.icon({
icon: 'money',
prefix: 'fa',
markerColor: 'blue'
});

              var markerLocation = new L.LatLng(lat, lon);
                if (type == 'Donazioni') {
                        var marker = new L.Marker(markerLocation, {icon: donazioniMarker});
                } else if (type == 'Alloggi') {
                        var marker = new L.Marker(markerLocation, {icon: alloggiMarker});
                } else if (type == 'Fabbisogni') {
                        var marker = new L.Marker(markerLocation, {icon: fabbisogniMarker});
                } else if (type == 'Notizie Utili') {
                        var marker = new L.Marker(markerLocation, {icon: notizieutiliMarker});
                } else if (type == 'Raccolte Fondi') {
                        var marker = new L.Marker(markerLocation, {icon: raccoltefondiMarker});
                } else {
                        var marker = new L.Marker(markerLocation);
                }
```

**Comment by Jolsty** [comment]
@mfortini Come vogliamo assegnare i diversi tipi di marker? In base alle label?
Perchè questo mi crea un problema visto che una issue può avere più label assegnate.. ad esempio ["Servizi e iniziative solidali private", "Supporto psicologico"]

**Comment by mfortini** [comment]
Giustissima domanda. Giro a @cristigalas @favoeva @Saraveg @iltempe 
In teoria possiamo anche mettere un marker per ogni categoria per ogni segnalazione (ovvero possono venire doppi). Forse sarebbe utile poterne spegnere/accendere

**Comment by Saraveg** [comment]
propongo @cristigalas @favoeva @chiccap se non sbaglio tutte: supporto psico, consegne e sono iniziative solidali. quindi si potrebbe proporre:
iniziative solidali
raccolte fondi
richiesta aiuto (che è diversa?)

**Comment by chiccap** [comment]
Per i colori assolutamente d'accordo a martenere quelli delle label e sarebbe bellissimo se si potesse spegnere/accendere come dice @mfortini. Invece ho timore che il marker con l'icona occupi tanto spazio sulla mappa e diventi solo una macchia informe :)

**Comment by chiccap** [comment]
> iniziative solidali
> raccolte fondi
> richiesta aiuto (che è diversa?)

Anche supporto psicologico!

**Comment by Jolsty** [comment]
Ok quindi avremo soltanto questi 4 marker: 
- Iniziative solidali 
- Raccolte fondi
- Richiesta aiuto
- Supporto psicologico

Confermate? @chiccap @Saraveg  @cristigalas

**Comment by iltempe** [comment]
ma perchè non tutte le tipologie?

**Comment by mfortini** [comment]
Considera @chiccap che i marker son piccolini, stanno dentro alla goccia che c'è ora

> Per i colori assolutamente d'accordo a martenere quelli delle label e sarebbe bellissimo se si potesse spegnere/accendere come dice @mfortini. Invece ho timore che il marker con l'icona occupi tanto spazio sulla mappa e diventi solo una macchia informe :)

**Comment by Jolsty** [comment]
@Saraveg @mfortini @iltempe @chiccap 
Controllate pure le icone. Per ora sono gestite solo quelle 4 label, fate sapere se va bene

I marker senza icona son quelle che non hanno una label che fanno parte di quelle 4 gestite

**Comment by gorobey** [comment]
> 
> 
> @Saraveg @mfortini @iltempe @chiccap
> Controllate pure le icone. Per ora sono gestite solo quelle 4 label, fate sapere se va bene
> 
> I marker senza icona son quelle che non hanno una label che fanno parte di quelle 4 gestite

Ottimo! ho trovato la risposta alla mia domanda.
Volevo chiedere come hai quello che segnalavo veniva fuori con un marker viola senza icona.
Propongo di odificare i form mettendo dei menu a tendina, altrimenti qui vien fuori solo casino.

**Comment by avivace** [comment]
> > @Saraveg @mfortini @iltempe @chiccap
> > Controllate pure le icone. Per ora sono gestite solo quelle 4 label, fate sapere se va bene
> > I marker senza icona son quelle che non hanno una label che fanno parte di quelle 4 gestite
> 
> Ottimo! ho trovato la risposta alla mia domanda.
> Volevo chiedere come hai quello che segnalavo veniva fuori con un marker viola senza icona.
> Propongo di odificare i form mettendo dei menu a tendina, altrimenti qui vien fuori solo casino.

Proposta esclusa in fase iniziale di progettazione form da @cristigalas perchè altrimenti viene troppo "dettagliata" la segnalazione, la categorizzazione a quel livello di granularità la facciamo noi con le label sulle Issue.

Vi torna?

**Comment by gorobey** [comment]
> 
> 
> > > @Saraveg @mfortini @iltempe @chiccap
> > > Controllate pure le icone. Per ora sono gestite solo quelle 4 label, fate sapere se va bene
> > > I marker senza icona son quelle che non hanno una label che fanno parte di quelle 4 gestite
> > 
> > 
> > Ottimo! ho trovato la risposta alla mia domanda.
> > Volevo chiedere come hai quello che segnalavo veniva fuori con un marker viola senza icona.
> > Propongo di odificare i form mettendo dei menu a tendina, altrimenti qui vien fuori solo casino.
> 
> Proposta esclusa in fase iniziale di progettazione form da @cristigalas perchè altrimenti viene troppo "dettagliata" la segnalazione, la categorizzazione a quel livello di granularità la facciamo noi con le label sulle Issue.
> 
> Vi torna?
si, ma:
se sono state decise delle icone per categorizzare, quando la segnalazione aprte dal sito non funzionerà praticamenta mai, non dico di far solo menu a tendina, ma per le categorie scelte (che sono quelle che campeggiano in home) direi che sia una cosa utile.

**Comment by cristigalas** [comment]
Scusate ma non vi seguo... spiegate meglio il problema?

**Comment by gorobey** [comment]
@cristigalas quando faccio una segnalazione attraverso un form del sito clicco su un bottone, questo mi porta a un form differente, e quindi tecnicamente categorizza la mia segnalazione, la categoria dovrebbe quindi essere già un parametro stabilito (infatti lo trovo nella categoria corretta, ma non è così nella mappa), erro? sbaglio io nel segnalare? e anche se fosse così non è forse migliorabile in modo che sulla mappa appaia

**Comment by cristigalas** [comment]
Ah ok, grazie! Adesso ho capito... e come migliorare? Non usando form esterno? Ma io non sono una tecnica e dunque lascio a voi. 
L’unica cosa che posso dire è che le segnalazioni devono arrivare su macro categorie, poi è chi si occupa di processarle e pubblicarle che deve attribuire label più specifiche...

**Comment by iltempe** [comment]
@mfortini si può chiudere?

**Comment by mfortini** [comment]
Chiudiamo perché adesso le segnalazioni hanno le icone (definite in issuecategories.yml)
