### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#159]
Quando qualcuno condivide link soprattutto sui social, è importante che venga fuori qualcosa di "carino".
Finora chi ha condiviso ha fatto screenshot. Riusciamo a generare in automatico qualche immagine o comunque ad assegnare i campi per la condivisione in modo che sia chiaro che la notizia viene da covid19italia.help?

**Comment by avivace** [comment]
Considererei anche di mantenere una tipografia e palette coerente

**Comment by Albertopi78** [comment]
@mfortini se l'immagine di preview fosse l'icona corrispondente alla segnalazione, per Twitter andrebbe molto bene, secondo me. Per Facebook ci vorrebbe un'immagine ad hoc per differenziare le varie segnala. Ma basterebbe anche il logo oppure il disegno di costantini tagliato in modo che si veda bene in preview.
![covid19italiahelp](https://user-images.githubusercontent.com/42850988/76689370-788c9380-6635-11ea-8d6b-157fa959c940.jpeg)

**Comment by iltempe** [comment]
ma questo è chiudibile?

**Comment by iltempe** [comment]
chiudo.
