### ISSUE TITLE
Pagine di servizio del portale

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#16]
Oltre alle categorie delle segnalazioni aprirei anche

- Blog
- About e Contatti
- Press
- Opendata

Altro?

**Comment by cristigalas** [comment]
@iltempe ho buttato giù il testo about e contatti riprendendo quello di Tci. Naturalmente è una bozza... 

_Covid19Italia è un progetto non profit, promosso e gestito interamente da volontari. È nato per condividere informazioni utili e verificate sull’emergenza coronavirus in Italia.

Il progetto ha lo scopo di aggregare e diffondere contenuti utili provenienti da fonti ufficiali e non, al fine di offrire supporto e sostegno in un momento di grande emergenza per il Paese.

Il progetto non vuole in alcun modo sostituirsi a fonti istituzionali di informazione che incoraggiamo a consultare sempre.

Il progetto, laddove lo si ritenga utile, è usabile da organizzazioni non profit, associazioni, gruppi informali e pubbliche amministrazioni che avessero bisogno di un servizio per informare su quanto sta avvenendo in seguito alla diffusione del coronavirus.

Il progetto è descritto tramite il nostro wiki.

Il progetto nasce con il supporto di Action Aid Italia e per iniziativa di.... [mettiamo i nomi di tutti?]_

CONTATTI
Email
Twitter
Instagram
Pagina Facebook
Gruppo Telegram 
Repository Github 
Feed RSS
App

**Comment by cristigalas** [comment]
> Oltre alle categorie delle segnalazioni aprirei anche
> 
> * Blog
> * About e Contatti
> * Press
> * Opendata
> 
> Altro?

* Link utili

**Comment by cristigalas** [comment]
@iltempe ecco i contatti (manca solo RSS):

**CONTATTI**
[Email](mailto:covid19ita@gmail.com)
[Twitter](https://twitter.com/ItaliaCovid19)
[Instagram](https://www.instagram.com/covid19italia.info/)
[Gruppo Telegram ](http://t.me/covid19italia)
[Canale Telegram](https://t.me/COVID19I)
[Repository Github](https://github.com/emergenzeHack/covid19italia) 
Feed RSS

**Comment by iltempe** [comment]
aggiunti. chiudo.
