### ISSUE TITLE
Sezione rassegna stampa

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/covid19italia#161]
Come per tci creiamo un file rassegna che poi va in una sezione specifica del sito, che ne dite?
Qui già parlano di noi: https://magazine.fbk.eu/it/news/labbraccio-collettivo-della-tecnologia/?fbclid=IwAR1X8Sf1MnuY66HWJskcy-ZIfcNawViWbEQ9f2Wkm2MT_r7K1yE_Qyfz4Hw

@cristigalas @dontyna @favoeva @Saraveg

**Comment by Albertopi78** [comment]
Sì. La sezione c'è già, sto imparando a popolarla @chiccap :-D
intanto mi appunto questi altri due link che poi aggiungerò 

https://www.slow-news.com/contenuti/covid19italia-help/ (fatto da me, ma non si sa mai)
https://www.focusicilia.it/2020/03/13/covid19italia-help-un-aiuto-contro-il-virus/

**Comment by chiccap** [comment]
@Albertopi78  Se mi dai il file in cui aggiungere la rassegna ti aiuto mano a mano!

**Comment by favoeva** [comment]
https://github.com/emergenzeHack/covid19italia/wiki/Come-si-inserisce-un-elemento-in-PRESS

**Comment by iltempe** [comment]
chiudo. se mai volessimo fare una pagina SOLO per i PRESS si può fare. in caso apriamo altro issue.
