### ISSUE TITLE
Sul sito manca pagina e bottone per label RICHIESTE AIUTO

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#162]
Sul [gruppo Telegram ](https://t.me/c/1305892550/1509)ci fanno notare che ci sono richieste da parte degli ospedali che cercamo medici e infermieri e che sul sito questo tipo di richieste al momento non ci sono. In realtà la label c’è: RICHIESTA AIUTO, manca pagina ad hoc sul sito. 

@iltempe @Saraveg @avivace @chiccap @favoeva la facciamo e poi mettiamo semmai un bottone in homepage oppure in Iniziative solidali? 

Nel frattempo ho visto che qualche richiesta di aiuto è arrivata, sono ancora poche ma forse meritano una particolare attenzione e visibilità. Che dite? Comunque al momento, poche o molte, sul sito non ci sono e questo credo vada risolto comunque...

**Comment by iltempe** [comment]
la pagina c'è già. https://www.covid19italia.help/richiesta/ ditemi dove volete il link e ve lo piazzo ;-)

**Comment by iltempe** [comment]
le ho messe in home page. chiudo.
