### ISSUE TITLE
Sezione Storie

### ISSUE THREAD

**Issue by dontyna** [emergenzeHack/covid19italia#169]
Aggiungiamo una sezione "Storie"?
Opzioni:

- categoria del blog
- nuova sezione del sito

**Comment by iltempe** [comment]
Ciao @dontyna la pagina Storie esiste già, eccola https://www.covid19italia.help/storie/
Non è accessibile da nessun link al momento. Se ti piace il layout possiamo gestirla come TCI ovvero popolando come POST questa cartella GITHUB (che contiene ancora i post di TCI). https://github.com/emergenzeHack/covid19italia/tree/master/_storie

**Comment by iltempe** [comment]
@dontyna ho risistemato un po' la pagina Storie è pronta per essere popolata. Ho lasciato un vecchio post di TCI che ha ancora senso giusto per ricordarci il template da compilare per compilare una storia. https://www.covid19italia.help/storie/

**Comment by cristigalas** [comment]
@iltempe intanto potremmo pubblicare il testo del post che abbiamo fatto per il blog del Giornale della protezione civile. Questo qui https://blog.ilgiornaledellaprotezionecivile.it/terremotocentroitalia/2020/03/17/covid19italia-help-riuso-creativo-lecologia-del-civic-hacking/
Qui il GoogleDoc https://docs.google.com/document/d/1Z17i4un6LEoohaKoH2AYh6HVVC0sMqcBTpjtI8BRx2M

**Comment by iltempe** [comment]
E' online con una prima storia pubblicata da @favoeva qui https://www.covid19italia.help/storie/

**Comment by cristigalas** [comment]
@iltempe si può chiudere qui.
