### ISSUE TITLE
Pubblicazione giornaliera dati ufficiali COVID-19 Italia

### ISSUE THREAD

**Issue by parallelit** [emergenzeHack/covid19italia#170]
Propongo l'integrazione sul canale Telegram **COVID19I** del mio bot **@CovidItaliaBot** che estrae i dati ufficiali COVID-19 Italia da qui https://github.com/pcm-dpc/COVID-19 e li pubblica.

Un esempio dei dai pubblicati lo trovate su questo canale https://t.me/coviddata.

Il bot pubblica **SOLO** questi dati una volta al giorno, all'aggiornamento del repository GitHub citato sopra.

Ho anticipato questa PR con @iltempe e Cristina su Telegram.

**Comment by iltempe** [comment]
cosa intendi per integrazione? usare il tuo bot per pubblicare su nostro canale automaticamente?

**Comment by parallelit** [comment]
@iltempe mi sembra il modo più semplice. Il bot può essere rimosso in ogni momento da voi dal canale.

Oppure posso fare una POST HTTP/S verso un vostro endpoint.

Si accettano proposte alternative. 

La cosa importante è evitare azioni manuali da parte mia.

**Comment by iltempe** [comment]
ok. mi piacerebbe sentire altri pareri. per me se il bot non "inquina troppo" e si mantiene su un post al giorno si può fare @cristigalas @favoeva @Saraveg @mfortini ?

**Comment by cristigalas** [comment]
Anche per me va bene se è solo un post al giorno. Sarebbe però possibile aggiungere in calce al post link alla fonte? Immagino che la fonte dei dati sia la protezione civile e in link renderebbe l’informazione più completa e attendibile. Del resto, noi non diamo info o dati senza citare la fonte.

**Comment by salvatorecordiano** [comment]
@cristigalas si è possibile citare la fonte in calce

**Comment by parallelit** [comment]
@cristigalas si è possibile citare la fonte in calce

**Comment by cristigalas** [comment]
> @cristigalas si è possibile citare la fonte in calce

Ottimo! 

Allora @iltempe @Saraveg @mfortini @favoeva io procederei. Con l’aggiunta del link fonte mi pare che sia un post utile sul nostro canale...

**Comment by parallelit** [comment]
@cristigalas @iltempe se mi contattate su Telegram procediamo, così già questa sera ci sarà la prima pubblicazione

**Comment by cristigalas** [comment]
@iltempe ci pensi tu che sei il capo sviluppatore? 😜

**Comment by iltempe** [comment]
@cristigalas non sono il capo di un bel nulla ;-) @parallelit ti contatto e lo mettiamo in piedi. qui chiudo.
