### ISSUE TITLE
Rimuovere campi latitudine / longitudine in form

### ISSUE THREAD

**Issue by dontyna** [emergenzeHack/covid19italia#171]
La mia è una proposta per toglierli: si rischia di confondere l’utente e da mobile fanno casino con il form.

@iltempe @mfortini @avivace

**Comment by iltempe** [comment]
ma toglierli o nasconderli? @avivace  se pole fare?

**Comment by avivace** [comment]
Non ne ho idea se è possibile con il widget "prefabbricato" che stiamo usando.. @Jolsty secondo te è possibile? Bisognerebbe trovare la documentazione dei quel particolare "tipo di campo"

**Comment by Jolsty** [comment]
@avivace  Onestamente non lo so, è abbastanza un casino quella roba. Le uniche documentazioni che ho trovato sono http://xlsform.org/en/#appearance e https://support.kobotoolbox.org/en/articles/592418-list-of-question-types e non trovo comunque qualcosa di utile che riguardano le mappe..

**Comment by iltempe** [comment]
@aborruso secondo te si può fare?

**Comment by aborruso** [comment]
@iltempe c'è l'opzione di _appearance_  `maps hide-input` che rimuove i campi lat e lon.

L'esempio è la prima mappa di questo form https://enketo.ona.io/x/#HqyyE1VO

Allego file definizione di esempio

[notLatLon.zip](https://github.com/emergenzeHack/covid19italia/files/4333398/notLatLon.zip)

**Comment by avivace** [comment]
Grazie @aborruso !
Tutti i form non hanno più i campi longitudine e latitudine  e appaiono così:
![immagine](https://user-images.githubusercontent.com/14352721/76692004-f5793680-6650-11ea-81ae-3bb9a7ceb85b.png)

**Comment by dontyna** [comment]
Scusate se riapro ma ho cliccato su ["Segnala iniziative e servizi"](https://ee.humanitarianresponse.info/x/#6KafBk33) e vedo ancora così:
![Schermata 2020-03-15 alle 15 16 52](https://user-images.githubusercontent.com/6824007/76703178-0a48df00-66d0-11ea-8d93-c941d84236e7.png)

**Comment by aborruso** [comment]
@dontyna secondo me è cache. Prova in una sessione anonima del browser.

Io la vedo senza lat e lon
