### ISSUE TITLE
Policy per approvazione segnalazioni

### ISSUE THREAD

**Issue by Albertopi78** [emergenzeHack/covid19italia#172]
L'esigenza è partita dalle approvazioni sul gruppo di Facebook, ma potrebbe tornar utile in generale. 
Ecco qua un file-bozza con alcuni casi che si sono già presentati:

https://docs.google.com/document/d/1Vs9IelFCg9U3vBdHEPIyObMtrS2v9ql_ES0_vHxqtow/edit?usp=sharing

**Comment by favoeva** [comment]
> L'esigenza è partita dalle approvazioni sul gruppo di Facebook, ma potrebbe tornar utile in generale.
> Ecco qua un file-bozza con alcuni casi che si sono già presentati:
> 
> https://docs.google.com/document/d/1Vs9IelFCg9U3vBdHEPIyObMtrS2v9ql_ES0_vHxqtow/edit?usp=sharing

Collegata a #158

**Comment by favoeva** [comment]
Riflessione che prende spunto da questa conversazione nel gruppo FB 

https://www.facebook.com/groups/covid19italia/permalink/2929839583704876?sfns=mo

Caso: servizio supporto psicologico non pubblico . 

Problema : potrebbero essere tentativi di agganciare anziani soli per truffe ed altro :(

Diamoci una linea

**Comment by Albertopi78** [comment]
@favoeva non credo abbiamo altra scelta che accettare solo iniziative riconducibili a strutture verificate.

**Comment by chiccap** [comment]
> @favoeva non credo abbiamo altra scelta che accettare solo iniziative riconducibili a strutture verificate.

Sí forse dovremmo non accettare che iniziative che possiamo verificare. Credo però che dovremmo iniziare a fare lo stesso pensiero per le raccolte fondi, sono tantissime.

**Comment by favoeva** [comment]
è abbastanza urgente definire questa cosa. 
In TCI non verificavamo tutto ma solo quello che in qualche modo 'non ci tornava' (corretto @cristigalas ?)
Qui la fragilità dei destinatari è ancora più accentuata e dovremmo valutare se e come richiedere un contatto per verifica, insieme alla segnalazione. 
So che questo potrebbe impallare il tutto, ma se decidiamo che le categorie a cui applichiamo questa procedura sono solo supporto psicologico e raccolta fondi, forse diventa sostenibile .
Ditemi

**Comment by Saraveg** [comment]
sulle RACCOLTE FONDI la verifica è molto difficile. e poi penso che collezionarle significa anche tracciarle eventualmente per monitorarle (adesso o in futuro). Sulle offerte di supporto psicologico possiamo verificare o che siano di associazioni/enti riconosciuti (anche se, per dire, io ho inserito una mia amica di Palermo, psicologa che sono certa lo faccia davvero probono, quella discrezionalità della conoscenza personale la condidererei.) o di enti pubblici.

**Comment by favoeva** [comment]
Per le bufale che ne dite se lanciamo le card per Canva su IG ?

**Comment by chiccap** [comment]
> Per le bufale che ne dite se lanciamo le card per Canva su IG ?

Siiii che bella idea!

**Comment by cristigalas** [comment]
Per le raccolte fondi sono d’accordo con @Saraveg, le accoglierei tutte e poi se c’è qualcosa che non ci torna non le accettiamo. Terrei quindi la linea Tci. 
Per il supporto psicologico è certo più complesso decidere una linea. Però intanto potremmo fare due cose, non troppo complicate ma, secondo me, utili a contenere eventuali criticità: 
1. Aggiungere nella form “Dona beni e servizi” un **campo per allegare curriculum vitae** spiegando che per psicologi, medici e altri professionisti in ambito socio-sanitario è obbligatorio allegare il cv. Senza cv la segnalazione non viene accettata e pubblicata.
2. Inoltre possiamo usare i **database regionali degli ordini dei psicologi** per verificare che siano iscritti all’albo ([vedi ad es. qui](https://www.ordinepsicologitoscana.it/iscritti-ricerca-avanzata.php)). Con Tci qualche volta lo abbiamo fatto, ad es. per i medici. Ricordi @chiccap? 

Che ne dite?

**Comment by Saraveg** [comment]
1. CV PSI: pero' ci sono le associazioni. solo noi lavoriamo o abbiamo lavorato con psyplus, esprì, emergency, sipem, 180amici. e ce ne sono molte altre. quindi direi che sindacare è difficile. per i singoli ok. si potrebbe dire allega il cv (o il sito dell'associazione). poi ci sono gli ordini e i servizi offerti dagli enti locali (comuni, comunità montane, ambiti ecc...) quelli ci vanno.
2. sul controllo dei professionisti è un inizio ma certo non ti assicura un uso scorretto della professione.

**Comment by cristigalas** [comment]
>     1. CV PSI: pero' ci sono le associazioni. solo noi lavoriamo o abbiamo lavorato con psyplus, esprì, emergency, sipem, 180amici. e ce ne sono molte altre. quindi direi che sindacare è difficile. per i singoli ok. si potrebbe dire allega il cv (o il sito dell'associazione). poi ci sono gli ordini e i servizi offerti dagli enti locali (comuni, comunità montane, ambiti ecc...) quelli ci vanno.
Sì sì, il cv lo chiediamo solo ai singoli... secondo me un po' scoraggia imbroglione o chi vuole abusare e poi così anche gli utenti possono leggerlo e farsi un'idea.
>     2. sul controllo dei professionisti è un inizio ma certo non ti assicura un uso scorretto della professione.
Sì certo, non assicura ma aiuta...

**Comment by chiccap** [comment]
@Saraveg @cristigalas @favoeva apriamo issue e chiediamo di aggiungere al form “Dona beni e servizi” sezione CV e sito associazione?

**Comment by cristigalas** [comment]
> @Saraveg @cristigalas @favoeva apriamo issue e chiediamo di aggiungere al form “Dona beni e servizi” sezione CV e sito associazione?

Per me va bene cominciare così e poi vediamo... ma sentiamo @Saraveg e @favoeva prima di procedere con nuova issue.

**Comment by Saraveg** [comment]
@cristigalas proviamo così.
Bisogna cmq lavorare ancora sulla policy generale. teniamo il doc di @Albertopi78 ?

**Comment by Albertopi78** [comment]
@cristigalas @Saraveg @favoeva 
quando leggo casi che discutete e trovate una linea li metto tutti qui
https://docs.google.com/document/d/1Vs9IelFCg9U3vBdHEPIyObMtrS2v9ql_ES0_vHxqtow/edit#

**Comment by cristigalas** [comment]
> @cristigalas proviamo così.
> Bisogna cmq lavorare ancora sulla policy generale. teniamo il doc di @Albertopi78 ?

Sì, sì anzi ho colto l’occasione per fare qualche piccola aggiunta.

**Comment by cristigalas** [comment]
Allora apro nuova issue per introdurre le seguenti modifiche:

Aggiungere nella form “Dona beni e servizi” un campo per allegare curriculum vitae spiegando che per psicologi, medici e altri professionisti in ambito socio-sanitario è obbligatorio allegare il cv. Senza cv la segnalazione non viene accettata e pubblicata. Idem per campo link in caso di associazioni. Se non c’è un link che rimanda all’associazione non accettiamo.

**Comment by favoeva** [comment]
> > Per le bufale che ne dite se lanciamo le card per Canva su IG ?
> 
> Siiii che bella idea!

chi gestisce IG alla fine? mi sono persa un po' ;)
ci sei tu @chiccap ?

**Comment by chiccap** [comment]
> > > Per le bufale che ne dite se lanciamo le card per Canva su IG ?
> > 
> > 
> > Siiii che bella idea!
> 
> chi gestisce IG alla fine? mi sono persa un po' ;)
> ci sei tu @chiccap ?

Al momento solo @dontyna, non ci ho ancora messo mano! Vedi #189 Dobbiamo ancora coordinarci!

**Comment by favoeva** [comment]
> > @Saraveg @cristigalas @favoeva apriamo issue e chiediamo di aggiungere al form “Dona beni e servizi” sezione CV e sito associazione?
> 
> Per me va bene cominciare così e poi vediamo... ma sentiamo @Saraveg e @favoeva prima di procedere con nuova issue.

visto che la issue non è ancora stata affrontata lato dev. , mi chiedo se potrebbe essere una valida alternativa chiedere almeno un link al profilo linkedIN? per non scoraggiarli troppo gli psicologi ;)

**Comment by cristigalas** [comment]
@favoeva intendi profilo Linkedin al posto del cv? Però profilo LinkedIn possono non averlo tutti, cv sì... comunque uno degli obiettivi è proprio quello di scoraggiarli ;)

**Comment by avivace** [comment]
Credo ci sia un problema di fondo sul lato tecnico: tutti i dati inseriti nelle segnalazioni diventano pubblici, potenzialmente **per sempre** (nonostante le modifiche). Dovremmo iniziare a scindere i dati che vengono visualizzati pubblicamente sull'Issue (e  che quindi finiscono sul sito) e quelli che vengono inviati, permettendo ad un gruppo ristretto di persone di visionare e limitare alcuni campi.

**Comment by federicarizzo** [comment]
> sulle RACCOLTE FONDI la verifica è molto difficile. e poi penso che collezionarle significa anche tracciarle eventualmente per monitorarle (adesso o in futuro). Sulle offerte di supporto psicologico possiamo verificare o che siano di associazioni/enti riconosciuti (anche se, per dire, io ho inserito una mia amica di Palermo, psicologa che sono certa lo faccia davvero probono, quella discrezionalità della conoscenza personale la condidererei.) o di enti pubblici.

Sulle RACCOLTE FONDI inserirei due tre cose minime. E' un lavoraccio però si potrebbe cominciare facendo una piccola verifica, seguendo quello che le associazioni di fundraiser stanno facendo, ovvero verificare che ci sia accordo tra chi lancia la raccolta e l'azienda ospedaliera destinataria delle donazioni. Moltissime hanno smentito. Ci sono ostacoli oggettivi (e di mentalità purtroppo) però esistono. Certo, non ci si puo lanciare nella verifica della seconda fase (rendicontazione) però una piccola verifica la farei. Sono troppe, dispersive e a volte purtroppo inutili se l'ospedale non ha dato l'ok.

**Comment by Saraveg** [comment]
@federicarizzo intanto le direzioni sanitarie della regione piemonte ci stanno mandando aggiornamenti come questa mail che ti incollo qua. Potremmo chiedere ad altre direzioni sanitarie di fare lo stesso?
(poi si apre un problema sulle segnalazioni: ne facciamo tante quante sono le raccolte o una riassuntiva e "validata"?) @cristigalas et all

Gentilissimi,
sono Tiziana Guidetto, la Responsabile dell'Ufficio Relazioni Esterne dell'ASL TO4 (Regione Piemonte). Ho appena segnalato nella vostra piattaforma la nostra campagna istituzionale per la raccolta fondi per covid-19. 
Siamo anche a conoscenza di iniziative serie organizzate da associazioni e da privati tramite la piattaforma GoFundMe per raccogliere fondi a favore dell'ASL TO4 per l'emergenza da coronavirus covid-19. Di seguito le indico; per cortesia potete caricarle voi nella vostra piattaforma? Grazie infinite
Tiziana Guidetto
Cell. 3355812438

https://www.gofundme.com/f/aiutiamo-lospedale-di-ivrea?utm_source=customer&utm_medium=copy_link&utm_campaign=p_cf+share-flow-1

https://www.gofundme.com/f/d23wzf-coronavirusrafforziamo-la-terapia-intensiva

https://www.gofundme.com/f/coronavirus-asl-to4-ivrea-chivasso-cirie?utm_source=whatsapp-visit&utm_medium=chat&utm_campaign=p_cp+share-sheet

https://www.gofundme.com/f/emergenza-coronavirus-aslto4-cuorgne

**Comment by federicarizzo** [comment]
#raccoltefondi 
Aggiungo alcuni commenti sulla parte delle policy dedicata alla raccolta fondi.
- Le donazioni possono venire da privati, aziende o fondazioni. Quindi non escluderei quelle avviate da non privati.
- I criteri per la verifica, in questo momento emergenziale e di grande proliferazione di raccolte fondi, non possono essere molti ma almeno uno, così come esercitato dalle maggiori associazioni di fundraiser italiane, ovvero: verificare che ci sia un **accordo** tra chi lancia la raccolta fondi e l'azienda ospedaliera.
Questo perchè? perche molti ospedali non possono accettare denaro ma solo macchinari/attrezzature; perchè quel macchinario per il quale decido di raccogliere fondi magari è già coperto da altri fondi, per esempio dalla protezione civile.
poi il problema della rendicontazione sarà un altro problema...ma almeno si dà un criterio di verifica univoco.
sul sito italianoprofit ci sono le raccolte fondi al momento attive secondo questo criterio.

**Comment by federicarizzo** [comment]
> @federicarizzo intanto le direzioni sanitarie della regione piemonte ci stanno mandando aggiornamenti come questa mail che ti incollo qua. Potremmo chiedere ad altre direzioni sanitarie di fare lo stesso?
> (poi si apre un problema sulle segnalazioni: ne facciamo tante quante sono le raccolte o una riassuntiva e "validata"?) @cristigalas et all
> 
> Gentilissimi,
> sono Tiziana Guidetto, la Responsabile dell'Ufficio Relazioni Esterne dell'ASL TO4 (Regione Piemonte). Ho appena segnalato nella vostra piattaforma la nostra campagna istituzionale per la raccolta fondi per covid-19.
> Siamo anche a conoscenza di iniziative serie organizzate da associazioni e da privati tramite la piattaforma GoFundMe per raccogliere fondi a favore dell'ASL TO4 per l'emergenza da coronavirus covid-19. Di seguito le indico; per cortesia potete caricarle voi nella vostra piattaforma? Grazie infinite
> Tiziana Guidetto
> Cell. 3355812438
> 
> https://www.gofundme.com/f/aiutiamo-lospedale-di-ivrea?utm_source=customer&utm_medium=copy_link&utm_campaign=p_cf+share-flow-1
> 
> https://www.gofundme.com/f/d23wzf-coronavirusrafforziamo-la-terapia-intensiva
> 
> https://www.gofundme.com/f/coronavirus-asl-to4-ivrea-chivasso-cirie?utm_source=whatsapp-visit&utm_medium=chat&utm_campaign=p_cp+share-sheet
> 
> https://www.gofundme.com/f/emergenza-coronavirus-aslto4-cuorgne

Ciao Sara, ottimo, ben vengano!
basterebbe anche una telefonata all'ufficio stampa, se da loro non arriva nulla.

**Comment by federicarizzo** [comment]
Sto cercando di capire come potenziare le raccolte fondi. Quando ce ne sono cosi tante per un unico obiettivo, c'è dispersione e il donatore puo rassegnarsi a non donare per non dover scegliere tra le tante quale è la piu affidabile.
Ipotesi: chiedere all'azuenda ospedaliera di fare un comunicato sta,pa e pubblicare su proprio sito anche qualo raccolte fondi approva.
Si puo chiedere a questa tiziana, per esempio.
Loro, le aziende ospedaliere, sono gli unici che possono mettere il timbro di  "approved" ad una raccolta fondi. Questo spinge il donatore a donare.

**Comment by cristigalas** [comment]
@iltempe si può chiudere.
