### ISSUE TITLE
Segnalazioni vuote

### ISSUE THREAD

**Issue by Saraveg** [emergenzeHack/covid19italia#173]
![image](https://user-images.githubusercontent.com/22255392/76686756-0fe5ec80-661e-11ea-8530-1e25dbc142af.png)

**Comment by avivace** [comment]
Riesci a postare dei link? Cristina ce ne ha segnalate un po' qui: https://github.com/emergenzeHack/covid19italia_form/issues/25

**Comment by cristigalas** [comment]
Per segnalare le segnalazioni vuote ora si può usare label #DaSistemare e @avivace le sistema!
