### ISSUE TITLE
Problema compilazione Sito in Locale

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#175]
**Priorità**: bassa

## Richiesta
Su Mac non si compila 
facendo un bundle install si ottiene

An error occurred while installing sassc (2.2.1), and Bundler cannot continue.
Make sure that `gem install sassc -v '2.2.1' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  minima was resolved to 2.5.1, which depends on
    jekyll-feed was resolved to 0.13.0, which depends on
      jekyll was resolved to 4.0.0, which depends on
        jekyll-sass-converter was resolved to 2.1.0, which depends on
          sassc

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by Jolsty** [comment]
Io avevo un problema simile con tzinfo su windows, semplicemente ho aggiunto il pacchetto a mano nel Gemfile e fatto bundle install (se mi ricordo bene)

**Comment by iltempe** [comment]
l'ho aggiunto....ma continua a darmi errore quando installa sassc

**Comment by avivace** [comment]
@iltempe Puoi cancellare tutto, riclonare, cancellare il file Gemfile.lock (se ne hai uno) e riprovare?

**Comment by iltempe** [comment]
provato. ho solo il gemfile...il gemfile.lock no...è grave ;-)
