### ISSUE TITLE
gruppo FB: proposta edit del post fissato in alto

### ISSUE THREAD

**Issue by favoeva** [emergenzeHack/covid19italia#176]
**Priorità**: alta

## Testo della comunicazione

propongo un edit di questo post di @Albertopi78 https://www.facebook.com/groups/covid19italia/permalink/2927745393914295/

_Ciao! Una comunicazione di servizio. 
Questo gruppo è "pubblico". I post sono però sottoposti ad approvazione preventiva da parte del gruppo di lavoro.
Grazie a tutte e tutti per le segnalazioni che continuate a fare! Potete anche usare il form messo a disposizione sul sito del progetto QUI https://www.covid19italia.help/segnala/._

**Comment by favoeva** [comment]
avrei voluto scrivere VI INVITIAMO AD UTILIZZARE invece che POTETE USARE , ma mi sono sentita un po' troppo nazi :P
(effetto collaterale di 3 settimane di moderazione pagina fb comunale ai tempi del covid19)

**Comment by cristigalas** [comment]
Sì, forse @favoeva ha ragione... cambierei.

**Comment by Albertopi78** [comment]
Fatto ieri sera, si può chiudere :) 
Di tanto in tanto possiamo dare comunicazioni di servizio, tanto la comunicazione dopo un po', nel gruppo, esaurisce la sua forza e si può rinnovare. Siamo già in moltissimi e l'algoritmo sta già limitando la visibilità di quel che viene pubblicato, ovviamente.
Magari possiamo alternartivamente firmarci col profilo personale oltre che col logo, per ricordare a tutti che... siamo persone.  :)

**Comment by favoeva** [comment]
Ok chiudo grazie @Albertopi78 sei una forzissima e... sto imparando tanto 💪💪💪
