### ISSUE TITLE
Tenere traccia dell'andamento di Covid19Help

### ISSUE THREAD

**Issue by Saraveg** [emergenzeHack/covid19italia#177]
Troviamo un sistema per tracciare l'andamento del progetto.
Il 12 sera stavamo (più o meno) così:
AGGIORNAMENTO DATI 12/03/20
Attiviste/i (tra sviluppatori e non): 60
Segnalazioni processate di servizi: 365
di cui evidenziamo: 
Consegne e commissioni a domicilio: 62
Attività culturali e ricreative: 24
Attività didattica e e-learning: 6
Sostegno psicologico: 9
Sostegno a lavoro e imprese: 3
Giochi e intrattenimento per bambine/i: 5
Raccolte fondi: 49

Stasera ne possiamo fare un altro.
Cos'altro tracciare?
Gruppo fb?
followers tw?

**Comment by iltempe** [comment]
@Saraveg essendo i dati archiviati su GITHUB in qualunque momento possiamo visualizzare le metriche di un determinato giorno/ora. non dovrebbe essere complesso.

**Comment by avivace** [comment]
D'accordo, questi dati andrebbero nella Dashboard già menzionata da @iltempe qui: https://github.com/emergenzeHack/covid19italia/issues/167

**Comment by Saraveg** [comment]
ok, quindi qua chiudiamo e speriamo nella dashboard #167 :)
