### ISSUE TITLE
Una mappa per ogni tipo di segnalazione

### ISSUE THREAD

**Issue by Albertopi78** [emergenzeHack/covid19italia#178]
## Richiesta
Quando si clicca su un tipo di segnalazione, per esempio "supporto psicologico"
https://www.covid19italia.help/issues/#supporto-psicologico
sarebbe utile vedere una mappa con tutte e sole le attività di quel tipo.

## Risolto?
* [ ] Ho verificato che il problema è stato risolto

**Comment by iltempe** [comment]
ciao @Albertopi78 ci abbiamo lavorato io e @mfortini . è a posto. chiudo.
