### ISSUE TITLE
Attivazione di un Web Form x segnalazioni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#18]
In TCI avevamo questo https://www.terremotocentroitalia.info/segnala/. Attiviamo una cosa simile? Diversa? Dite la vostra.

**Comment by olistik** [comment]
In riferimento alla pagina della Wiki:

https://github.com/emergenzeHack/covid19italia/wiki/Come-funziona-(in-breve)-il-%22metodo-TCI%22

Il backend comprende anche l'app Heroku, giusto? Avrebbe senso menzionarlo anche in quella pagina IMHO.

https://terremotocentroitalia.herokuapp.com/segnalazioni/

Ce la portiamo dietro as-is (eventualmente con un parametro di contesto)?

Un'istanza Heroku free non mi sembra brutta, dato che le hit sul sito non dovrebbero corrispondere alle hit sull'applicazione.

A questo proposito vedo che invece https://www.terremotocentroitalia.info/segnala/ include via iframe e quindi per ogni visita contatta anche l'app Heroku.

Possiamo replicare tutto in questo progetto ma se volete possiamo anche solo trattare l'istanza Heroku (o vattelapesca) come un API server che viene contattato dal sito web e lasciare sul sito web un rendering statico del form (con i vari JS per la mappa, ovviamente) che spedisce i dati all'API server solo al submit.

A meno che non entrino in giochi automatismi server-side particolari durante la composizione della form. Ve ne risulta qualcuno?

**Comment by mfortini** [comment]
Grazie.
Per l'app heroku non l'ho seguita io, ma possiamo recuperare.
Abbiamo due scelte: configurare un'app heroku per le segnalazioni, oppure
usare AWS come ci hanno proposto, con le lambda dovrebbe essere simile.

Il lun 9 mar 2020, 13:38 olistik <notifications@github.com> ha scritto:

**Comment by olistik** [comment]
> ## Di cosa si tratta

> Amazon Web Service - AWS offre un pacchetto di crediti per fornire a Pubbliche Amministrazioni, organizzazioni non governative e non profit, startup e imprese, l'accesso a piano di supporto e canale di assistenza AWS per progetti legati all’emergenza

> ## Come aderire

> È possibile inviare le richieste di adesione via mail a awsforitaly@amazon.com

https://solidarietadigitale.agid.gov.it/#/

**Comment by cristigalas** [comment]
> In TCI avevamo questo https://www.terremotocentroitalia.info/segnala/. Attiviamo una cosa simile? Diversa? Dite la vostra.

Scusate se mi inserisco... la form ”Segnala” è secondo me fondamentale per gli utenti ma anche per noi, per inserire le segnalazioni. È un sistema molto agile anche da mobile. 

Pensando anche alle label che useremo per categorizzare le issue, nella form potremmo prevedere i seguenti campi:

- Chiedi aiuto
- Offri aiuto o servizi
- Segnala raccolte fondi
- Segnala documenti o dati
- Segnala notizie utili
- Segnala contatto utile
- Segnala iniziativa solidale
- Segnala bufale

**Comment by iltempe** [comment]
@Pinzauti qui sopra le segnalazioni che diceva @cristigalas . occhio che dove ha senso va sempre messa la geoferenziazione.

**Comment by avivace** [comment]
Ce ne stiamo occupando su: https://github.com/emergenzeHack/covid19italia_form
Spostiamo pure le segnalazioni e feedback sui singoli form e moduli disponibili lì (sempre come Issues)

Le risposte ai form vengono invece inviate come Issues qui: https://github.com/emergenzeHack/covid19italia_segnalazioni

**Comment by iltempe** [comment]
questo è fatto?

**Comment by cristigalas** [comment]
Qui la web form https://covid19italia.netlify.com/segnala/ 
@saraveg facciamo qualche prova?
