### ISSUE TITLE
UX/UI e Tema

### ISSUE THREAD

**Issue by favoeva** [emergenzeHack/covid19italia#180]

**Comment by olistik** [comment]
@favoeva aiutami con una descrizione. 🤓🙏

**Comment by iltempe** [comment]
C'è bisogno di rivedere tutta l'usabilità della piattaforma. Compreso forse il tema del sito. Abbiamo pagine e contenuti che non sappiamo dove mettere.

**Comment by avivace** [comment]
https://github.com/emergenzeHack/covid19italia/issues/159

**Comment by GinaBondi** [comment]
Buongiorno. Sito visto da fuori. Aggiungere al menu "AGGIORNAMENTI" 2 voci "SEGNALAZIONI", "INFORMAZIONI"?

**Comment by GinaBondi** [comment]
al momento, le imbocchiamo solo dalla home
"SEGNALAZIONI" --> "INIZIATIVE SOLIDALI"  
 "INFORMAZIONI" --> "FONTI ISTITUZIONALI"

**Comment by iltempe** [comment]
@GinaBondi mi dici esattamente come vorresti modificare la home?

**Comment by favoeva** [comment]
> @favoeva aiutami con una descrizione. 🤓🙏

Ci ha pensato @iltempe 🔝

**Comment by dontyna** [comment]
- form segnalazione su URL esterno: l'utente potrebbe pensare di essere su sito non sicuro o di aver sbagliato qualcosa (impossibile l'embed?)
- se da menù home clicco su "Iniziative solidali" le mette in ordine per ultima inserita, sarebbe possibile avere navigazione per città, oltre che la mappa (che quando si apre presenta tutto il mondo)? 
- sarebbe ideale che il menù raccolte fondi, ecc fosse sempre visibile, perché una volta cliccato su una tipologia poi devo tornare indietro per forza
- le categorie potrebbero avere una descrizione, per far comprendere esattamente cosa ci mettiamo dentro

In generale: così com'è è difficilmente navigabile, mentre è ottimo per far fluire nel notizie sul bollettino e su Twitter. Appena riesco metto reference per ispirarci.

**Comment by mfortini** [comment]
Le richieste di @dontyna sono fattibili, tranne l'embed della form che non sono così esperto

**Comment by favoeva** [comment]
> Le richieste di @dontyna sono fattibili, tranne l'embed della form che non sono così esperto

forse sull'embed può aiutarci @olistik

**Comment by cristigalas** [comment]
Concordo con tutte le proposte di @dontyna. 
Tra l’altro, anche a me qualcuno ha segnalato che il form su url esterno genera diffidenza e non invoglia a segnalare...

**Comment by olistik** [comment]
Mi ci sono potuto dedicare solo poco fa.
Forse l'embed si può fare:

```
<iframe src=https://ee.humanitarianresponse.info/i/::ID_DEL_FORM_QUI width="800" height="600"></iframe>
```

Quindi tipo:

```
<iframe src=https://ee.humanitarianresponse.info/i/::aozLp5mz width="800" height="600"></iframe>
```

Ora lo provo.

**Comment by iltempe** [comment]
sul secondo punto di @dontyna secondo me potrebbe essere di aiuto una 
ricerca COMPLESSIVA (di tutte le categorie) per luogo. Intendo dire una pagina che ti chiede "Dove Sei?" e ti prospetta tutto ciò che è attorno a te nel raggio di un certo chilometraggio.

**Comment by cristigalas** [comment]
> sul secondo punto di @dontyna secondo me potrebbe essere di aiuto una
> ricerca COMPLESSIVA (di tutte le categorie) per luogo. Intendo dire una pagina che ti chiede "Dove Sei?" e ti prospetta tutto ciò che è attorno a te nel raggio di un certo chilometraggio.

Wow! Questo sarebbe davvero bello e utile!

**Comment by dontyna** [comment]
@iltempe sì, ma teniamo conto degli italiani all'estero (la richiesta mi è stata fatta da una persona fuori paese).

**Comment by olistik** [comment]
L'embed degli iframe è fattibile ma con qualche considerazione.
Ho aperto #196 dove continuerei la discussione su questo punto.

**Comment by Albertopi78** [comment]
Ho alcune proposte sull'UX. 

Per farle ho usato un metodo empirico, anche se in misura ridotta, purtroppo. Ho testato il sito con un paio di persone che vivono con me (le ho guardate navigare senza dir nulla, poi ho fatto domande) e con un paio di persone a distanza (un po' meno affidabile ma va be'). So che il campione non è sufficiente, ma da qualche parte tocca partire. Spero di riuscire a metterla giù in maniera comprensibile.

**LA HOME**

La prima cosa che mi è stata segnalata è che una volta scoperta la pagina "issue" con la mappa è tutto molto più chiaro e le persone che navigano si illuminano letteralmente.
Forse va solo integrata la pagina "issue" in home? 

La seconda cosa: "Iniziative solidali" nel pulsante in home risulta poco comprensibile come dicitura. Nessuna delle persone con cui ho testato si aspettava di atterrare sulla pagina dove ci sono tutte le segnalazioni.

Infine, in home metterei un rimando a una pagina (da creare) che contenga 
- tutti i numeri telefonici d'emergenza
- tutti i numeri verdi di sostegno
- tutti i link ufficiali

**MENU**

Qui provo a proporvi una logica di pulsanti-call to action e minima riorganizzazione, cercando di mantenere al minimo i secondi livelli

- SEGNALA --> Pagina per segnalare https://www.covid19italia.info/segnala/
- SCOPRI --> Pagina delle segnalazioni https://www.covid19italia.info/issues/
- SEGUI --> 
--> CONTATTI --> Pagina Canali https://www.covid19italia.info/canali/
--> NEWS --> Pagina News https://www.covid19italia.info/news/
--> BLOG (però se lo teniamo va popolato) https://www.covid19italia.info/post/
- COS'È? -->
                 --> DOMANDE E RISPOSTE --> Pagina FAQ (da creare)
--> OPENDATA --> Pagina Opendata https://www.covid19italia.info/opendata/
--> RASSEGNA STAMPA --> Pagina Press https://www.covid19italia.info/press/
- PARTECIPA! --> Pagina per collaborare (sistemare testi) https://www.covid19italia.help/2020-03-10-sei-uno-sviluppatore-se-vuoi-aiutaci/
- PRIVACY --> Pagina Legal https://covid19italia.help/legal/

** FOOTER **
Anche per favorire il posizionamento SEO sul lungo periodo, propongo una di aggiungere descrizione breve con un paio di parole "chiave", ripresa direttamente dal comunicato stampa. Scriverei così (preso dal CS):

Progetto non profit coordinato da civic hacker (attivisti e attiviste digitali) per mettere insieme in modo coordinato informazioni utili sull'epidemia e sull’emergenza da coronavirus in Italia nel 2020. Aggreghiamo, verifichiamo e diffondiamo notizie, informazioni utili, iniziative solidali, raccolte fondi e molto altro.

**Comment by GinaBondi** [comment]
> al momento, le imbocchiamo solo dalla home
> "SEGNALAZIONI" --> "INIZIATIVE SOLIDALI"
> "INFORMAZIONI" --> "FONTI ISTITUZIONALI"

> @GinaBondi mi dici esattamente come vorresti modificare la home?

mi piacerebbe, mentre mi sposto tra le pagine conservare la possibilità di accedere ad ognuno dei 5 flussi:

|INIZIATIVE SOLIDALI || RACCOLTE FONDI || FONTI ISTITUZIONALI || RICHIESTE DI AIUTO || FAKE NEWS |

non é indispensabile. Vedo che il secondo elemento del menù è già stato modificato. Com'è ora mi piace anche di più.

Forse, se é fattibile, sarebbe d'aiuto ritrovarle nelle altre pagine, senza sacrificare la nitidezza della home.

Post lunghetto! Scusate. Manca ancora una cosa: una grande GRAZIE di <3 a tutti.

**Comment by iltempe** [comment]
per ora ho aggiornato il menu come indicato da @Albertopi78 . se riuscite a darmi indicazioni su cosa altro volete cambiare "pezzettino per pezzettino" anche con issue molto semplici lo faccio.

**Comment by favoeva** [comment]
> Progetto non profit coordinato da civic hacker (attivisti e attiviste digitali) per mettere insieme in modo coordinato informazioni utili sull'epidemia e sull’emergenza da coronavirus in Italia nel 2020. Aggreghiamo, verifichiamo e diffondiamo notizie, informazioni utili, iniziative solidali, raccolte fondi e molto altro.

mi torna tutto 

solo sostituirei 'mettere insieme' con 'raccogliere'  e aggiungerei dopo coronavirus  (covid19)

**Comment by Pinzauti** [comment]
Credo sarebbe importante ri-discutere questa issue, ora che il tutto più o meno funziona va data una svecchiata all'interfaccia imho.

**Comment by iltempe** [comment]
sono d'accordo con @Pinzauti . chiudo questa e riapriamo issue mirata per eventuali modifiche da proporre. grazie.
