### ISSUE TITLE
Icona Post su Twitter

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#181]
**Priorità**: bassa

## Richiesta
I post su twitter non hanno il logo del nostro sito https://twitter.com/ItaliaCovid19/status/1239177068526612481?s=20

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by olistik** [comment]
@iltempe 

https://cards-dev.twitter.com/validator

https://www.covid19italia.help/issues/530/

<img width="458" alt="Screenshot 2020-03-16 at 11 53 50" src="https://user-images.githubusercontent.com/21038/76749454-d8da1d00-677c-11ea-9817-c49431e10589.png">

**Comment by avivace** [comment]
Grazie @olistik , mi sembra funzionare!
