### ISSUE TITLE
Guida introduttiva per gruppo media e comunicazione

### ISSUE THREAD

**Issue by Albertopi78** [emergenzeHack/covid19italia#182]
Con le "nuove leve" del gruppo media e comunicazione, abbiamo pensato di realizzare un testo introduttivo per chi vuole collaborare, non ha competenze di sviluppo e ha una sincope se vede un link github :)

Il risultato provvisorio è un documento di mediazione culturale che trovate qua
https://docs.google.com/document/d/1EFUzBaqQkDBmbcmZbtozG_LufBlnSCcS3tZhiw6rqiU/edit#

A disposizione per metterlo sul wiki e tenerlo aggiornato.

**Comment by avivace** [comment]
Fantastico

**Comment by cristigalas** [comment]
@iltempe si può chiudere.
