### ISSUE TITLE
Pubblicazione automatica WIKI -> Sito

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#185]
**Priorità**: bassa

## Richiesta
Chi sa come aggiornare una pagina del sito (che possiamo chiamare come vogliamo) dal WIKI del repo Github?

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by avivace** [comment]
Me ne posso occupare io, quali pagine della **wiki** vogliamo iniziare a pubblicare sul sito?

**Comment by iltempe** [comment]
@Albertopi78 tutte?

**Comment by avivace** [comment]
Le FAQ adesso dove stanno?

**Comment by iltempe** [comment]
le FAQ sono sul google doc se ricordo bene

**Comment by avivace** [comment]
Trovate ;)

**Comment by avivace** [comment]
Ci siamo! https://www.covid19italia.info/wiki/
