### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by jeeltuss** [emergenzeHack/covid19italia#186]
Ciao,

sono Giuseppe, lavoro come sviluppatore in una web agency. 
Lavoro principalmente su stack LAMP, basi di python, basi di framework js. 
Bazzico abbastanza sql e gestione di db, più alla bisogna faccio un po' da sysadmin in azienda. 
Di git(hub) ho nozioni basilari, ma mi manca la dimestichezza col lavoro in team. 
Se posso aiutare, il mio telegram è questo

@jeeltuss

Un saluto

**Comment by avivace** [comment]
Ciao @jeeltuss  ! Ti ho aggiunto al gruppo Telegram degli sviluppatori e tecnici che stanno lavorando al progetto. Nel frattempo, guardati attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare faccelo sapere :)
