### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by meesta1990** [emergenzeHack/covid19italia#187]
Ciao,
mi piacerebbe contribuire. Sono un programmatore Javascript, ReactJS con esperienza backend Java e Oracle. 
Ho visto che potrei fare qualche task, tra cui sicuramente https://github.com/emergenzeHack/covid19italia/issues/167

Mio telegram:
meestah

**Comment by avivace** [comment]
Ciao @meesta1990  ! Ti ho aggiunto al gruppo Telegram degli sviluppatori e tecnici che stanno lavorando al progetto. Nel frattempo, guardati attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare faccelo sapere :)
