### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by fedestyla** [emergenzeHack/covid19italia#188]
Salve,

Sono uno sviluppatore Android con qualche conoscenza di Web (React, Angular). Se posso aiutare in qualche modo, fatemi sapere. Telegram: @Fedestylah

**Comment by avivace** [comment]
Ciao @fedestyla  ! Ti ho aggiunto al gruppo Telegram degli sviluppatori e tecnici che stanno lavorando al progetto. Nel frattempo, guardati attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare faccelo sapere :)
