### ISSUE TITLE
Gemfile.lock untracked

### ISSUE THREAD

**Issue by olistik** [emergenzeHack/covid19italia#19]
@mfortini

Ho fatto il `bundle install` locale e `Gemfile.lock` risulta _untracked_.

C'è qualche motivo particolare o posso committarlo?

**Comment by drizzt** [comment]
L'ho rimosso (che qualcuno l'ha pushato per sbaglio) e messo in .gitignore, quindi si può chiudere

**Comment by olistik** [comment]
@drizzt Momento. 😅  

![tenor](https://user-images.githubusercontent.com/21038/76745641-83027680-6776-11ea-9bcb-0d882e19f0ad.gif)

Perché rimuoverlo?
Ci sono solo ottimi motivi per tenerlo. 😅

**Comment by drizzt** [comment]
Se lo metti creato con bundler 2 non funzionerà più con bundler 1 (che è il
default su Ubuntu Lys)

Il lun 16 mar 2020, 11:09 olistik <notifications@github.com> ha scritto:
