### ISSUE TITLE
Spiegare da qualche parte come usare i nostri dati per una citazione

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#190]
**Priorità**: bassa

## Richiesta
Potrebbe essere utile evidenziare i feed rss fatti qui #114 e forse aggiungere nella pagina opendata chi usa i nostri dati?

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by iltempe** [comment]
intanto ho aggiunto i link ai feed rss

**Comment by avivace** [comment]
Qui sicuramente andrebbe nella pagina OpenData, magari un pezzo di codice HTML da poter copia incollare che dice "Fonti covid19italia.help"

**Comment by iltempe** [comment]
è stato fatto nella pagina opendata
