### ISSUE TITLE
[richiesta di iscrizione]

### ISSUE THREAD

**Issue by albygio81** [emergenzeHack/covid19italia#192]
Salve a tutti,
sono un avvocato di Torino.

Non so se possa essere in qualche modo utile, ma se dovesse essere fatemi sapere.

Grazie.
Alberto

telegram:@duke176

**Comment by avivace** [comment]
Ciao @albygio81  ! Ti ho aggiunto al gruppo Telegram degli sviluppatori e tecnici che stanno lavorando al progetto. Nel frattempo, guardati attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare faccelo sapere :)
