### ISSUE TITLE
Tracking personale

### ISSUE THREAD

**Issue by albygio81** [emergenzeHack/covid19italia#193]
Sono nuovo del gruppo e leggendo questo articolo [https://www.lastampa.it/cronaca/2020/03/14/news/economisti-matematici-e-informatici-la-chiusura-totale-non-basta-servono-anche-tracciamenti-mirato-e-modello-corea-del-sud-1.38591873](https://www.lastampa.it/cronaca/2020/03/14/news/economisti-matematici-e-informatici-la-chiusura-totale-non-basta-servono-anche-tracciamenti-mirato-e-modello-corea-del-sud-1.38591873) mi sono chiesto se non sia possibile sviluppare, sul sito, una sezione database dove gli eventuali iscritti possano auto-dichiarare l'area dove si trovino (sulla precisione della segnalazione si può valutare sul piano giuridico le implicazioni possibili), il proprio stato di salute (qualora abbiano una sintomatologia possibilmente riconducibile al Covid-19) ed eventualmente i soggetti con i quali si sia entrati in contatto.

Il tutto potrebbe comparire, ad uso degli utenti, in modo generico (ad esempio segnalare solo la macro area dove l'iscritto si sia localizzato e la gravità della segnalazione), mentre, su richiesta delle Autorità potrebbe accedersi alle informazioni personali.

Forse è uno sviluppo mastodontico da implementare, ma visto il contenuto dell'articolo mi sarebbe sembrato un crimine non segnalarlo e potrebbe costituire una spinta per lo Stato a muoversi in questo senso. 
Ribadisco che se può interessare, e può essere fattibile, posso mettermi a studiare le modalità con cui potrebbe operare il sito, in particolare in punto tutela della privacy degli utenti e data sharing con le Autorità.

Se è non fattibile, esagerato, ridicolo, vi prego di scusarmi e non tenere conto del post.
Grazie.

**Comment by iltempe** [comment]
Ciao @albygio81 e grazie del tuo intervento. In Cina pare che il governo abbia fatto crowsourcing fornendo una APP per fare ciò che dici. Noi col nostro progetto abbiamo scelto di fare un qualcosa di un po' diverso. Lo scopo non è intromettersi nella comunicazione PAZIENTE - UNITA' SANITARIA (che invitiamo a fare con i canali istituzionali) quanto piuttosto fornire un supporto ai cittadini per far conoscere ciò che hanno attorno in un momento di così tanta difficoltà. Facciamo quindi crowdsourcing di questo non dei casi o dei contagi. Spero di aver chiarito. a presto.

**Comment by albygio81** [comment]
Grazie della risposta, pur essendomi abbastanza chiaro l'intento del sito, i chiarimenti sono sempre utili.
Quanto al mio commento, ci tenevo solo a riportare quanto mi pareva interessante in ordine ai possibili sviluppi del progetto, visti gli esiti che nel sud est asiatico aveva avuto un approccio di questo genere.

Grazie.

**Comment by iltempe** [comment]
@albygio81 certo, ma non escludo che qualcuno in europa ci stia lavorando eh. dico solo che non è esattamente nel nostro scopo. continua però a darci un contributo su altri issue ci serve una mano! grazie
