### ISSUE TITLE
Creazione dataset con dati regionali sulle terapie intensive

### ISSUE THREAD

**Issue by gianlab** [emergenzeHack/covid19italia#195]
**Priorità**: media

## Testo della comunicazione

**Tipo di richiesta**: richiesta di dati 

## Riassunto

Ciao,
finora ho fatto i seguenti reports con i dati delle Protezione Civile:
https://www.kaggle.com/gianlab/previsioni-ed-esplorazione-dati-covid-19-italia
https://www.kaggle.com/gianlab/esplorazione-dei-dati-province-italiane-covid-19

Ora mi vorrei occupare della terapia intensiva per ogni regione italiana... In questo momento si può calcolare la percentuale delle terapie intensive rispetto ai casi confermati della regione , ma bisognerebbe sapere i posti disponibil in terapia intensiva complessivi e per il covid19 per ogni regione. Si potrebbe creare un dataset che abbia i seguenti campi :
data,regione, posti totali in terapia intensiva, posti disponibili per il covid, link alla notizia giornalistica . 

## Interesse pubblico

Avendo questi dati si potrebbe calcolare la soglia regionale di casi confermati nella regione che non dovrebbe essere superata facendo una proporzione. In pratica se ci sono 50 posti in terapia intensiva disponibili in Puglia per il Covid19 e l'8% è la percentuale di casi confermati in terapia intensiva in Puglia la soglia regionale è 5000/8=625 cioè il numero di casi confermati che non deve essere superato .

Si potrebbe realizzare questo datasets a cui tutti potrebbero contribuire?
Si tratta in pratica di cercare le notizie giornalistiche e aggiornare il dataset.
Grazie

**Comment by bertanimauro** [comment]
Eccoli.
Uno è il dato dei posti letti a lunga decorrenza in numero, l'altro è per
100000 abitanti. Dati eurostat.



  Eurostat - Data Explorer3
<https://drive.google.com/file/d/1sVvnRDwGZX0mvUwAIHoZxxgrXp_grKQZ/view?usp=drivesdk>

  Eurostat - Data Explorer5
<https://drive.google.com/file/d/1sZBJSZkXtva4vUeaJH8UESouXl3tDcku/view?usp=drivesdk>


Il lun 16 mar 2020, 06:07 gianlab <notifications@github.com> ha scritto:

**Comment by iltempe** [comment]
posso chiuderlo?

**Comment by gianlab** [comment]
Io per ora chiudo con le previsioni perchè secondo me portano sfiga, infatti  ho cancellato quelle fatte con ARIMA e non ho pubblicato quella con la regressione polinomiale di grado 3 che funziona discretamente . Ho lasciato per ora soltanto le previsioni per la terapia intensiva qui : https://www.kaggle.com/gianlab/previsioni-sulla-terapia-intensiva-in-italia ma forse le cancello . Appena vedo un qualche miglioramento ricomincio a pubblicare . Ciao
