### ISSUE TITLE
Form embedded

### ISSUE THREAD

**Issue by olistik** [emergenzeHack/covid19italia#196]
**Priorità**: media

## Richiesta

I form usati per le segnalazioni vengono aperti in una pagina esterna e questo può generare confusione e timori da parte degli utenti.

Una soluzione a questo problema è l'_embedding_ dei form all'interno delle nostre pagine tramite l'uso di _iframe_.

Esempio:

<img width="445" alt="Screenshot 2020-03-16 at 07 42 18" src="https://user-images.githubusercontent.com/21038/76729623-d914f100-6759-11ea-8c00-a2177277a8fc.png">

Questa issue risolve uno dei punti sollevati nella epic #180 .

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by olistik** [comment]
Menziono @dontyna e @cristigalas dato che potreste avere qualche parere "caldo" sull'argomento ma chiunque può ovviamente intervenire. 🙂 

Nella pagina [Segnala](https://www.covid19italia.info/segnala/) abbiamo 8 form.

Per ognuna di queste possiamo creare una pagina, **interna al sito**, in cui effettuiamo l'_embed_ del corrispondente form.

Qui un risultato grezzo a cui sono arrivato.

## Desktop

<img width="1353" alt="Screenshot 2020-03-16 at 07 42 00" src="https://user-images.githubusercontent.com/21038/76730023-a7e8f080-675a-11ea-9f1b-71c586c0c622.png">

![recording--desktop](https://user-images.githubusercontent.com/21038/76732778-c3a2c580-675f-11ea-824b-857cc62aab84.gif)


## Mobile

<img width="445" alt="Screenshot 2020-03-16 at 07 42 18" src="https://user-images.githubusercontent.com/21038/76730035-b2a38580-675a-11ea-9cca-1d348d56d521.png">

![recording](https://user-images.githubusercontent.com/21038/76732790-c998a680-675f-11ea-982c-0f41eeb32a56.gif)

## Considerazioni

Si possono notare alcuni problemi:

1. Lo scrolling attivo nella mappa rende la navigazione della pagina un problema. Sarebbe da disabilitare e permettere lo zoom solo con controlli interni alla mappa. Possiamo creare una issue specifica a riguardo.
2. È presente una barra di scorrimento laterale **aggiuntiva** rispetto a quella del browser. Crea un po' di confusione tra i due contesti presenti in pagina (la pagina e il form).

È impossibile rimuovere la barra di scorrimento. Le opzioni che vedo sono quindi:

1. Usiamo l'embed con barra di scorrimento. Veloce da implementare ma con il problema di usabilità di sopra.
2. Creiamo le form in pagina e spediamo i risultati via API ad un server che le processa e le converte in issue GitHub. Impieghiamo un po' di più ma l'integrazione è perfetta.

@mfortini @iltempe @avivace @favoeva (solo per taggarne alcuni) & all, fatemi sapere che ne pensate. 🙇

**Comment by avivace** [comment]
Grazie @olistik per l'attenta analisi, purtroppo ci avevamo già riflettutto e su mobile non è fattibile la cosa.

> Creiamo le form in pagina e spediamo i risultati via API ad un server che le processa e le converte in issue GitHub. Impieghiamo un po' di più ma l'integrazione è perfetta.

Questo in realtà è quello che già facciamo! Solo che invece di essere hostati sul nostro sito in Jekyll, sono hostati su KoboToolbox. In previsione di questo scenario, abbiamo scelto KoboToolbox/Enketo/i form nello standard proprio perchè sono facili da self hostare e sono scritti in uno standard consumabile da tante librerie.

A questo punto, bisogna capire come, a partire dalle definizioni dei form, generare del'HTML da iniettare in /segnala/

**Comment by cristigalas** [comment]
Grazie per analisi e spiegazioni. Da profana, mi e vi chiedo, ma usare una form tipo quella di Tci? Funzionava benissimo. Scusate se ho detto una cosa sciocca...

**Comment by olistik** [comment]
@avivace 

> [..] su mobile non è fattibile la cosa.

Giusto per evitare di incappare nella stessa domanda in futuro, per quali motivi non è fattibile?

> Questo in realtà è quello che già facciamo! Solo che invece di essere hostati sul nostro sito in Jekyll, sono hostati su KoboToolbox.

Il comportamento attuale è diverso da ciò che ho proposto.

Per evitare i problemi menzionati bisogna comunque effettuare il rendering dei form sul nostro sito (HTML, CSS e JS) delegando principalmente il salvataggio dei risultati ad un servizio esterno.

> A questo punto, bisogna capire come, a partire dalle definizioni dei form, generare del'HTML da iniettare in /segnala/

Che è uno dei modi possibili.

Aiutami a comprendere meglio questa parte.

KoboToolbox è utile per vari motivi:

1. hosting dell'inventario dei form
2. composizione dei form e creazione delle logiche di validazione
3. salvataggio dei dati compilati
4. interfacciamento tramite API. Nel nostro caso per la creazione di issue GitHub

I form sono 8, quindi non stiamo parlando di numeri alti.

Un API server che riceve i dati e crea al volo la issue GitHub si tira su in poco tempo su hosting esterno e gratuito (ad esempio Heroku).

Rimarrebbe da creare il codice HTML, CSS e JS che effettua il rendering delle 8 form e spedisce il risultato all'API server.

Ipotizzando di volerci separare dei form su pagina esterna, **se** KoboToolbox ci permette di essere usato solo per i punti 3. e 4. allora bene, resta comunque da implementare HTML, CSS e JS.

Suggerisco che se questa integrazione richiede molto tempo (ho avuto un po' di difficoltà a recuperare la documentazione ma qui sono io inesperto sul prodotto), allora forse possiamo valutare di creare in poco tempo l'API server.

**Comment by olistik** [comment]
> Grazie per analisi e spiegazioni. Da profana, mi e vi chiedo, ma usare una form tipo quella di Tci? Funzionava benissimo. Scusate se ho detto una cosa sciocca...

@cristigalas Effettivamente è una soluzione "compromesso" che potrebbe anche avere senso.

Anche in TCI effettuiamo l'_embed_ di una form ospitata su un sito esterno. Era un'applicazione creata ad-hoc per TCI e ospitata su Heroku ma in questo caso potremmo usare KoboToolbox.

Il trucco usato sul form di segnalazione di TCI è che viene impostata l'altezza dell'_iframe_ che include il form esterno con un valore molto alto:

```
<iframe src="https://terremotocentroitalia.herokuapp.com/segnalazioni/" width="100%" height="1700rem" frameborder="0"> <a href="https://terremotocentroitalia.herokuapp.com/segnalazioni/">Segnalazioni terremoto</a></iframe>
```

`1700rem` in questo caso.

L'effetto positivo è che ogni form non arriverà mai a questa altezza e quindi l'utente non vedrà un'ulteriore barra di scorrimento verticale.

L'effetto negativo è che in fondo alla pagina è presente tanto spazio bianco:

![recording](https://user-images.githubusercontent.com/21038/76744743-058a3680-6775-11ea-9341-a277b77ee7be.gif)

È una soluzione veloce e potremmo implementarla in attesa di una migliore integrazione, che ne dite?

**Comment by avivace** [comment]
@olistik se l'unico effetto negativo è lo spazio bianco direi che va bene

**Comment by olistik** [comment]
Un altro effetto carino che avremmo ora è che possiamo condividere le singole pagine delle segnalazioni. 🙂 

```
/segnala/chiedi-aiuto
/segnala/dona-beni-servizi
/segnala/iniziative-servizi
/segnala/raccolta-fondi
/segnala/contatto-utile
/segnala/bufala
/segnala/documenti-dati
/segnala/notizia
```
