### ISSUE TITLE
Nella web form il campo mail non accetta certe tipologie di indirizzi

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#205]
Nella web form il campo email non prende alcuni tipi di indirizzi, tipo questo: sabrina.manzi@lombardia.cri.it ma anche altri ad es. di Regioni, Comuni, ecc.
Ciò accade in particolare in Chiedi Aiuto ma credo accada anche in altre form.

**Comment by Jolsty** [comment]
Ciao @cristigalas 

Ho aggiornato i form, adesso non dovrebbero più dar quelli errori per mail valide.
Se ci sono altri problemi fai pure sapere, grazie!

**Comment by cristigalas** [comment]
> Ciao @cristigalas
> 
> Ho aggiornato i form, adesso non dovrebbero più dare errori per mail valide.
> Se ci sono altri problemi fai pure sapere, grazie!

Grazieee!

**Comment by avivace** [comment]
Grazie @Jolsty :rocket:
