### ISSUE TITLE
Verifiche javascript

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#207]
Molte pagine contengono javascript che sono stati creati "per funzionare".
Verificare e se possibile ottimizzare per migliorare l'esperienza utente.

Per esempio quelli in queste pagine:
https://github.com/emergenzeHack/covid19italia/tree/master/_layouts

O in generale, tutti gli script e i css inclusi, che potrebbero essere obsoleti.

**Comment by luciaarsena** [comment]
Sono finalmente riuscita a installare in locale (avevo un problema con libcurl.dll). Cosa c'è da fare su questo punto? Eliminare gli script inutili?

**Comment by iltempe** [comment]
@luciaarsena a livello JS quello che vuoi per migliorare l'attuale codice. Se pensi sia meglio anche riorganizzare con script esterni da gestire come librerie si può fare. fai la tua pull request e dicci cosa modifichi almeno verifichiamo.

**Comment by iltempe** [comment]
chiudo. è generico.
