### ISSUE TITLE
[Voci menu] Compare ancora dicitura "segnalazioni terremoto"

### ISSUE THREAD

**Issue by ali-ce** [emergenzeHack/covid19italia#21]
<img width="203" alt="Screenshot 2020-03-09 at 11 58 58" src="https://user-images.githubusercontent.com/7140368/76207089-7376b100-61fd-11ea-993f-bd3afde188c6.png">

**Comment by iltempe** [comment]
@ali-ce ho rimosso quella dicitura che segnalavi. Credo che tutti i menu andranno rifatti a valle della #6

**Comment by iltempe** [comment]
chiudo è a posto.
