### ISSUE TITLE
Sezione BLOG

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/covid19italia#210]
@iltempe @mfortini Segnalo che sulla piattaforma nella sezione “Blog” sull’uso dei social in modo utile appaiono riferimenti legati al terremoto (alloggi, donazioni e richiesta).

**Comment by iltempe** [comment]
@chiccap si...quel post forse te lo ricordi... ;-) l'ho lasciato al momento così si può cambiare quando abbiamo un testo alternativo, o anche qualche frase da cambiare, lo trovo utile per chi volesse ricondividere informazioni dal sito.

**Comment by chiccap** [comment]
> @chiccap si...quel post forse te lo ricordi... ;-) l'ho lasciato al momento così si può cambiare quando abbiamo un testo alternativo, o anche qualche frase da cambiare, lo trovo utile per chi volesse ricondividere informazioni dal sito.

Sì sì me lo ricordo bene :) io lo terrei andrei solo a modificare le parti con i rimandi a TCI, posso farlo io...non mi ricordo come si fa...!

**Comment by iltempe** [comment]
E' tutto molto semplice....te lo dice il wiki di TCI!! ;-) https://github.com/emergenzeHack/terremotocentro/wiki/009-Creare-un-post-da-inserire-nel-sito ora lo metto anche nel nostro wiki.

**Comment by Albertopi78** [comment]
@iltempe anche per i post sul blog vale il fatto che si può scrivere sul drive e poi usare l'add-on di conversione in .md?

**Comment by iltempe** [comment]
@Albertopi78 si certo. l'addon lo puoi usare sempre per scrivere il documento normalmente e poi avere il Markdown direttamente da incollare.

**Comment by iltempe** [comment]
ho reso generico il post. chiudo.
