### ISSUE TITLE
Rimuovere lista delle segnalazioni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#214]
**Priorità**: alta

## Richiesta
DIrei di lasciare in questa pagina https://www.covid19italia.help/issues/ solo la mappa e i pulsanti delle categorie e rimuovere la lista infinita delle segnalazioni. 

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by cristigalas** [comment]
@iltempe io le lascerei, semmai solo fino ad un certo punto perché danno subito l’idea di come sono strutturate le segnalazioni... 

Tuttavia, secondo me, il problema di [questa pagina](https://www.covid19italia.help/issues/) è un altro: il titolo della pagina è “Iniziative solidali”, ma in realtà qui ci sono praticamente tutte le segnalazioni e tra i bottoni verdi c’è di nuovo [Iniziative e servizi solidali](https://www.covid19italia.help/servizi-e-iniziative-solidali) che però raccoglie solo le iniziative/servizi pubblici. Quindi qualcosa non torna. 

Ho fatto un’analisi delle label e ho verificato che tutte le iniziative solidali pubbliche hanno almeno un’altra label (consegna a domicilio, news e info utili, supporto psicologico, ecc.), quindi non ha senso riproporle con questo bottone. 

Suggerirei allora di togliere il bottone verde Iniziative e servizi solidali e inserire al suo posto “Notizie e info utili” (label Notizie + Informazioni Utili), perché queste compaiono solo in alto e, invece, cominciano ad essere numerose e meritano, a mio avviso, più visibilità.  

Infine chiamerei questa pagina semplicemente “Segnalazioni“ o “Tutte le segnalazioni” e in home page, visto che ci sono le raccolte fondi, aggiungerei anche consegne a domicilio e supporto psicologico che mi sembrano quelle più numerose e ricercate. In home aggiungerei anche le Notizie ma forse si affolla troppo? Però credo sia utile avere accesso fin dalla home alle segnalazioni più ‘consistenti’ e utili.

Ora mi taccio e vorrei sapere cosa ne pensano anche gli altri... @Saraveg @favoeva @mfortini @chiccap @Albertopi78 

Perdonate la lungaggine... volevo spiegarmi bene :) Ma forse dovevo aprire una nuova issue? 😱

**Comment by chiccap** [comment]
Non so perchè ancora mi stupisco della capacità di analisi e precisione di @cristigalas essendo così evidente! Io sono d'accordo su tutto, non so se per le modifiche proposte dobbiamo aprire issue ma sicuramente al momento terrei lista segnalazioni (per le persone meno smart ecco...)

**Comment by cristigalas** [comment]
(@chiccap mi fai arrossire 😊) 

@iltempe apriamo nuova issue per queste proposte? O modifichiamo titolo di questa

**Comment by iltempe** [comment]
questa la chiudiamo. per favore apriamo issue puntuali sulle modifiche che secondo voi ha senso fare. grazie.

**Comment by cristigalas** [comment]
Ok, aperta #228
