### ISSUE TITLE
Form non visibili

### ISSUE THREAD

**Issue by gorobey** [emergenzeHack/covid19italia#216]
**Priorità**: alta

## Richiesta

I form ora inclusi via iframe non vengono caricati se è attivo un sistema di blocco degli annunci

## Come si riproduce il bug

ho verificato il problema con AdBlock Plus

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by drizzt** [comment]
Risolto cambiando iframe con object con fallback che fa redirect della pagina verso il form.

**Comment by amerlo94** [comment]
I forms non vengono visualizzati se vengono disabilitati i cookies tramite browser.

Per riprodurre:
Firefox -> Settings -> Enhanced Tracking Protection -> Cookies -> All third-party cookies
