### ISSUE TITLE
Aggiornare automaticamente la lista dei contributori

### ISSUE THREAD

**Issue by drizzt** [emergenzeHack/covid19italia#218]
Sarebbe carino che la lista dei contributori venga aggiornata automaticamente

**Comment by iltempe** [comment]
come si fa? dagli utenti github? utenti gruppo telegram? per iscrizione diretta?

**Comment by avivace** [comment]
Fatto! https://www.covid19italia.info/about/

Ognuno può gestire il proprio nome e immagine dal proprio profilo. Nel futuro possiamo mettere una breve descrizione e la possibilità di scegliere in che team comparire (se si è in più team)
