### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by GianlucaSolinas** [emergenzeHack/covid19italia#220]
Ciao a tutti,
mi piacerebbe contribuire (lavoro permettendo) a questo gran bel progetto! 
Il mio username Telegram e' GianlucaSolinas

Grazie!

**Comment by avivace** [comment]
Ciao @GianlucaSolinas ! Ti ho aggiunto al gruppo Telegram degli sviluppatori e tecnici che stanno lavorando al progetto. Nel frattempo, guardati attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare faccelo sapere :)
