### ISSUE TITLE
API Pubblica

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia#221]
**Priorità**: media

## Descrizione

Si avvicina il momento in cui dovremmo poter esporre il tutto con un API pubblica per sviluppatori:

- Backend dei form (aggiungere HTTPS, CAPTCHA/auth token)
- Open Data

**Comment by drizzt** [comment]
Gli Open Data ci sono già su github o intendi proprio delle api che espongano quelle API?

**Comment by iltempe** [comment]
io farei le API per creare segnalazioni. ad esempio su un'associazione avesse un servizio e volesse attivarsi per supportarci come deve fare? se avesse un BOT da usare?

**Comment by iltempe** [comment]
ho iniziato con una semplice GET qui https://github.com/emergenzeHack/covid19italia_api chi vuole può metterla su VPS o fare deploy. grazie.

**Comment by avivace** [comment]
Chiudo e spostiamo nelle issue allora
