### ISSUE TITLE
Attivare invio automatico notifiche commenti segnalazioni in gruppo Telegram

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#222]
Cominciano ad arrivare i commenti con Disqus in calce alle segnalazioni. Io ho intercettato questo per caso http://disq.us/p/27zbfw4
Possiamo attivare l’invio automatico delle notifiche nel gruppo Telegram Media o in quello di tutti i volontari, come facevamo per Tci? Altrimenti li perdiamo...

@chiccap @Saraveg @iltempe @mfortini @favoeva

**Comment by chiccap** [comment]
Sì è importante!

**Comment by favoeva** [comment]
sì iniziavo a chiedermelo anch'io come fare a non perderseli
per la notifica: direi meglio gruppo editor 
che dite?

**Comment by cristigalas** [comment]
@favoeva ah sì, hai ragione meglio gruppo Editor (quando ho aperto issue non c’era, siamo troppo veloci :)

**Comment by iltempe** [comment]
@aborruso che tu sappia Disqus ha un feed rss che potremmo aggiungere su IFTTT?

**Comment by aborruso** [comment]
@iltempe può darsi che sia questo https://covid19italia.disqus.com/latest.rss ??
Confermate

Dove dovrebbe essere girato?

**Comment by iltempe** [comment]
a me pare quello. attendiamo @cristigalas che confermi. l'idea sarebbe quello di inserire gli update di quel feed nel gruppo telegram così da avere notifica.

**Comment by cristigalas** [comment]
@aborruso @iltempe non so se il feed è quello, però se è quello deve inviare notifiche sul gruppo Telegram Editor, di cui però non trovo link :(

**Comment by cristigalas** [comment]
@aborruso ecco il link al gruppo Telegram Editor https://t.me/joinchat/DRpotBuFJlGpOejl41lUmw

**Comment by aborruso** [comment]
Cara @cristigalas dovrei avere attivato (dico dovrei perché sul gruppo non ho tutti i permessi, ma dovrebbe funzionare).
Ora lascio un commento test

**Comment by aborruso** [comment]
Fatto e testato

**Comment by cristigalas** [comment]
Grazie! Faccio un test per provarlo...
