### ISSUE TITLE
Elementi in mappa, ma non renderizzati come pagine

### ISSUE THREAD

**Issue by aborruso** [emergenzeHack/covid19italia#223]
Ciao,
questa [issue](https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/81) è visibile in mappa, ma non è renderizzata in HTML https://www.covid19italia.help/raccolte-fondi/81

![image](https://user-images.githubusercontent.com/30607/76881338-466b7380-6879-11ea-8fc2-e5a04b83aeaf.png)

**Priorità**: media

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by drizzt** [comment]
Io la vedo in mappa su https://www.covid19italia.help/issues/81/

**Comment by aborruso** [comment]
Ok, prima (non so perché) non era renderizzato in HTML, ma si vedeva il pallino su mappa.

Grazie

**Comment by aborruso** [comment]
mmm @drizzt fai questo percorso:

- vai su mappa raccolta fondi e zooma sulla Puglia https://www.covid19italia.help/raccolte-fondi/
- l'URL di quel pallino è https://www.covid19italia.help/raccolte-fondi/81

E questo non viene renderizzato

**Comment by aborruso** [comment]
@drizzt e penso che avvenga per tutte le sezioni con mappa. Come ad esempio questa https://www.covid19italia.help/sostegno-lavoro-e-imprese/

Ci sono i PATH da correggere/modificare
