### ISSUE TITLE
Sulla mappa i link alle consegne a domicilio di Roma e Ciampino non funzionano

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#225]
![D33CA916-9FD4-49EE-874F-751E2F935C47](https://user-images.githubusercontent.com/21283775/76891284-044a2e00-6889-11ea-9510-c58165cd2b2f.png)

Vedi:
https://www.covid19italia.help/consegne-e-commissioni/372
https://www.covid19italia.help/consegne-e-commissioni/135
https://www.covid19italia.help/consegne-e-commissioni/433
https://www.covid19italia.help/consegne-e-commissioni/231
https://www.covid19italia.help/consegne-e-commissioni/239

Ma può darsi anche altre, non ho controllato...

**Comment by aborruso** [comment]
Chiudo questa, che è duplicara della precedente https://github.com/emergenzeHack/covid19italia/issues/223

**Comment by cristigalas** [comment]
@aborruso Ah ecco.. Avevo il dubbio che parlassimo della stessa cosa ma non capivo ‘renderizzati’, ora ho capito :)
