### ISSUE TITLE
Prevedere una versione inglese di covid19italia

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#227]
**Priorità**: bassa

## Richiesta
Se è vero che potrebbe essere un modello esportabile all'estero (come mi è stato fatto notare) forse vale la pena ragionarci.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by avivace** [comment]
D'accordo. Le prime cose che tradurrei sarebbero la documentazione tecnica e non, in modo tale che chiunque - indipendentemente dalla lingua o specifica regione - possa mettere su un'infrastruttura analoga alla nostra con propri nomi sfruttando tutto il nostro lavoro ed eventualmente procedendo con sviluppo proprio

**Comment by chiccap** [comment]
@avivace @iltempe ho delle amiche traduttrici possono dare una mano? Decidiamo una lista di pagina da tradurre e le coinvolgo!

**Comment by dontyna** [comment]
Segnalo piattaforma https://crowdin.com che abbiamo usato come Ondata e può servire a questo scopo, @aborruso può dirvi di più :)

**Comment by aborruso** [comment]
Grazie @dontyna .

Sì è un prodotto fra l'altro che si integra con [github](https://support.crowdin.com/github-integration/).
Abbiamo a disposizione in piano "open source" e possiamo abilitare un progetto dedicato a questo spazio.

**Comment by iltempe** [comment]
Grazie @aborruso @dontyna per me si può fare anche in vista delle richieste che ci stanno arrivando per questo #243

**Comment by Saraveg** [comment]
Noi potremmo metterci gente sulla traduzione "umana". ma non prima settimana prossima. non conosco il prodotto crowdin...(scusate l'ignoranza)

**Comment by Annalisa789** [comment]
ciao Io sono disponibile per le traduzioni

**Comment by iltempe** [comment]
segnalo anche questo #243 . se ho capito bene per domani @Saraveg ci da il WIKI tradotto.

**Comment by aborruso** [comment]
Ho fatto richiesta di abilitazione progetto su crowdin (va fatta a progetto).

Non appena abilitato inserisco l'account gmail di progetto come admin.

Saluti

**Comment by aborruso** [comment]
Ciao @iltempe ho attivato su crowdin un progetto covid19italia, dando accesso da manager all'account gmail, con la stessa password.

È integrabile in termini git https://support.crowdin.com/github-integration/

Questo è il progetto https://crowdin.com/project/covid19italiahelp
