### ISSUE TITLE
Landing page informativa

### ISSUE THREAD

**Issue by gbonfiglio** [emergenzeHack/covid19italia#23]
In Italia manca una semplice landing page informativa sul COVID-19.

Esempio UK: https://www.nhs.uk/conditions/coronavirus-covid-19/

Le info su http://www.salute.gov.it/nuovocoronavirus ci sono ma sono sparse e difficilmente accessibili.

Suggerisco di trovare un dominio carino e pubblicare traducendo la fonte NHS UK (ci servirebbe un medico per validare la traduzione).

**Comment by tailot** [comment]
Ciao non mi convince molto creare un ennessimo dominio (un po dispersivo), includerei queste informazioni direttamente nel progetto covid19italia per fare convergere i dati in un unico "punto" piuttosto che disperdere.

**Comment by iltempe** [comment]
ne abbiamo discusso in #167 e in #379 . al momento qui non facciamo dashboarding di dati sul COVID19, al limite dei nostri se lo vogliamo fare. Direi di chiudere fino a che non nasce nuova esigenza sul tema.
