### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by etcware** [emergenzeHack/covid19italia#232]
Salve sono Alessandra Donnini, sviluppatore. Un saluto.

**Comment by avivace** [comment]
Ciao @etcware ! Se vuoi essere aggiunta ai gruppi telegram dovresti scrivere l'username! Nel frattempo, guardati attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare faccelo sapere :)

**Comment by etcware** [comment]
Ciao dove lo devo mettere l’username Telegram? In ogni caso è 
@twalendo

**Comment by avivace** [comment]
Va benissimo qui, ti ho aggiunto!
