### ISSUE TITLE
Avvisare quando una lista o pagina è priva di dati

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia#233]
**Priorità**: bassa

## Richiesta
Quando una lista è vuota, scriverci qualcosa tipo "Sembra che qui non ci sia nulla" per non lasciare solo i titoloni. Esempio: Molise. (Oppure nascondere i titoli delle categorie vuote e scrivere solo una volta che non ci sono dati).
https://www.covid19italia.help/issues/regione/molise/

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by antoniogiordano** [comment]
Provo a darci un'occhiata io

**Comment by iltempe** [comment]
fatto.
