### ISSUE TITLE
Migrare da licenza CC-BY a ODbL per gli Open Data

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia#234]
**Priorità**: bassa

## Richiesta

Potremmo considerare di cambiare la licenza dei dataset che rilasciamo da CC-BY ad una licenza più specifica per gli open data, come:

- https://en.wikipedia.org/wiki/Open_Database_License
- https://www.dati.gov.it/content/italian-open-data-license-v20

I termini di riuso rimarrebbero ovviamente invariati

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by iltempe** [comment]
non so. le note legali sono basate su quella licenza al momento.

**Comment by iltempe** [comment]
abbiamo messo la cc by 4.0 come suggerito da @aborruso sul repo dati.

**Comment by avivace** [comment]
Va bene, non vale la pena dover rivedere i termin e Legal.
