### ISSUE TITLE
Form embeddabile per siti

### ISSUE THREAD

**Issue by Saraveg** [emergenzeHack/covid19italia#235]
-->
**Priorità**: media

## Richiesta

Ci arriva la richiesta da un comune (sito istituzionale quindi) di avere un form (su TCI avevamo direttamente quello) o altro strumento da inserire direttamente sul loro sito.
è possibile?

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by iltempe** [comment]
molto utile. lo segnalo

**Comment by avivace** [comment]
Ciao @Saraveg ! Intendi una pagina simile a questa? https://terremotocentroitalia.herokuapp.com/segnalazioni/

**Comment by Saraveg** [comment]
si, direi troppo lunga per essere embeddata su siti (soprattutto se istituzionali). Dovrebbe essere forse un solo pulsante che rimanda al form. con una micro spiegazione tipo: Segnala una richiesta o offerta di aiuto a Covid19Italia.help

**Comment by Jolsty** [comment]
Allora devono fare sul loro sito un semplice link che punti al nostro form

**Comment by avivace** [comment]
@Saraveg Okay, quindi un semplice link? Lo citiamo sotto segnala con un titoletto tipo "Includi questi moduli sul tuo sito:" e poi col codice per farlo, simile a quello che viene mostrato alla fine qui? https://terremotocentroitalia.herokuapp.com/segnalazioni/

**Comment by iltempe** [comment]
no no ragazzi aspettate non basta rilasciare il codice HTML del nostro form? si secondo me va fatto come per TCI. grazie!

**Comment by avivace** [comment]
@iltempe intendi quel pezzetto di codice HTML citato alla fine, qui: https://terremotocentroitalia.herokuapp.com/segnalazioni/ ?

**Comment by iltempe** [comment]
Esatto. Basta fare lo stesso no?

**Comment by avivace** [comment]
> si, direi troppo lunga per essere embeddata su siti (soprattutto se istituzionali). Dovrebbe essere forse un solo pulsante che rimanda al form. con una micro spiegazione tipo: Segnala una richiesta o offerta di aiuto a Covid19Italia.help

Qua sembra che sia meglio un link e basta però

**Comment by iltempe** [comment]
Io fare entrambi. @saraveg nel tuo caso basta dare il link al nostro form. Ma se altri volessero embeddare il form io prevederei anche il codice html sotto.

**Comment by avivace** [comment]
Ricevuto

**Comment by iltempe** [comment]
scusate ma questo è da chiudere giusto? i form sono già tutti embeddabili. forse manca il codice HTML pubblicato?

**Comment by avivace** [comment]
Si, manca il codice, lo aggiungo appena riesco

**Comment by cristigalas** [comment]
<iframe src="https://covid19italia.help/segnala-base/" frameborder="0"> <a href="https://covid19italia.help/segnala-base/">Segnalazioni terremoto</a></iframe>

@iltempe questo il codice che @avivace ha inviato su Slack un paio di giorni fa a Gloria ma dentro è rimasto _Terremoto_ e va quindi corretto.

**Comment by avivace** [comment]
Il codice è disponibile aggiornato a [covid19italia.help/segnala](https://covid19italia.help/segnala), in basso
