### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by antoniogiordano** [emergenzeHack/covid19italia#236]
Telegram: andrew10111989

**Comment by simox76** [comment]
3492918919

**Comment by avivace** [comment]
Ciao @antoniogiordano , non riesco a trovare il tuo account telegram, sicuro di averlo inserito correttamente?
@simox76 Ho rimosso il numero di telefono, meglio non pubblicarlo! Mandaci il tuo nome utente su Telegram
Oppure, mandate un messaggio a @avivace su telegram e vi aggiungo io ;)

**Comment by antoniogiordano** [comment]
scusa c'era un 1 in più, andrew1011989

**Comment by avivace** [comment]
Perfetto! Ti ho aggiunto al gruppo Telegram degli sviluppatori e tecnici che stanno lavorando al progetto. Nel frattempo, guardati attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare faccelo sapere :)

**Comment by simox76** [comment]
Ciao Antonio
grazie il mio account telegram è simox767

Simone Emanuele Salis
Business Developer
Via Einstein 32a
09126 Cagliari
Cell. 349.29.18.919

INFORMATIVA AI SENSI DEL Reg. UE 679/2016. Si autorizza il trattamento dei
dati personali contenuti nella presente e-mail solo per l'adempimento di
obblighi contrattuali o di legge. Le informazioni contenute in questo
messaggio di posta elettronica e/o nel/i file/s allegato/i, sono da
considerarsi strettamente riservate. Il loro utilizzo è consentito
esclusivamente al destinatario del messaggio, per le finalità indicate nel
messaggio stesso. Qualora riceveste questo messaggio senza esserne il
destinatario, Vi preghiamo cortesemente di darcene notizia via e-mail e di
procedere alla distruzione del messaggio stesso, cancellandolo dal Vostro
sistema; costituisce comportamento contrario ai principi dettati dal Reg.
UE 679/2016 trattenere il messaggio stesso, divulgarlo anche in parte,
distribuirlo ad altri soggetti, copiarlo, od utilizzarlo per finalità
diverse. Si raccomanda di trattare i dati personali ricevuti nella presente
e-mail secondo la normativa ex Reg. UE 679/2016.
