### ISSUE TITLE
Estrarre lista label come Dati jekyll

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#237]
**Priorità**: bassa

## Richiesta
Non è urgente ma dato che il team segnalazioni aggiunge LABEL come più fa comodo di giorno in giorno forse varrebbe la pena di estrarle e popolare la pagina di issue in automatico?

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by avivace** [comment]
Sono d'accordo, alla fine cambia così spesso che ha poco senso fare liste ad hoc.

Escluderei solamente le etichette "meta" (accettato, non accettato, manca posizione, form, ...) e il resto potrebbe finire diretto

**Comment by iltempe** [comment]
ecco qua. https://developer.github.com/v3/issues/labels/#list-all-labels-for-this-repository

**Comment by iltempe** [comment]
lo ha praticamente fatto @mfortini con il file di configurazione delle label/categorie
