### ISSUE TITLE
404 su file esempio per post per il Blog

### ISSUE THREAD

**Issue by Albertopi78** [emergenzeHack/covid19italia#238]
**Priorità**: bassa

## Richiesta
Nelle istruzioni per fare un post per il blog https://github.com/emergenzeHack/covid19italia/wiki/Creare-un-Post-da-mettere-in-Blog
c'è link a un file che restituisce un 404
https://raw.githubusercontent.com/emergenzeHack/covid19italia/master/_posts/2016-8-26-usare-waze.md

## Risolto?

* [x] Ho verificato che il problema è stato risolto

**Comment by iltempe** [comment]
a posto
