### ISSUE TITLE
Uniformare Label Notizia con Notizie

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#239]
**Priorità**: bassa

## Richiesta
La label Notizia non è gestita. Rimuovere la label e lasciare solo Notizie riassegnando le label agli issue che hanno label Notizia.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by cristigalas** [comment]
@iltempe concordo!

**Comment by cristigalas** [comment]
Aggiungo che sarebbe fondamentale che nella sezione sul sito [Notizie](https://www.covid19italia.help/notizie/), fossero pubblicate anche le segnalazioni con label [Informazioni Utili](https://github.com/emergenzeHack/covid19italia_segnalazioni/issues?q=is%3Aopen+is%3Aissue+label%3A%22Informazioni+utili%22)che ad oggi sul sito non hanno una pagina dedicata. Ho verificato che alcune segnalazioni, non molte, hanno solo label Informazioni Utili e quindi al momento sono completamente invisibili sul sito. Le metterei quindi nella sezione del sito ‘Notizie’.

In alternativa, per evitare confusione, potremmo eliminare la label Informazioni Utili e rinominare Notizie in Notizie Utili che forse è anche più incisivo. Ovviamente in quest’ultimo caso, prima di procedere alla eliminazione, bisognerebbe aggiungere label Notizie Utili a tutte le segnalazioni con solo label Informazioni Utili che, ripeto, sono poche e quindi la cosa è fattibilissima.

@chiccap @Saraveg che ne dite?

**Comment by chiccap** [comment]
> Aggiungo che sarebbe fondamentale che nella sezione sul sito [Notizie](https://www.covid19italia.help/notizie/), fossero pubblicate anche le segnalazioni con label [Informazioni Utili](https://github.com/emergenzeHack/covid19italia_segnalazioni/issues?q=is%3Aopen+is%3Aissue+label%3A%22Informazioni+utili%22)che ad oggi sul sito non hanno una pagina dedicata. Ho verificato che alcune segnalazioni, non molte, hanno solo label Informazioni Utili e quindi al momento sono completamente invisibili sul sito. Le metterei quindi nella sezione del sito ‘Notizie’.
> 
> In alternativa, per evitare confusione, potremmo eliminare la label Informazioni Utili e rinominare Notizie in Notizie Utili che forse è anche più incisivo. Ovviamente in quest’ultimo caso, prima di procedere alla eliminazione, bisognerebbe aggiungere label Notizie Utili a tutte le segnalazioni con solo label Informazioni Utili che, ripeto, sono poche e quindi la cosa è fattibilissima.
> 
> @chiccap @Saraveg che ne dite?

Sì sono d'accordo se sono poche procediamo!

**Comment by luciaroma** [comment]
qui mi sa che non siamo andati avanti, però siamo concordi nelle uniformarle ... @iltempe lascio a te questo onore :-)

**Comment by cristigalas** [comment]
@iltempe @chiccap @luciaroma @Saraveg ho rivisto tutte le segnalazioni con label Informazioni Utili e verificato che ci fossero anche altre label associate. In quelle dov’è c’era solo label Info Utili ho aggiuntato anche Notizie. A questo punto eliminerei label Informazioni Utili e rinominerei label (e bottone sul sito) Notizie in Notizie Utili. Ok?

**Comment by cristigalas** [comment]
@iltempe poi rimane da togliere label grigia Notizia e attribuire le segnalazioni da form la label Notizie Utili. Si fa, please?

**Comment by iltempe** [comment]
la label grigia Notizia per me può essere tolta subito (non dovrebbe essere mai usata). sono invece perplesso sul rinominare una label che si chiama Notizie in Notizie Utili se si potesse in questa fase eviterei, non fosse altro che dobbiamo ricoinvolgere gli sviluppatori.

**Comment by cristigalas** [comment]
@iltempe va bene, aspettiamo a rinominare label ma poi facciamolo perché Notizie Utili è più chiaro...

**Comment by iltempe** [comment]
@avivace andrebbe fatto in modo che da form anziché "Notizia" sia assegnala la label "Notizie Utili" . poi chiudiamo questo issue infinito. grazie

**Comment by cristigalas** [comment]
@avivace attenzione che ora label in uso si chiama Notizie (rosa) ma vorremmo rinominarla Notizie Utili. Se però crea casino, possiamo lasciarla così. L’importante è che sparisca PER SEMPRE label grigia Notizia :)

**Comment by favoeva** [comment]
Scusate ricapitolo:
Label Notizia (grigia) scompare 
E notizie (che  ora è stata dats anche a issue info utili ) diventa notizie utili 
Corretto? 
Possiamo procedere così ?

**Comment by avivace** [comment]
Mi confermate quanto detto da @favoeva ?

**Comment by cristigalas** [comment]
@avivace confermo! Ricordiamoci però che, dopo aver rinominato Notizie in Notizie Utili, vanno cambiati link sul sito...

**Comment by cristigalas** [comment]
@avivace dimmi quando posso procedere a rinominare Notizie in Notizie Utili e a eliminare label Informazioni Utili. Io sono pronta, aspetto solo tuo ok :)

**Comment by avivace** [comment]
Informazioni Utili deve diventare Notizie Utili, corretto?

**Comment by iltempe** [comment]
@cristigalas è a posto?

**Comment by cristigalas** [comment]
@iltempe si, puoi chiudere.
