### ISSUE TITLE
Dataset disponibilità posti letto

### ISSUE THREAD

**Issue by olistik** [emergenzeHack/covid19italia#24]
Identificare e comunicare l'andamento di indici statistici significativi è un ottimo metodo per comunicare lo stato dell'emergenza.

Penso che un indice, fra tanti, che potrebbe aiutare le persone a prendere coscienza del problema sia la disponibilità dei posti letto adibiti al trattamento delle insufficienze respiratorie.

Qui il resoconto di un medico (Daniele Macchini) che tratta (anche) il problema dei posti letto: 

https://bergamo.corriere.it/notizie/cronaca/20_marzo_07/coronavirus-bergamo-medico-humanitas-facebook-situazione-drammatica-altro-che-normale-influenza-4fdf6866-6088-11ea-8d61-438e0a276fc4.shtml

https://www.facebook.com/daniele.macchini.52/posts/3395152210500625

Qui invece un'"istantanea" del dato per la Lombardia: https://twitter.com/ebobferraris/status/1236369796574445570

Qui un dataset che è stato aggiornato alla fine del 2019 (~ 2 mesi fa). (🎩 Mauro Cordoli)

http://www.dati.salute.gov.it/dati/dettaglioDataset.jsp?menu=dati&idPag=18

Sarebbe necessario trovare un dataset aggiornato più frequentemente.

Qua una semplice richiesta lanciata su Twitter:

https://twitter.com/olistik/status/1237000507652268032

**Comment by olistik** [comment]
Già che c'ero ho spedito un'e-mail a Fulvio Basili, il responsabile del dataset menzionato sopra. 🤞

**Comment by caesarsol** [comment]
Ciao, ben ritrovato @olistik ;)

Mi chiedevo esattamente la stessa cosa ieri, già ottimo il dataset da te linkato, ci darò un'occhiata!

**Comment by sapomnia** [comment]
Io avevo fatto questo grafico per Wired, con dati sulla terapia intensiva aggiornati al 2017. È da qualche giorno che non lo aggiorno, però https://public.tableau.com/profile/riccardo.saporiti#!/vizhome/Terapiaintensiva/Dashboard1

**Comment by favoeva** [comment]
c'è questo lavoro di @piersoft (non so quale sia il dataset da cui pesca per il riferimento a disponibilità posti letto in terapia intensiva. Potrei chiedere ...) http://www.piersoft.it/covid19/?incidenza=2&fbclid=IwAR2--MCNJ5016t2-tzmGF82NPwg1Rlol3kha8t5WrZhppgie-PQ2VITxlRY#6/41.838/13.881

**Comment by favoeva** [comment]
anzi potrei invitarlo qui ;)

**Comment by olistik** [comment]
@favoeva 🙇 Qui dovrebbe esserci una sorta di punto della questione: https://github.com/pcm-dpc/COVID-19/issues/70#issuecomment-597079087
È un dato difficile da ottenere e verrà valutato se inserirlo nel dataset del progetto https://github.com/pcm-dpc/COVID-19 🎩

**Comment by olistik** [comment]
@favoeva Effettivamente però:

<img width="406" alt="Screenshot 2020-03-11 at 18 19 59" src="https://user-images.githubusercontent.com/21038/76444942-f5fd9d00-63c4-11ea-905c-506734c7afe1.png">

@piersoft da dove hai tirato fuoi quei dati?
