### ISSUE TITLE
Pagina Press: il file dà 404

### ISSUE THREAD

**Issue by Albertopi78** [emergenzeHack/covid19italia#246]
**Priorità**: media

## Richiesta
Non trovo più il file per modificare il foglio press
https://github.com/emergenzeHack/covid19italia/blob/master/_data/press.csv

Vogliamo alimentarla direttamente da qui?
https://docs.google.com/spreadsheets/d/e/2PACX-1vRdGVUb583V_SQ2YG6GwrXSW33o_0_kMphmi-ua0o0bY9BROJ69fPOCFpIKAsin8O2DXbIDPVwU8jfg/pubhtml?gid=1270372062&single=true

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by avivace** [comment]
Ciao @Albertopi78 ! Abbiamo spostato press.csv qui https://github.com/emergenzeHack/covid19italia_data !
La procedura dovrebbe essere la stessa

**Comment by Albertopi78** [comment]
Grazie @avivace ho aggiunto un po' di segnalazioni. Segnalo però che ora sembra non funzionare la pagina online
https://www.covid19italia.info/press/

**Comment by avivace** [comment]
Sistemato
