### ISSUE TITLE
Aggiornamento automatico n segnalazioni 

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/covid19italia#247]
Con @Albertopi78 ci chiedevamo se esiste un modo per generare i numeri della segnalazioni automaticamente in forma dati riutilizzabili per la comunicazione.

Ad esempio questi sono quelli di oggi:
iniziative solidali 268
servizi di consegna 112
news e info utili 36
raccolte fondi 124
supporto psicologico 64
attività culturali 56
e-learning 26
bufale 23
fonti istituzionali 49
giochi bimbi 14

@iltempe

**Comment by avivace** [comment]
Me ne occupo io!

**Comment by avivace** [comment]
Adesso, puoi vedere tutte le statistiche sui conteggi (fino ad oggi) delle segnalazioni [qui](https://github.com/emergenzeHack/covid19italia_data/blob/master/statisticheSegnalazioni.csv) mentre quelle che hai citato vengono anche mostrate sul sito, nella pagina [About](https://www.covid19italia.info/about/) -> Statistiche

**Comment by chiccap** [comment]
Mi sono emozionata! E' bellissimo e molto utile grazie tantissime @avivace
