### ISSUE TITLE
Segnalazione progetti di Citizen Science

### ISSUE THREAD

**Issue by amerlo94** [emergenzeHack/covid19italia#248]
**Priorità**: bassa

## Richiesta

Non so se questo sia il luogo adatto, ma potrebbe essere utile estendere il form per le segnalazioni a progetti di Citizen Science per il contrato a Covid-19, quali ad esempio:

* https://foldingathome.org/
* http://boinc.bakerlab.org/rosetta/

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by favoeva** [comment]
Interessante @amerlo94, anche se in questo progetto il focus è sulla condivisione di informazioni a supporto dell'emergenza e abbiamo quindi già ragionato sulla opportunità di non affrontare gli aspetti di ricerca scientifica sul tema covid-19

**Comment by amerlo94** [comment]
Chiaro, chiudo l'issue allora.
