### ISSUE TITLE
Proposta di collaborazione a questionario da associazione Orlando

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#251]
L'[associazione Orlando](https://orlando.women.it/) di Bologna ci chiede di integrare all'interno del portale un loro questionario (anonimo) dedicato all'analisi dell'impatto dell'emergenza sulle famiglie, in particolare sulle donne.

Come potete vedere qui sotto, i dati saranno open (anonimizzati) e propongono di inserire, parallelamente al questionario, anche delle infografiche aggiornate con i risultati.

La gestione e la responsabilità dei dati è in capo a loro.

Ovviamente non c'è problema a pubblicizzare via bollettino.

Domande 
* Creiamo una sezione? 
* Quali criteri ci diamo per eventuali altre richieste? (oltre alla condivisione dei principi di apertura e no profit che abbiamo già stabilito)

> L’associazione Orlando, che ha ideato e gestisce il Centro delle Donne di Bologna, propone un breve questionario per indagare i dati inerenti alle condizioni abitative, familiari, lavorative e al lavoro di cura, fondamentali per misurare e valutare quanto costa, economicamente e socialmente, questa crisi/emergenza e verificare quanto ricada o meno, in termini di impatti,  sulle donne (occuparsi di figli, nipoti, genitori anziani, malatI, persone non-autosufficienti) e le conseguenze sul medio-lungo periodo.
> 
> L’obiettivo è avere dati, in particolare sul peso del lavoro di cura quotidiano, da presentare alle istituzioni per sviluppare politiche e azioni efficaci contro le numerose e sistematiche discriminazioni di genere con uno sguardo attento alle implicazioni dell’attuale emergenza.
> 
> Il questionario ha il solo scopo di ricerca e mappatura. I dati verranno messi a disposizione in forma aperta, anonimizzata e aggregata. Responsabile del trattamento dei dati è l’associazione Orlando. La policy e il regolamento sul trattamento dei dati sono disponibili nel sito dell’Associazione. https://orlando.women.it/

**Comment by luciaroma** [comment]
Ci era arrivata una segnalazione da Università di Pavia, sempre relativamente ad una ricerca sull'impatto dell'emergenza nelle persone. Questa ha un focus donne e magari è più interessante. Ad ogni modo, nel caso della segnalazione di UniPav, ci siamo detti in gruppo editors di non accettare perchè in questo momento, questo tipo di richieste/segnalazioni, non sono effettivamente centrate sui bisogni delle persone. 
Sono sicuramente utili e interessanti questo tipo di ricerche ma ci sembra che debbano essere visibilizzate più avanti, non nel pieno dell'emergenza. O comunque, non tramite la piattaforma, perché lo scopo che ci siamo dati e date è diverso.

**Comment by luciaroma** [comment]
@Saraveg @claudiamazzantiact @chiccap che ne pensate?

**Comment by claudiamazzantiact** [comment]
Ciao, concordo con @luciaroma. In questo momento non accetterei questa tipologia di richieste rimandando a più avanti una valutazione ad hoc sul dare spazio a progetti di ricerca che immagino nasceranno come funghi.

**Comment by cristigalas** [comment]
Sì anch’io lascerei perdere, anche perché su che basi scegliamo questa indagine e non altre che sono arrivate e arriveranno? Detto questo, conosco bene l’associazione Orlando e sono in gambissima, sempre un passo avanti!

**Comment by chiccap** [comment]
Intanto hanno caricato il sito...
https://women.it/covid19-uno-sguardo-di-genere/

**Comment by luciaroma** [comment]
ottimo. Possiamo comunque contattarle per sapere se, oltre alla ricerca, possiamo collaborare in qualche modo? @chiccap

**Comment by FrancescaZambi89** [comment]
Ciao, la Presidente di Orlando mi ha ricontattata e il supporto di cui avrebbero bisogno in questa fase è nel diffondere il questionario il più possibile. Finora hanno avuto 3000 risposte. Il questionario resta aperto fino al 9 aprile. @luciaroma @chiccap

**Comment by cristigalas** [comment]
> Ciao, la Presidente di Orlando mi ha ricontattata e il supporto di cui avrebbero bisogno in questa fase è nel diffondere il questionario il più possibile. Finora hanno avuto 3000 risposte. Il questionario resta aperto fino al 9 aprile. @luciaroma @chiccap

Bene, allora visto che abbiamo deciso di accettare questo tipo di richieste, direi di aprire subito una segnalazione e mandarla al bollettino così comincia a girare e semmai la rilanciamo su Fb è Twitter. Ok @chiccap e @luciaroma? @FrancescaZambi89 semmai la apri tu?

**Comment by luciaroma** [comment]
ok

**Comment by FrancescaZambi89** [comment]
> > Ciao, la Presidente di Orlando mi ha ricontattata e il supporto di cui avrebbero bisogno in questa fase è nel diffondere il questionario il più possibile. Finora hanno avuto 3000 risposte. Il questionario resta aperto fino al 9 aprile. @luciaroma @chiccap
> 
> Bene, allora visto che abbiamo deciso di accettare questo tipo di richieste, direi di aprire subito una segnalazione e mandarla al bollettino così comincia a girare e semmai la rilanciamo su Fb è Twitter. Ok @chiccap e @luciaroma? @FrancescaZambi89 semmai la apri tu?

perfetto! Grazie! si, la apro io!

**Comment by cristigalas** [comment]
@iltempe questa issue si può chiudere, è stato fatto quanto proposto.
