### ISSUE TITLE
Le pagine con liste di segnalazioni dovrebbero mostrare solo un estratto della descrizione/dati

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia#258]
**Priorità**: media

## Richiesta

Le card nelle liste di segnalazioni dovrebbero mostrare solo una piccola parte introduttiva sulla segnalazione, non ha senso stamparle in toto sempre.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by mfortini** [comment]
Jekyll ha un filtro che può essere utile https://shopify.github.io/liquid/filters/truncatewords/
