### ISSUE TITLE
Segnalazioni non presenti in mappa

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia#259]
**Priorità**: bassa

## Richiesta
Queste due segnalazioni, nonostante risultino valide ed approvate, non appaiono in mappa:
- https://www.covid19italia.help/issues/861/
- https://www.covid19italia.help/issues/862/

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by abonte** [comment]
Forse perché la posizione non è nel formato definito qui #113

**Comment by gloriaschiavi** [comment]
Ciao, ho per caso visto queste due segnalazioni. Non apparivano in mappa perchè anzichè "Posizione:" nella descrizione c'era scritto "Indirizzo:" così ho sostituito.
Il formato lat long era giusto
Posso chiudere issue direi?

**Comment by iltempe** [comment]
yes.
