### ISSUE TITLE
Rimozione dei riferimenti di TCI

### ISSUE THREAD

**Issue by olistik** [emergenzeHack/covid19italia#26]
Parzialmente collegato a #25 

- [x] link che puntano a http://terremotocentroitalia.info
- [ ] Contenuti sensati solo per TCI (da identificare)

**Comment by mfortini** [comment]
Si può chiudere?

**Comment by drizzt** [comment]
> Si può chiudere?

C'è ancora, almeno, https://www.covid19italia.info/legal/ da aggiustare. @Saraveg ci stai lavorando te, giusto?

**Comment by iltempe** [comment]
fatto. chiudo.
