### ISSUE TITLE
Consegne a domicilio: modulo ad hoc o opzione su modulo Servizi e Iniziative?

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia#260]
**Priorità**: bassa

## Richiesta

Ha senso un form apposito per segnalare esercizi commerciali che offrono la consegna a domicilio?

Alcuni dati che potrebbero essere popolati solo per questa natura di segnalazione:

- Minimo di spesa richiesta per la consegna(gratuita)
- Sistemi di pagamento accettati

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by cristigalas** [comment]
Secondo me basta aggiungere l’opzione Consegne a domicilio nel form Servizi e Iniziative, cosa che con @dontyna avevamo già discusso. E poi se l’utente seleziona questa opzione potrebbe visualizzarsi un campo in più “modalità di pagamento”. È fattibile nel caso?

**Comment by avivace** [comment]
Sì, è fattibile mostrare condizionalmente alcuni campi in base a scelte già fatte.
Aggiungo che non è necessario che le cose siano mutualmente esclusive: possiamo prevedere sia una che l'altra (ovviamente mostrando solo una delle due soluzioni) e poi usare il form ad hoc solo per determinate campagne o post sui social.

**Comment by Albertopi78** [comment]
Secondo me ci vorrebbe il bottone "segnala consegna a domicilio della spesa", con form di segnalazione ad hoc. Probabilmente è uno dei bisogni più sentiti in questo momento. Guardate Google Trends.

<img width="848" alt="Schermata 2020-03-21 alle 11 29 59" src="https://user-images.githubusercontent.com/42850988/77224568-5def7880-6b67-11ea-868d-a8a46ab8881c.png">

**Comment by mstn** [comment]
Secondo me ha senso dare più visibilità al modulo esistente perché la spesa e le consegne a domicilio sono un problema quotidiano comune a tutti.

Come dicevo su Telegram, volevo costruire un'app (web/mobile) specifica (oltre questo sito). Per le seguenti ragioni:

1. Le grosse catene che offrono servizio di consegna o simili sono intasate. Tuttavia esistono piccole realtà distribuite sul territorio (negozietti, aziende agricole) che stanno funzionando, ma forse hanno bisogno di più visibilità.
2. La segnalazione e la consultazione deve essere più semplice. Queste informazioni girano sui social, ma si perdono nel chiacchericcio.
3. L'app può rimanere dopo la crisi. La gente ha iniziato a lavorare remoto e comprare locale. Sarebbe opportuno mantenere questa buona abitudine anche dopo.

Funzionalità prima versione

1. Lista degli esercenti vicini a te
2. Informazioni su come ordinare le spesa, se viene fatta consegna a domicilio ecc...
3. Segnala esercenti

Requisiti tecnici: le segnalazioni attraverso app creano una segnalazione sul sito delle segnalazioni, emergenzeHack verifica le informazioni, periodicamente l'app si aggiorna con le informazioni validate.

Le mie domande
1. cosa pensate?
2. esiste già qualcosa
3. avete suggerimenti per un nome?
4. apro un issue a parte?

Forse può interessare anche a @albertocottica @stefanocudini

**Comment by milanini** [comment]
Salve a tutti, qlcn ha fatto qst attiva in Lombardia: https://www.filaindiana.it/    inoltre google maps  dà info su affluenza dei supermercati, magari facciamolo sapere,
inoltre ho preparato un modulo google che potete modificare e riutilizzare per organizzare localmente servizi consegna a domicilio:   https://docs.google.com/forms/d/1zMDjnhM2tZ3EA8h9GPzPCXoIHOJ_BgrkKQRE-bCSCeM/edit?usp=sharing
@cristigalas @mstn

**Comment by stefanocudini** [comment]
suggerisco di basare tutto su dati Openstreetmap, qui un esempio di dati gia open data su negozi che offrono consegna a domicilio su Milano:
[https://overpass-turbo.eu/s/RMi](https://overpass-turbo.eu/s/RMi)

Inoltre openstreetmap gia prevedere degli appositi tag sui dati per gestire tutte le informazioni rispetto alle modalita e orari di consegna:
[https://wiki.openstreetmap.org/wiki/Key:delivery](https://wiki.openstreetmap.org/wiki/Key:delivery)

inoltre in quanto trattasi di contributi di utenti utili per la comunita anche in seguito, sarebbe giusto e logico mantenere i dati su piattaforme open invece di andare a lavorare gratis per google.

@mstn ottima idea!

**Comment by milanini** [comment]
d'accordo @stefanocudini : non dicevo di lavorare su google maps, ma di dare l'informazione che  ora ricercando  su google maps l'esercizio commerciale si può spesso conoscere in tempo reale l'affluenza, e questo aiuta i cittadini a non affollarsi ...

**Comment by mstn** [comment]
Ho mandato un'email a filaindiana dicendo di passare da queste parti. Grazie @milanini (se li conosci di persona, potresti pingarli?), ottimo il form!

@stefanocudini sono negozi che la offrono in condizioni di normalità? Perché anche i Supercati Poli a Trento lo fanno (https://www.duplicardrive.it/shop/home), ma ci sono code di una settimana per prenotare uno spot per il ritiro. Hanno potenziato la loro offerta, ma sono comunque intasati.

Ho quasi finito la parte client dell'app sopra. **Se mi suggerite un nome, la pubblico su github.**

Vorrei fare tutto per benino, in modo tale che ognuno possa installarsi app e server a suo piacimento. Insomma, non fare una cosa scalabile alla startup californiana, ma replicabile. In sostanza, Milano e Catanzaro possono girare su due server diversi, tanto nessuno di Milano va a fare la spesa a Catanzaro (o viceversa). Inoltre, può tornare utile ai francesi, tedeschi e americani.

**Comment by cristigalas** [comment]
@mstn per app suggerirei di spostare la discussione in un’altra issue, semmai collegata a questa. Qui si discute del form...

**Comment by GinaBondi** [comment]
Buongiorno a tutti

Se inserissimo anche una form dedicata a "segnala Spesa a Casa dai Comuni" - o simile - ed, eventualmente, con un post nel blog incoraggiassimo questo tipo di segnalazioni?

Ho fatto un esercizio: 

da [Comuni d'Italia - Wikipedia](https://it.wikipedia.org/wiki/Comuni_d%27Italia) ho scelto qualche Comune
sulla pagina del Comune ho trovato alcuni siti ufficiali

ne ho scelti alcuni che stanno raccogliendo liste di esercizi commerciali che vogliano fare consegne a domicilio:

Name:**Comune di Parma** - Notizie
Url:https://www.comune.parma.it/notizie/Consegne-a-domicilio-1.aspx

Name:Coronavirus, spesa e medicinali a domicilio e un numero dedicato agli anziani soli e alle persone con fragilità | **Bagno a Ripoli**
Url:https://www.comune.bagno-a-ripoli.fi.it/rete-civica/coronavirus-spesa-e-medicinali-a-domicilio-e-un-numero-dedicato-agli-anziani-soli-e-alle

Name:Coronavirus. **Milano** Aiuta, al via il percorso telefonico dedicato agli #over65 – Milano Aiuta
Url:http://www.milanoaiuta.org/over65/

Name:Comune di **Barcellona Pozzo di Gotto** - Sito ufficiale
Url:http://www.comune.barcellona-pozzo-di-gotto.me.it/index.php

Name:Spesa a domicilio - **COMUNE DI CASALECCHIO DI RENO** (BO)
Url:https://www.comune.casalecchio.bo.it/servizi/notizie/notizie_fase02.aspx?ID=49857

Name:Coronavirus, spesa e medicinali a domicilio e un numero dedicato agli anziani soli e alle persone con fragilità | **Bagno a Ripoli**
Url:https://www.comune.bagno-a-ripoli.fi.it/rete-civica/coronavirus-spesa-e-medicinali-a-domicilio-e-un-numero-dedicato-agli-anziani-soli-e-alle

**Comment by cristigalas** [comment]
@ghirardinicola se decidiamo di inaugurare nuova form per le Consegne a domicilio (e mi sto convincendo che sia una buona idea ;) allora basta aggiungere dentro la form le due opzioni pubblico/privato e il Chi. Insomma un po’ come accade ora per la form Servizi e Iniziative. Poi, quando la processiamo, aggiungiamo label Servizi pubblici che sul sito sono già segnalati in [questa sezione](https://covid19italia.help/servizi-e-iniziative-solidali/). A quel punto cerchiamo di intercettare e segnalare via web form quanto più possibile i servizi offerti dai Comuni, almeno capoluoghi di provincia.

Però a questo punto direi che dobbiamo decidere rapidamente sul da farsi (form ad hoc o modifica form Servizi e Iniziative), altrimenti ci perdiamo e non offriamo un aiuto tempestivo a un bisogno che è sempre più pressante. Per me la form ad hoc va bene.

@avivace @Albertopi78 @Saraveg @chiccap @iltempe @favoeva

**Comment by GinaBondi** [comment]
Ottimo! In questo modo sarà anche possibile dar prededenza a segnalazioni per località delle quali non abbiamo ancora ricevuto notizie

**Comment by GinaBondi** [comment]
mettendo mano alla form, mi domandavo; sarebbe utile aggiungere un campo località per agevolare la ricerca sul testo?

**Comment by GinaBondi** [comment]
> mettendo mano alla form, mi domandavo; sarebbe utile aggiungere un campo località per agevolare la ricerca sul testo?

Ho scritto una sciocchezza. Scusate

**Comment by mstn** [comment]
Secondo me un form ad hoc è meglio. Domande forse scontate (sono nuovo)
* https://www.covid19italia.help/segnala/iniziative-servizi è il modo in cui fare segnalazioni per consegne a domicilio. Intendete aggiungere dei campi? Ad esempio, telefono e email dell'esercente sarebbero utili, così come indicazioni su come fare la spesa (es mandare un'email).
* Non limitiamoci alla sola modalità "consegna a domicilio". Ritiro presso l'esercente è buona e riduce i contatti al minimo.
* Qual è il tempo medio di verifica delle fonti? Potrebbe esserci una valanga di segnalazioni. Secondo voi avrebbe senso allentare il controllo su questo tipo di segnalazioni? Poiché si tratta di attività vicine a casa, molto probabilmente il comune cittadino è in grado di capire se sono vere. Si potrebbe automatizzare il controllo (verifica se esiste attività ad un certo indirizzo) per avere più sicurezza (lo posso fare io oppure @stefanocudini che è esperto di overpass-turbo :))

Ci sono anche privati e discussioni sui social che fanno liste. Segno che l'esigenza è sentita.
Ad esempio https://www.iltrentinodeibambini.it/consegne-a-domicilio-ecco-chi-le-fa/ e sono in contatto con un'allevatrice di Cuneo che sta compilando una lista di aziende agricole.

L'altro problema è capire come diffondere il modulo il più possibile. Per i comuni possiamo mandare email, ma molte attività penso non siano note ai comuni.

**Comment by mstn** [comment]
Domanda tecnica: il sito covid19italia penso sia statico e le segnalazioni sono parte della pagina (cosa positiva per maggiori performance/sicurezza). Anche il filtro su mappa penso sia locale in quanto non vedo richieste sulla rete. 

Cosa succede se ci sono tantissime segnalazioni? Gli esercenti che fanno consegna a domicilio in tutta Italia saranno tantissimi. 

Forse è opportuna una categorizzazione per comune. 

Penso che per comuni sopra i 100k abitanti, gli esercenti saranno centinaia. Gestibili, ma probabilmente serve una lista virtuale (tutti i dati lato client, ma non vengono visualizzati tutti assieme)

Ah ovviamente questo non è per disincentivare la raccolta dei dati, anzi! Stavo solo riflettendo su un possibile problema nella visualizzazione.

**Comment by Albertopi78** [comment]
Ciao, secondo me per partire abbiamo già un enorme lavoro fatto da tanti giornali locali in forma disaggregata. Bisogna prevedere anche di mappare le mappe
tipo questa: https://www.larena.it/home/provincia/spesa-e-farmaci-a-domicilio-la-mappa-del-servizio-in-provincia-di-verona-1.7996773
o tipo questo elenco dell'Eco di Bergamo: 
https://public.flourish.studio/visualisation/1584883/?utm_source=showcase&utm_campaign=visualisation/1584883

In questo caso non abbiamo nemmeno l'onere di verificare, possiamo "fidarci" del giornale locale.

Nel form andrebbe prevista la possibilità di indicare il singolo negozio o un aggregatore locale come quelli che ho indicato. 

E lo attiverei al più presto, perché da oggi direi che sarà ancor più sentita, la questione. Cosa dite?

**Comment by mstn** [comment]
Come ho detto a @milanini sull'altra discussione, perché non raccogliamo tutte queste info in un'awesome list? https://github.com/mstn/awesome-italia 

Così cosentiamo alle persone di trovare le informazioni. Pian piano iniziamo a renderle digeribili per una macchina.

Cerchiamo di tenere la discussione solo in un punto. Abbiamo tre thread: Telegram, #269 (per un'app) e questa (che sarebbe per il modulo del sito covid19italia).

**Comment by chiccap** [comment]
Ciao, io seguirei la logica per cui la piattaforma si differenzia da altri canali perchè guarda ai bisogni dei destinatari. Per questo motivo creerei un form ad hoc per segnalare consegne a domicilio/ritiro presso esercente (sono d'accordo si utile).

**Comment by cristigalas** [comment]
@avivace farei form simile a Iniziative e servizi e Contatti, cioè aggiungendo anche i contatti telefono e email e con Descrizione e poi, se possibile, aggiungerei opzione: pagamento con bancomat si/no.

**Comment by iltempe** [comment]
direi di chiudere. no?

**Comment by cristigalas** [comment]
> direi di chiudere. no?

Secondo me sì!
