### ISSUE TITLE
Segnalazioni To Gif

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#262]
**Priorità**: bassa

## Richiesta
Per una miglior divulgazione sui social si potrebbe realizzare la trasformazione del testo (o del titolo) di una segnalazione in GIF animata. Qui qualche indicazione https://support.giphy.com/hc/en-us/articles/360020071472-How-to-Text-a-GIF-

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by mfortini** [comment]
Related #159 
Related #258

**Comment by iltempe** [comment]
direi per ora di chiudere con quanto sviluppato da @mfortini
