### ISSUE TITLE
Mappa Generale - > Errore Coordinate di Segnalazioni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#265]
**Priorità**: alta

## Richiesta
Abbiamo varie segnalazioni in Golfo di Guinea. Si può verificare? http://u.osmfr.org/m/434021/ Grazie

## Come si riproduce il bug
Si vede da qui http://u.osmfr.org/m/434021/

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by gorobey** [comment]
@iltempe penso sia collegato a questo:
https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/707

**Comment by iltempe** [comment]
@gorobey riesci a dirci di più? Da cosa dipende?

**Comment by iltempe** [comment]
@gorobey quelle al centro della terra dice @mfortini sono quelle senza coordinate. Ma quelle negli stati uniti e in groenlandia?

**Comment by gorobey** [comment]
@iltempe ha le coordinate:
Vpn? un click a caso sulla mappa mi fa strano, lo zoom è bloccato

**Comment by gorobey** [comment]
comunque questa segnalazione l'avevo fatta io, e sono sicuro di aver messo le coordinate
https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/707

**Comment by gorobey** [comment]
#273 io comincerei a delimitare il campo facendo un po di validazione dei form, vediamo se la situazione migliora.

**Comment by luciaroma** [comment]
ciao, questo problema è stato poi risolto, giusto? si può chiudere la segnalazione @iltempe?

**Comment by iltempe** [comment]
pare a posto. chiudo.

**Comment by gorobey** [comment]
@iltempe io vedo ancora un sacco di marker dispersi in mezzo al mare, sono anche aumentati (sono 347 al momento
