### ISSUE TITLE
Jekyll Multilingua

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#266]
**Priorità**: media

## Richiesta
Segnalo questo https://github.com/kurtsson/jekyll-multiple-languages-plugin
Chi lo prova?

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by iltempe** [comment]
Oppure senza impazzire troppo possiamo fare una cosa molto più semplice senza plugin https://simpleit.rocks/ruby/jekyll/tutorials/multilingual-jekyll-without-plugins/#language-directories

**Comment by agofilo** [comment]
@iltempe 
Ci guardo io stasera

**Comment by iltempe** [comment]
Perfetto. c'è chi già lavora a traduzioni tra gli issue. Opterei per la soluzione senza plugin mi pare abbia meno problemi. Io stavo studiando questo https://medium.com/@desfocado/how-to-make-jekyll-multilingual-c13e74c18f1c Questo è un file che ho fatto come esempio di navigazione menu https://github.com/emergenzeHack/covid19italia_data/blob/master/navigation.yml ho fatto anche la home in inglese per fare una prova fai un fischio quando vuoi.

**Comment by iltempe** [comment]
guarda anche il #243

**Comment by iltempe** [comment]
@agofilo ho fatto tre sottocartelle con tre index di esempio da tradurre. ho aggiunto un tag "lang" che identifica la lingua.

**Comment by agofilo** [comment]
@iltempe  sono riuscito ad utilizzare i file che mi hai mandato e a rendere dinamico rispetto alla lingua il menu, rispetto al post su medium che mi hai linkato sopra non mi è chiarissimo l'uso che fa della chiave :categories nel permalink

**Comment by iltempe** [comment]
Perfetto fai pull request integro io.

**Comment by agofilo** [comment]
Ti metto lang : it su tutte le pagine italiane così non si rompe nulla in teoria e finisco di tradurre gli index en e fr poi pusho tutto

**Comment by iltempe** [comment]
ok.

**Comment by iltempe** [comment]
@agofilo direi che il metodo è affinato e funziona. ora lavoriamo sulla traduzione in altri issue. qui chiudo.
