### ISSUE TITLE
Spostare la Wiki ad una cartella 

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia#267]
**Priorità**: media

## Richiesta

È necessario spostare la wiki in una cartella "normale" insieme alle altre. Allo stato attuale delle cose non c'è un processo di contribuzione alla wiki stessa in quanto GitHub non permette di fare PR alla wiki. Ci tocca aggiungere all'organizzazione e dare write access a tutto il sito per revisionare la wiki (oppure darla a chiunque senza revisione).

All'atto pratico cambierebbe poco nulla:

- Si potrebbero fare le PR sugli articoli della wiki
- La wiki rimane leggibile e umanamente modificabile come Markdown in una cartella apposita
- Il risultato compilato e in un unica pagina finirebbe comunque in /wiki

Se vi viene in mente qualcosa contro questo spostamento fatemelo sapere.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by iltempe** [comment]
Vogliamo gestirla come i post?

**Comment by avivace** [comment]
Avresti una cartella (ignorata da jekyll) con ogni articolo in Markdown separato, proprio come adesso. Ad ogni aggiornamento di qualsiasi articolo viene riprodotto un file unico che comprende tutta la wiki, uguale a quello che viene visualizzato ora sotto /wiki

**Comment by iltempe** [comment]
si ma vogliamo gestirlo con una folder con un file solo o più file divisi per tema?

**Comment by avivace** [comment]
file divisi per poter esser gestiti meglio e comodamente, poi lo script li unisce per produrre il "manuale" che è su /wiki, come fa ora
