### ISSUE TITLE
App per consegne a domicilio

### ISSUE THREAD

**Issue by mstn** [emergenzeHack/covid19italia#269]
**Priorità**:  alta

## Richiesta

Come suggerito da @cristigalas creo una nuova issue e riporto (citandomi) la proposta fatta in questa discussione https://github.com/emergenzeHack/covid19italia/issues/260

Penso che, oltre al sito covit19italia, sarebbe utile un'app specifica per le consegne a domicilio e i negozi presenti in un vicinato per le seguenti ragioni:

1. Le grosse catene che offrono servizio di consegna o simili sono intasate. Tuttavia esistono piccole realtà distribuite sul territorio (negozietti, aziende agricole) che stanno funzionando, ma forse hanno bisogno di più visibilità.
2. La segnalazione e la consultazione deve essere molto semplice. Queste informazioni girano sui social, ma si perdono nel chiacchericcio.
3. L'app può rimanere dopo la crisi. La gente ha iniziato a lavorare remoto e comprare locale. Sarebbe opportuno mantenere questa buona abitudine anche dopo.

Funzionalità prima versione

1. Lista degli esercenti vicini a te
2. Informazioni su come ordinare le spesa, se viene fatta consegna a domicilio ecc...
3. Segnala esercenti

Requisiti tecnici: 
1. le segnalazioni attraverso app creano una segnalazione sul sito delle segnalazioni, emergenzeHack verifica le informazioni, periodicamente l'app si aggiorna con le informazioni validate.
2. codice opensource agpl e ben ingegnerizzato per consentire a chiunque di replicare il progetto nella propria città/paese/vicinato sui propri server. Potrebbe tornare utile anche in altri stati.

@milanini ha segnalato questa iniziativa simile  https://www.filaindiana.it/ , ho contattato i creatori per email chiedendo loro di passare da qui. Inoltre ha fatto questo form per raccogliere info sui punti vendita. https://docs.google.com/forms/d/1zMDjnhM2tZ3EA8h9GPzPCXoIHOJ_BgrkKQRE-bCSCeM/edit?usp=sharing

Ho quasi ultimato un semplicissimo client. **Chiedo un suggerimento per il nome!** Poi pubblico su github.

cc @stefanocudini

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by milanini** [comment]
https://ressroma.wordpress.com qui c'è l'esempio di spesa condominiale della Rete Economia Sociale e Solidale a Roma
inoltre sto apprestando anche il modulo di prenotazione spesa  https://docs.google.com/forms/d/1rCsAxfzRRW7IFL2zKwLMThRD6Pdz2m3RN8MJQhvslkQ/edit?usp=sharing     
e poi farò un altro modulo dove si censiscono associazioni e volontari disponibili alla consegna, era ciò che pensavo per il mio Comune, ma se si fa una app per tutti ...  e mi piacerebbe anche innescare un meccanismo di riconoscimento dell'attività dei volontari ... potrebbe essere interessante capire se interfacciabile con quest'altra app del Prof. Alessandro Bogliolo vedi  https://codeweek.wom.social  @mstn @stefanocudini

**Comment by cristigalas** [comment]
@mstn per il nome: qualcosa tipo _**Tutto a casa**_, giocando sull’espressione “tutti a casa”?

**Comment by mstn** [comment]
Ottimo! Pensavo anch'io una cosa del genere con i tre passaggi che hai indicato.

Il vantaggio dei form è che sono più veloci da costruire di sicuro e si possono anche replicare. Forse l'app è meglio nel lungo termine, cioè dopo l'epidemia potrebbe consentire alle persone di compare nel negozio sotto casa senza usare auto ecc... però per ora le due strade non si escludono (anzi i form possono funzionare da prototipi per capire cosa serve).

In ogni caso, farei una cosa distribuita, cioè il codice (app o form) è in comune, poi ogni piccola comunità se li gestisce come crede. 

@cristigalas è una buona idea. Chiedo, però, e se fosse in inglese? Il progetto potrebbe tornare utile anche fuori dall'Italia.

**Comment by cristigalas** [comment]
> @cristigalas è una buona idea. Chiedo, però, e se fosse in inglese? Il progetto potrebbe tornare utile anche fuori dall'Italia.

Tipo: **AAH** All at home!

**Comment by mstn** [comment]
Ahah non è male l'acronimo, come per dire "niente panico" 😨

**Comment by gorobey** [comment]
@mstn @milanini  @cristigalas  @dottorblaster  @olistik  ricordiamo a chi però è maggiormente rivolto:
agli anziani, gente che ha poca dimestichezza con la tecnologia.

**Comment by fpietrosanti** [comment]
Vi ricordo che, secondo il metodo israeliano e tedesco, la possibile quarantena forzata degli anziani, potrebbe essere l'unico vero modo per ridurre lo stress del sistema sanitario. In tal caso, l'esigenza di una rete di assistenza per gli anziani, come il suo coordinamento, è fondamentale. Ministro della Difesa Isreaeliano https://www.youtube.com/watch?v=XFfORq5KsQQ

**Comment by gorobey** [comment]
@fpietrosanti hai qualche idea da dove partire?
sarebbe da buttare giù un diagramma per schematizzare le dinamiche di funzionamento.

**Comment by milanini** [comment]
@fpietrosanti @mstn @cristigalas @gorobey     per le consegne a domicilio tutti i Comuni stanno attivando Servizi Sociali di raccordo con Protezione Civile, come presa in carico di anziani fragili e soli che potrebbero avere anche altre forme di assistenza, quindi ci sarà una mediazione digitale, anche se non escludo di fare un video tutorial, per lo meno così avevo pensato per il mio  @Comune, mettendo all'opera un'associazione giovanile

**Comment by milanini** [comment]
@fpietrosanti @mstn @cristigalas @gorobey   inoltre può essere utile per una popolazione anziana anche quest'altro modulo di segnalazione fragilità per presa in carico, naturalmente epurato di riferimenti https://docs.google.com/forms/d/1wtM2cZwN-KUf-xbvhjiFy4pJFP_qXQWWoEhjuG1PbxE/edit?usp=sharing

**Comment by milanini** [comment]
vedo anche questo di Firenze: https://www.comune.fi.it/spesadovecome/?fbclid=IwAR0mcKZvRDv4S1Li8hRBzGt0X-noUf9JNG70iVh2zqV1Pqv1CnDUaDTMttw

**Comment by mstn** [comment]
@gorobey hai ragione. Non solo anziani, direi persone non abituate ad usare la tecnologia. Ad esempio, mi dicono che molti insegnanti (età <= 60 e con istrizione "avanzata") hanno grosse difficoltà con la scuola a distanza.

Una prima visione dell'app, penso che sia molto semplice. Per ora metto il minimo apposta per non complicarla. Integrazioni con servizi sociali e segnalazioni di situazioni difficili, possono essere integrate, ma non vorrei che il layout si complicasse troppo. Secondo me covid19italia è meglio per le segnalazioni "sociali".

![Screenshot from 2020-03-22 05-53-57](https://user-images.githubusercontent.com/159818/77242712-be32f880-6c01-11ea-881f-e4dcc5e75660.png)
![Screenshot from 2020-03-22 05-53-31](https://user-images.githubusercontent.com/159818/77242714-bf642580-6c01-11ea-9f3e-fda8d02b28ac.png)
![Screenshot from 2020-03-22 05-52-51](https://user-images.githubusercontent.com/159818/77242715-bf642580-6c01-11ea-8234-b8987d69a79c.png)

Oggi implemento la logica lato server. Però questo dipende da come l'app verrà distribuita. La mia idea iniziale era di diffondere il repo github con un `Dockerfile`. Altri potevano prendere il `Dockerfile` e lanciare l'app su una loro macchina virtuale. Sebbene sia molto semplice, mi chiedo quanti abbiano disponibilità di macchine virtuali e conoscano un minimo di Docker.

L'altra soluzione è avere un unico server. Però mi chiedo quale potrebbe essere il carico. Secondo me, se abbiamo successo, abbiamo picchi di traffico considerevoli. 

Come fate con covid19italia?

**Comment by milanini** [comment]
e qui il loghetto è stupendo: https://vicinoesicuro.it/?fbclid=IwAR19t31wps98ZP3uWepA7cJXLLKYCV-TitTu9NQNgN4jy23PGie0VbGRGpw

**Comment by milanini** [comment]
segnalo anche qst a cui sta lavorando il Prof. Alessandro Bogliolo che potremmo anche contattare, persona squisitamente disponibile: https://covid19app.uniurb.it

**Comment by mstn** [comment]
@milanini per non perdersi, organizziamo queste informazioni in una awesome list https://github.com/mstn/awesome-italia. 

Penso si possa fare in parallelo alla raccolta dati più strutturata. Così se qualcuno cerca ha subito le informazioni.

**Comment by stefanocudini** [comment]
> * sicurezza (lo posso fare io oppure @stefanocudini che è esperto di overpass-turbo :))

@mstn se vuoi verificare gli inserimenti degli utenti... devi condificare gli input degli utenti con gli stessi valori di chiavi si OSM.. quindi la vedo difficile.

**Comment by milanini** [comment]
@mstn scusa ci ho provato, ma non saprei come inserire in un awesome list non sapendo programmare ...
però intanto c'è quest'altra importante possibilità eliminacode che è la app Ufirst che può essere utilizzata gratuitamente fino a giugno 2020 https://corporate.ufirst.com/it/contact-us?utm_source=Referral&utm_medium=Banner&utm_campaign=Sitoufirst

inoltre lascio anche un foglio excel bianco riutilizzabile da tutti, sempre per raccogliere chi fa consegne a domicilio, magari possiamo creare una sezione strumenti utili che altri possano riutilizzare autonomamente,                                   https://docs.google.com/spreadsheets/d/1aCaQxau-ZOJoiFisrw_QRAqgIH_nGVuLw55eyOovtG8/edit?usp=sharing
@cristigalas

**Comment by mstn** [comment]
@milanini non serve programmare

1. Clicca su fork per fare una copia del repo
2. Nella copia modifca i file markdown usando l'editor di github
3. Torna nel repo originale, sopra ti viene chiesto se vuoi fare una Pull Request, un paio di click ed è fatta

Per l'app salvacode, bisogna farla conoscere agli esercenti. Come si fa?

**Comment by gorobey** [comment]
@mstn ci sono 3 vie:
sposorizzata, mail marketing, attività di call center.
Le prime 2 le scarterei, ma va trovata un'azienda disposta a dare una mano e la lista di chi contattare (attrasaverso codice ateco).

**Comment by mstn** [comment]
@cristigalas forse possiamo chiudere questo issue?

Ho creato un repo per l'app https://github.com/mstn/aah. Qui funziona (a meno di piccoli issue che sto risolvendo) con dei dati aperti che la Provincia di Trento ha pubblicato di recente https://mstn.github.io/aah.

Ce ne sono tantissime di cose simili. Quello che ho voluto fare era una cosa facilmente clonabile in un'ottica iperlocale e che consentisse di dare una mano agli esercenti a gestire le richieste (su questo, ci sto lavorando).

Forse potete aggiungerli i dati della Provincia di Trento anche alla vostra piattaforma (se non lo avete già fatto), sono qui https://consegnointrentino.provincia.tn.it

**Comment by cristigalas** [comment]
@mstn ok Marco! Direi che la cosa migliore è segnalare che esiste questa piattaforma per la Provincia di Trento, non starei ad aggiungere i dati... Chiudo.
