### ISSUE TITLE
JSON-LD

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia#275]
**Priorità**: bassa

## Richiesta

@bertanimauro

> ciao,
> io ho provato a fare un po' di seo con i linked data in formato json-ld.
> se può servire aggiungere  questo pezzo di codice alla HEAD della home page.
> Un saluto
> Mauro
> 
> https://docs.google.com/document/d/1ZFcRWcZGTUu1UCABAqbn_5URrmXhbOdRyAG_Li4d-8E/edit?usp=drivesdk

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by bertanimauro** [comment]
ciao, ho provato a farlo anche per le pagine 

- https://www.covid19italia.help/opendata/

- https://www.covid19italia.help/issues/

sempre nel file:
https://docs.google.com/document/d/1ZFcRWcZGTUu1UCABAqbn_5URrmXhbOdRyAG_Li4d-8E/edit?usp=sharing 

Può essere utile? continuo?  volevo  farlo per altre 3 o 4 pagine. Qualcuno vuole correggerlo? Non sono uno sviluppatore. E' un passatempo il mio. E' probabile che ci siano degli errori
