### ISSUE TITLE
Donazioni in formato .csv

### ISSUE THREAD

**Issue by danielecar** [emergenzeHack/covid19italia#277]
**Priorità**: bassa

## Dataset donazioni

Ciao ragazzi, sono Daniele del gruppo #stopcovid19. Avevamo prodotto un dataset con 42 ospedali/ASL/ASST/ULSS/Regioni, relativi IBAN (rintracciati tramite fonte autorevole linkata o sito ospedale verificato), eventuali altri canali di donazione e GoFoundMe verificati al meglio che si poteva. Ho trasferito il dataset che era in formato <tr><td></td></tr> in CSV [il separatore in realtà è una semicolon:  ";" ], ve lo lascio come allegato .txt perché ne facciate quel che ritenete più opportuno.

P.S.: Se mi sono perso come inoltrare correttamente questo tipo di materiale abbiate pazienza e vogliate avere anche la cortesia di spiegarmi come fare la prossima volta ;)
[#stopcovid19 - donazioni.txt](https://github.com/emergenzeHack/covid19italia/files/4364526/stopcovid19.-.donazioni.txt)

**Comment by avivace** [comment]
Grazie daniele! Direi che il materiale va benissimo così, ora ci occupiamo di importarlo

**Comment by avivace** [comment]
Il file è da pulire, al momento è inutilizzabile: https://docs.google.com/spreadsheets/d/1YagJJ3LjMkbYSI4JZope1lRhM2_TLCUXQeft5JXqGrk/edit#gid=2092850484

**Comment by favoeva** [comment]
Ok visto 👍Provo a sistemarlo

**Comment by favoeva** [comment]
Me lo apri @avivace ? È in sola visualizzazione

**Comment by favoeva** [comment]
il file sistemato è qui https://docs.google.com/spreadsheets/d/1FWuZ2Ayv9N9gO6oW4gJkPM-u0zs3u60PoMgSEowRia8/edit?usp=sharing

**Comment by favoeva** [comment]
c'è solo da togliere colonne che non servono
ma tutti i campi del form sono corretti e nella posizione giusta (se può servire, ma non so)

**Comment by avivace** [comment]
Fatto! Ci sono
