### ISSUE TITLE
Messaggio di benvenuto gruppo telegram

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#28]
Ha senso?

**Comment by sapomnia** [comment]
Più che di benvenuto, magari per spiegare a cosa serve il canale/che info fornirà. Se mi dai uno schema di quello che inseriamo posso mettere giù una bozza

**Comment by iltempe** [comment]
possiamo inserire queste info nella descrizione del gruppo. metterei breve descrizione del progetto (che aggrega e valida informazioni sul covid19italia) che siamo civic hacker italiani e il link al sito e a questo repo github.

**Comment by avivace** [comment]
Io farei una "frontpage" (magari ristrutturare l'attuale emergenzehack.github.io ) con descrizione del progetto e rapida introduzione a tutti gli effort che sono attualmente in corso (e quindi facili indicazioni per iniziare a contribuire in base al proprio tempo/capacità!), così che una volta entrati nelle chat non ci sia bisogno di ulteriori informazioni.

**Comment by cristigalas** [comment]
Se il gruppo Telegram COVID19ITALIA è il gruppo di tutti, allora sì, sarebbe utile aggiungere un messaggio di 'benvenuto' con link a Github, alle altre chat, sito, ecc. Insomma come abbiamo fatto  per gruppone Tci. Se mi fate admin posso farlo io.
@iltempe @mfortini

**Comment by iltempe** [comment]
@cristigalas sei admin.

**Comment by cristigalas** [comment]
Messaggio fatto, anche sul canale. @iltempe puoi chiudere.
