### ISSUE TITLE
Mappatura esperienze di resilienza comunitaria

### ISSUE THREAD

**Issue by Saraveg** [emergenzeHack/covid19italia#3]
Creiamo una mappatura tipo questa (scarnissima, solo di esempio)?
[Uploading Mappatura_resilienzacomunitaria.xlsx…]()

**Comment by cristigalas** [comment]
Non riesco ad aprire il link :(

**Comment by cristigalas** [comment]
Ecco la copia su GDrive https://docs.google.com/spreadsheets/d/17dyXTy5LZGlLhYXBq4Qb4jiOsbqrGhPPhEZcqzo68Ow

**Comment by cristigalas** [comment]
Qui un po’ di iniziative solidali che ho raccolto in questi giorni e che volevo pubblicare su Medium https://docs.google.com/spreadsheets/d/17dyXTy5LZGlLhYXBq4Qb4jiOsbqrGhPPhEZcqzo68Ow
Che dici @Saraveg domani le carico nella mappatura?

**Comment by Saraveg** [comment]
@cristigalas assolutamente si e anch'io inizio a nutrire. se ci vengono idee migliori per categorizzare ovviamente cambiamo schema...

**Comment by olistik** [comment]
È utile soprattutto nell'ottica di avere un'idea di come si può essere d'aiuto a livello iperlocale (mio condominio, via o comune).
Avere dei modelli tipo "aiutare gli anziani del condominio a fare la spesa" e le relative precauzioni sociali e sanitarie permetterebbe a chi può, di replicare (mitigando esiti maldestri).

**Comment by olistik** [comment]
Quindi un elenco di format con allegata la lista delle notizie di chi li ha già applicati?

**Comment by sapomnia** [comment]
Se volete, qui c'è la mappa dei negozianti che effettuano consegne a domicilio che stiamo alimentando a Galarate (Varese) https://public.tableau.com/profile/riccardo.saporiti#!/vizhome/MappanegoziGallaratecoronavirus/Dashboard1

**Comment by Saraveg** [comment]
@cristigalas io non riesco a modificare il file. @sapomnia grazie! appena riesco ad accedere lo aggiungo

**Comment by cristigalas** [comment]
> @cristigalas io non riesco a modificare il file. @sapomnia grazie! appena riesco ad accedere lo aggiungo

Aperto! Scusate! Adesso inserisco le segnalazioni che ho raccolto in questi giorni...

**Comment by Saraveg** [comment]
bene, si sta nutrendo! forse sarebbe utile ragionare sulla categorizzazione? così ci prepariamo ad una messa online di più facile ricerca?

**Comment by cristigalas** [comment]
Io ho finito con le segnalazioni

**Comment by cristigalas** [comment]
> bene, si sta nutrendo! forse sarebbe utile ragionare sulla categorizzazione? così ci prepariamo ad una messa online di più facile ricerca?

Io pensavo che la gran parte potrebbe andare sotto la voce/label “offerta aiuto e servizi”. Ho scritto la proposta qui https://github.com/emergenzeHack/covid19italia/issues/6

**Comment by Saraveg** [comment]
@cristigalas forse so due cose diverse. un conto sono le iniziative varie istituzionali un conto esperienze comunitarie (che forse nell'issue #6 rientrano in social street/associazionismo?)

**Comment by Saraveg** [comment]
@dontyna propongo: possiamo unire i due file? propongo creando dei fogli diversi almeno 3 - associazioni, istituzioni, donazioni. se è ok posso impostarlo io. così proviamo a limitare entropia.

**Comment by Saraveg** [comment]
abbiamo sistemato il famoso file. Utile forse anche a impostare il form che si inizia a capire che cosa arriverà. sta qua:
https://docs.google.com/spreadsheets/d/17dyXTy5LZGlLhYXBq4Qb4jiOsbqrGhPPhEZcqzo68Ow/edit#gid=255255457
@iltempe @mfortini vedete voi come farlo comunicare con che. noi domani continuiamo a nutrirlo

**Comment by cristigalas** [comment]
@Saraveg @mfortini @iltempe credo che la cosa più semplice sia inserire noi a mano le segnalazioni raccolte in GDrive usando la form non appena è pronta.
