### ISSUE TITLE
Fonti istituzionali

### ISSUE THREAD

**Issue by Saraveg** [emergenzeHack/covid19italia#30]
Apro per lavorarci domani

**Comment by RocknRollAllNight** [comment]
ci sto lavorando qui:
https://docs.google.com/spreadsheets/d/1EXiPYuAzudFmLMGWGmU_PKilqgZ4guH0q-6ecNV1i4g/edit#gid=0

**Comment by cristigalas** [comment]
@RocknRollAllNight apri il file? Pensavo di aggiungere il portale Epicentro di Iss e questo link con info e materiali molto utili https://www.epicentro.iss.it/coronavirus/aggiornamenti

**Comment by RocknRollAllNight** [comment]
> @RocknRollAllNight apri il file? Pensavo di aggiungere il portale Epicentro di Iss e questo link con info e materiali molto utili https://www.epicentro.iss.it/coronavirus/aggiornamenti

Ho aperto...scusa, ma abbiamo dei problemini di condivisione con i nostri account e ho dovuto fare un paio di passaggi in più. Ottimo questo link!!!

**Comment by Saraveg** [comment]
ora dovrebbe essere aperto. Questa è la base per riempire le fonti istituzionale in hp @mfortini @cristigalas

**Comment by mfortini** [comment]
Le ho caricate sulle issue, per favore non teniamo aperte due cose (oppure comunque teniamo allineato)
