### ISSUE TITLE
Definire metodo per confederare altri enti/realtà che vogliano collaborare.

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#303]
**Priorità**: bassa

## Richiesta
Ho per ora fatto questo #256. Direi di definire un modo per tracciare chi collabora e come dando credito della collaborazione al progetto.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by claudiamazzantiact** [comment]
Ciao, ho riguardato la #256, sono d'accordo sul metodo che hai proposto. Cambierei forse il form con domande chiusa se chi compila è: cittadin@, ente/associazione, azienda. Si clicca su spunta e poi a seconda della scelta si va con biografia, nominativo (solo però nel caso delle singole persone che vogliono contribuire), etc...

**Comment by chiccap** [comment]
Ciao! Sono d'accordo con quello che dice @claudiamazzantiact e quindi rivedrei il form ragionando per legami. Non vogliamo prevederlo anche per le PA?

**Comment by Saraveg** [comment]
questa è collegata #305

**Comment by luciaroma** [comment]
concordo con @claudiamazzantiact e @chiccap . Sì tra elenco di possibilità metterei anche PA. Ora c'è ente che va bene eh ... giusto per dirci che oltre ai singoli o al terzo settore c'è anche PA

**Comment by Albertopi78** [comment]
Proposta: sentiamo i giornali locali per capire se hanno interesse a condividere dati in cambio di mappa incorporabile?

A partire da https://www.anso.it/

**Comment by favoeva** [comment]
Pasocial https://www.pasocial.info/ potrebbe interessare come partner? Dovrebbe chiedere a comunicatori associati nei comuni di farci avere dati 
 Definiamo quali  insieme a loro 
Ma potrebbe essere sicuramente Consegne a domicilio e servizi per la popolazione anziana o fragile

**Comment by favoeva** [comment]
> Pasocial https://www.pasocial.info/ potrebbe interessare come partner? Dovrebbe chiedere a comunicatori associati nei comuni di farci avere dati
> Definiamo quali insieme a loro
> Ma potrebbe essere sicuramente Consegne a domicilio e servizi per la popolazione anziana o fragile

Condivido anche qui iniziative di PAsocial dei prossimi giorni . https://velocitamedia.it/comunicare-e-informare-nellemergenza/
Alcuni relatori interessanti per attivare partenariati con PA

**Comment by iltempe** [comment]
direi che possiamo chiuedere con questa https://www.covid19italia.help/credit_form/ ?
