### ISSUE TITLE
Integrazione con portale arci/unhcr 

### ISSUE THREAD

**Issue by Saraveg** [emergenzeHack/covid19italia#305]
C'è questo progetto: https://coronavirus.jumamap.com/it_it/
Ci siamo sentiti per aprire una collaborazione.
Le cose potrebbero essere
 - avere una mappa dedicata nostra delle segnalazioni che ci arrivano per persone di origine straniera, in modo che loro possono rilanciare, 
 - incorporare nel loro sito il nostro form in inglese (e si rendono disponibili a tradurlo nelle 11 lingue delle loro comunità di riferimento). 

Che dite?

-->
**Priorità**: alta

-->

**Comment by luciaroma** [comment]
che bello! attualmente esiste già la label "stranieri" per segnalare quelle iniziative a loro dedicate. Si tratterebbe di "isolarle" su una mappa dedicata solo ai servizi che li riguarda, giusto @Saraveg ?

**Comment by Saraveg** [comment]
si, ragionerei anche su rinominare la label...

**Comment by chiccap** [comment]
> si, ragionerei anche su rinominare la label...

Sì certo sono d'accordo. L'idea mi piace! Poipotremmo inserire il progetto nella nostra pagina credits no?

**Comment by claudiamazzantiact** [comment]
Aggiungo, oltre alla mappa dare visibilità al loro numero verde e sito. Per questo potremo ragionare su una stringa nella pagina dedicata alla segnalazioni specifiche per questo target?

**Comment by iltempe** [comment]
@Saraveg i form in inglese ci sono già. basta andare alla pagina del form e selezionare la lingua corretta. manca la gestione di tutto il sito multilingua. personalmente propenderei per fare noi da aggregatori dei dati. I form sono già integrabili nel loro sito. Invece per la traduzione del form in tutte le altre lingue che vogliono possono darci sicuramente mano. (attualmente c'è italiano francese inglese) basta che aggiungi un loro rappresentante all' issue #243

**Comment by Saraveg** [comment]
Ok, intanto giro il form embeddabile in inglese. ma per la mappa sulle segnalazioni label stranieri @mfortini? è possibile?
invece @cristigalas e @chiccap secondo voi la label puo' essere modificata?

**Comment by chiccap** [comment]
> Ok, intanto giro il form embeddabile in inglese. ma per la mappa sulle segnalazioni label stranieri @mfortini? è possibile?

@Saraveg certo possiamo modificarla! A cosa pensavi? Più breve è, meglio è :)

**Comment by Saraveg** [comment]
aggiornamento: l'arci quando lo diciamo noi manda invito alla segnalazione a tutti i suoi associati
ci chiedevano se abbiamo aggiornamenti sulla mappa per i servizi a loro dedicati
su label non credo potremmo trovare di meglio per sintesi. then lasciamo così.

**Comment by cristigalas** [comment]
> > Ok, intanto giro il form embeddabile in inglese. ma per la mappa sulle segnalazioni label stranieri @mfortini? è possibile?
> 
> @Saraveg certo possiamo modificarla! A cosa pensavi? Più breve è, meglio è :)

Ma c’è davvero bisogno di cambiare nome a label Stranieri? Secondo me no, quella è a uso interno, sul sito non compare... se vogliamo pubblicare questo tipo di segnalazioni in una sezione specifica del sito (ovviamente da creare), allora potremmo dare un titolo più esplicito ed efficace alla sezione. Non so se mi sono spiegata, un conto sono le label e un conto i titoli che diamo alle varie pagine tematiche del sito.

**Comment by cristigalas** [comment]
Comunque @Saraveg vediamo quante e che tipo di segnalazioni arriveranno da Arci e cittadini stranieri e poi valutiamo come gestirle e renderle evidenti sul sito..

**Comment by iltempe** [comment]
secondo me "stranieri" con mappa dedicata non è proprio inclusiva ecco...

**Comment by cristigalas** [comment]
> secondo me "stranieri" con mappa dedicata non è proprio inclusiva ecco...

No, infatti... ma ripeto vediamo cosa arriva e poi vediamo.

**Comment by Saraveg** [comment]
Ciao, con @mfortini e @claudiamazzantiact abbiamo fatto una riunione con arci. Sintetizzo le proposte (e chiedo integrazioni):
 - entro oggi, con il loro aiuto, ragioniamo se e come cambiare la label "stranieri". Cmq si, sembra a tutti poco inclusiva. Nel primo braintorming ci dicevamo "in altre lingue" "servizi multilingua" "refugees" (??)
 - forniamo al loro sito il form e una mappa con le segnalazioni che hanno questa specifica label
 - apriamo una pagina sul sito nostro che contenga le stesse informazioni + in evidenza in qualche modo numero verde e portale juma.
 - facciamo una uscita social e media sulla collaborazione.

**Comment by claudiamazzantiact** [comment]
Hai riassunto perfettamente. Non c'è bisogno di aggiungere nulla se non che attendiamo un feedback da loro sul nome da attribuire alla label (l mio voto va a "servizi multilingua").
Rilancio la proposta di dare visibilità al loro sito e numero verde nella pagina dedicata, magari sotto o a lato della mappa dedicata.

**Comment by Saraveg** [comment]
Vi metto la risposta di arci sulla label. a me continua a non convincere ma se non ne troviamo altre...vabbè


Ciao Sara,

per quanto ci riguarda forse il nome più neutro, ma al contempo più facilmente comprensibile e indicativo è "Stranieri" nella versione italiano e "Migrants" nella versione inglese (per evitare foreigners).

Ovviamente valutate anche voi.
A presto

**Comment by luciaroma** [comment]
Stranieri non è di certo inclusivo e so che non ci soddisfa però penso che per l'uso che dobbiamo farne qui, stranieri sia la formula più adatta, più immediata e comprensibile e ... anche più neutra alla fine. "Persone di origine straniera" sarebbe la formulazione corretta, ma è troppo lunga! 
Io voto "stranieri" e "Migrants" , come proposto da Arci

**Comment by cristigalas** [comment]
In alternativa potremmo usare Migranti/Rifugiati. Non è molto più lunga ma forse più corretta... Comunque anche a me Stranieri, se non troviamo altro, va bene. Teniamo conto che se sul sito apriamo una pagina dedicata a queste segnalazioni possiamo titolarla meglio e in modo più articolato. Questa è solo la label ad uso interno.

**Comment by Saraveg** [comment]
@mfortini ma intanto form e mappa?

**Comment by Saraveg** [comment]
Chiudiamola così:
la label interna rimane "stranieri"
la pagina dedicata Migranti/Rifugiati

Adelante!

**Comment by Saraveg** [comment]
Intanto il sito Juma Map cambia così:
https://coronavirus.jumamap.com/it_it/home/

(ho già chiesto loro di modificare "in collaborazione con actionaid" in " in collaborazione con covid19italia.help)

Ora si attende la nostra pagina e qua rompo le scatole sempre allo stesso @mfortini :)

**Comment by cristigalas** [comment]
@Saraveg bella! 👏 Sarebbe però importante georiferire tutte le segnalazioni con label stranieri perché ho visto che in tutto ad oggi sono 34 ma sulla mappa sono solo 19. E siccome loro hanno pubblicato la mappa è un po’ un peccato che non si vedono tutte... Facciamo una squadra di editors ad hoc, che dite?

**Comment by Saraveg** [comment]
vado in chat editor! :)

**Comment by gloriaschiavi** [comment]
Ciao, sviluppatori. Ho notato questo ma non so se è problema nostro o loro
Una volta cliccato il segnaposto sulla mappa jumamap compare la segnalazione ma se ne vede solo un pezzo e non è cliccabile per leggere tutto, e non rimanda a nulla quindi di fatto non è fruibile. Non so se è solo una impostazione grafica, ma su mobile è ancora peggio.
@avivace @mfortini

**Comment by cristigalas** [comment]
Accidenti, è vero! Credo che accada perché le segnalazioni si aprono dentro il riquadro della mappa mentre sarebbe più semplice se si aprissero direttamente sul nostro sito o in una pagina nuova... dico giusto @avivace @mfortini?
