### ISSUE TITLE
Chatbot FAQ Covid-19

### ISSUE THREAD

**Issue by lorecioni** [emergenzeHack/covid19italia#307]
**Priorità**: bassa

## Richiesta
Buongiorno,
la mia azienda ha implementato, tramite il proprio prodotto di LiveChat, un chatbot dedicato al supporto per i cittadini sulle domande più frequenti sul Covid-19.

Possiamo fornire il codice HTML da inserire sul portale così da inizializzare la chat.

**Comment by avivace** [comment]
Ciao @lorecioni , il codice è open source?

**Comment by lorecioni** [comment]
Ciao @avivace , l'applicativo ed il codice è proprietario. E' un prodotto che viene venduto.
L'utilizzo del chatbot è però possibile semplicemente inserendo tale codice nella pagina web.

**Comment by iltempe** [comment]
@lorecioni non affiliamo servizi privati normalmente ai nostri progetti ma impostiamo i progetti affinchè le iniziative private che lo vogliano possano rilanciare i nostri dati. i dati sono opendata con lincenza aperta li trovi qui e sono costantemente in aggiornamento https://www.covid19italia.help/opendata/ se vuoi puoi usarli come contenuto per popolare il tuo servizio. GRazie!

**Comment by lorecioni** [comment]
@avivace ok grazie mille.
