### ISSUE TITLE
link errato - pagina non disponibile o in costruzione

### ISSUE THREAD

**Issue by gloriaschiavi** [emergenzeHack/covid19italia#308]
**Priorità**: alta

## Richiesta

alcuni link arrivati via telegram mandano a pagina non disponibile o in costruzione. Ad esempio queste:

https://www.covid19italia.help/issues/1132
https://www.covid19italia.help/issues/1133
https://www.covid19italia.help/issues/1135
https://www.covid19italia.help/issues/1137
https://www.covid19italia.help/issues/1155
https://www.covid19italia.help/issues/1156
https://www.covid19italia.help/issues/1163

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by avivace** [comment]
A posto!
