### ISSUE TITLE
Segnalazioni RICHIESTE D'AIUTO

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/covid19italia#310]
Ciao!

Potremmo rendere obbligatorio almeno un campo contatto in RICHIESTE DI AIUTO? Ad es. la mail. Purtroppo arrivano tante richieste senza possibilità di ricontattare il richiedente.

**Comment by Jolsty** [comment]
Posso rendere telefono o mail obbligatori, quale delle due vogliamo fare?

**Comment by chiccap** [comment]
> Ciao @chiccap,
> 
> Posso rendere telefono o mail obbligatori, quale delle due vogliamo fare?

Meglio mail è meno invasiva e scoraggia di meno alla segnalazione se obbligatoria. @cristigalas sei d'accordo?

**Comment by avivace** [comment]
@Jolsty non c'è modo di fare "almeno uno dei due"?

**Comment by chiccap** [comment]
> @Jolsty non c'è modo di fare "almeno uno dei due"?

Non l'ho detto perchè mi sembrava troppo complesso ma serebbe l'ideale!

**Comment by claudiamazzantiact** [comment]
Concordo, se possibile sarebbe la soluzione migliore per andare incontro alle diverse esigenze di chi segnala.

**Comment by Jolsty** [comment]
Ci gioco un attimo e vedo se riesco, non prometto nulla perchè la documentazione di sti form è molto.. dubbiosa

**Comment by cristigalas** [comment]
@chiccap @Jolsty concordo su almeno uno dei due. Poi se dobbiamo per forza scegliere metterei obbligatoria la mail e opzionale il telefono.

**Comment by Jolsty** [comment]
@claudiamazzantiact @cristigalas 

Provate ora: https://ee.humanitarianresponse.info/x/#aozLp5mz

Se va bene chiudete pure il ticket, grazie

**Comment by cristigalas** [comment]
@Jolsty scusa se rompo ma mi rendo conto solo ora che andrebbe aggiunto all’inizio anche il campo (obbligatorio) _Nome/Cognome_ (il nome di chi chiede aiuto). E poi il campo _Destinatari_ non lo renderei obbligatorio perché non è detto che si sappia sempre a chi destinare/rivolgere la richiesta. Concordate @claudiamazzantiact @chiccap?

**Comment by Jolsty** [comment]
@cristigalas Fatto anche queste modifiche

https://ee.humanitarianresponse.info/x/#aozLp5mz

**Comment by cristigalas** [comment]
> @cristigalas Fatto anche queste modifiche
> 
> https://ee.humanitarianresponse.info/x/#aozLp5mz

Ottimo, grazie! Ora è davvero completa!

**Comment by avivace** [comment]
Grazie @jolsty !
