### ISSUE TITLE
Aggiungere Tag  lang: it alle pagine jekyll autogenerate

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#312]
**Priorità**: alta

## Richiesta
Alle pagine come about che sono autogenerate va aggiunto il tag lang: it altrimenti scopare il menu di navigazione in alto. si veda ad esempio questa https://www.covid19italia.help/about/

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by Pinzauti** [comment]
Lo avevo aggiunto su wiki (dove non appare il menù) ma vedo è stato tolto con https://github.com/emergenzeHack/covid19italia/commit/f4395250c783b9a793c0c64461b242a114271e6b, si è rotto qualcosa?

**Comment by avivace** [comment]
Quel file viene autogenerato e non va toccato. I template che lo generato sono qui https://github.com/emergenzeHack/covid19italia/blob/master/wiki/templateWiki.mdpp
