### ISSUE TITLE
Footer multilingua: traduzioni

### ISSUE THREAD

**Issue by Albertopi78** [emergenzeHack/covid19italia#313]
Il footer di ogni versione va tradotto nella lingua corrispettiva.
Vanno mantenuti i link.

Questa è la traduzione in inglese.
 
We collect, verify and disseminate useful information on the epidemic and the coronavirus emergency in 2020: news, solidarity initiatives, home shopping deliveries, fundraisers, psychological support and much more. The project is non-profit, managed by voluntary civic hackers.
Content released under CC-BY 3.0 license. Open Data.

Non ho le competence per traduzioni in altre lingue.

**Comment by gloriaschiavi** [comment]
Ho mobilitato amici international. Qui francese: 

Nous collectons, vérifions et diffusons des informations utiles sur l'épidémie et l'urgence du coronavirus en Italie en 2020: actualités, initiatives de solidarité, livraisons à domicile, collectes de fonds, soutien psychologique et bien d’autres encore. Le projet est à but non lucratif, géré par des hackers civiques volontaires et volontaires.
Contenu publié sous licence CC-BY 3.0. Open Data.

**Comment by gloriaschiavi** [comment]
Spagnolo - passato da Google Translate ma verificato da madrelingua ;)  

Recopilamos, verificamos y difundimos información útil sobre la epidemia y la emergencia del coronavirus en Italia en 2020: noticias, iniciativas de solidaridad, entregas a domicilio, recaudación de fondos, apoyo psicológico y mucho más. El proyecto es sin fines de lucro, administrado por hackers cívicos voluntarios y voluntarios.
Contenido publicado bajo licencia CC-BY 3.0. Datos abiertos

**Comment by iltempe** [comment]
stasera metto online tutto.

**Comment by gloriaschiavi** [comment]
PORTOGHESE

Recolhemos, verificamos e divulgamos informações úteis sobre a epidemia e a emergência do coronavírus na Itália em 2020: notícias, iniciativas de solidariedade, entregas de compras em casa, angariação de fundos, apoio psicológico e muito mais. O projeto não tem fins lucrativos, gerido por civic hackers voluntários e voluntárias.
Conteúdo distribuido sob licença CC-BY 3.0. Open Data.

**Comment by iltempe** [comment]
chiudo. abbiamo usato quanto tradotto portoghese ed inglese, da ora in avanti issue dedicati con label international. grazie a tutti.
