### ISSUE TITLE
URL multilingua: traduzione

### ISSUE THREAD

**Issue by Albertopi78** [emergenzeHack/covid19italia#317]
Ciao,
tutte le URL per il multilingua andrebbero tradotte. 

Ad esempio:

https://www.covid19italia.help/en/segnala/ 
dovrebbe diventare
https://www.covid19italia.help/en/recommend/

**Comment by gloriaschiavi** [comment]
ottimo! avete cambiato REPORT in RECOMMEND? Volevo proporlo.
Si può fare anche nella homepage? #243 
Ora metto alcune proposte di traduzione.

Per le URL da tradurre, invece, è questa la pagina dove si trovano?

https://docs.google.com/spreadsheets/d/14Mx-XDOLZxBk4RMWIC_Z2L1zBQv5UfSj_oygQbZEBf8/edit#gid=1188522065

Posso iniziare con l'inglese ma bisogna concordare le parole chiave/base ("recommend" o "report" ecc, per essere un po' allineati e usarle giuste anche negli url)

Che dite?

**Comment by robertoCib** [comment]
[A questo link](https://docs.google.com/document/d/1gbFMNHxFqVUoV1c3ZvQQLS35xr-ueSpFLEm3o7qekyA/edit?usp=sharing) trovate una proposta di traduzione delle URL in Portoghese. Grazie

**Comment by iltempe** [comment]
ciao! attualmente report è un po' ovunque nella traduzione in inglese (ma è da intendersi come "segnala").

**Comment by iltempe** [comment]
ok. con la versione internazionale in portoghese, greco e inglese facciamo così con i link e lo teniamo presente per il futuro. chiudo.
