### ISSUE TITLE
Traduzione Tag Title HTML e meta description

### ISSUE THREAD

**Issue by Albertopi78** [emergenzeHack/covid19italia#318]
Anche Title html e meta description vanno tradotti in tutte le lingue. 
Teniamo traccia a partire da qui?
https://docs.google.com/spreadsheets/d/14Mx-XDOLZxBk4RMWIC_Z2L1zBQv5UfSj_oygQbZEBf8/edit#gid=1188522065

**Comment by gloriaschiavi** [comment]
ciao, io ho fatto l'inglese sul foglio 2. 
In giallo dubbi o piccole variazioni rispetto a quello che era scritto, con commento, comunque
