### ISSUE TITLE
Prevedere menu per cambiare la lingua

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#319]
**Priorità**: media

## Richiesta
Va previsto un menu sempre presente sulle pagine multilingua per cambiare la lingua quando si vuole.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by Pinzauti** [comment]
Header o footer?
Non ho seguito come è stato fatto il cambio lingua: basta un link alla versione /en e a quella di default o è necessario altro?

**Comment by iltempe** [comment]
Due possibilità

- mettiamo una lista di link/bandierine in home page a cui associare le INDEX di ogni lingua (per ora solo quella inglese e italiano)

-  facciamo un sistema di rilevamento per capire se ogni pagina ha una sua lista di pagine tradotte e facciamo comparire lo swicth di lingua solo in quelle pagine che hanno più di una lingua (più complesso)

**Comment by Pinzauti** [comment]
Ma nel menù della lingua inglese escludiamo le pagine non tradotte giusto? Perché attualmente vedo che sono presenti link che però rimandano a pagine in italiano.

Comunque io darei la possibilità di cambiare lingua in tutte le pagine, considerando che raramente si atterra sulla index.

**Comment by iltempe** [comment]
il menu delle lingue straniere possiamo configurarlo come vogliamo, per ora l'ho un po' ridotto nella versione inglese, ma ho lasciato i link alle segnalazioni per far vedere cosa è il portale nel suo complesso. per cambiare lingua ok in tutte le pagine dicci te dove preferisci e fallo pure, forse la cosa migliore sarebbe avere uno YAML in _data con una lista di lingue e link index da fare comparire nel footer?
