### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by mrBymax** [emergenzeHack/covid19italia#327]
Ciao, io e un mio amico volevamo dare una mano per quel che possiamo.
_User telegram:_

- mr_bymax

- Fil120

**Comment by avivace** [comment]
Ciao! Vi ho aggiunto alla chat Sviluppo! Nel frattempo, guardatevi attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare fatecelo sapere :)
