### ISSUE TITLE
Creare un logo per il progetto

### ISSUE THREAD

**Issue by tailot** [emergenzeHack/covid19italia#33]
È necessario creare un logo per il progetto e sostituire il vecchio.

**Comment by tailot** [comment]
Una proposta (rappresenta un virus con all'interno un grafico a torta):
![virus_data](https://user-images.githubusercontent.com/40148896/76302341-168fff00-62c0-11ea-86dd-14a328ebcbbd.png)

**Comment by olistik** [comment]
@tailot dovrebbe già esserci #9 a riguardo.

**Comment by tailot** [comment]
@olistik ok chiudo questa, vedo proposte migliori.
