### ISSUE TITLE
Colorare di blu tutti i bottoni del sito e form

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#331]
Ho visto adesso che abbiamo cambiato colore della home! Bello il blu, però forse è meglio mettere in blu o un tono del blu anche i bottoni della form e quelli dentro la pagina Tutte le segnalazioni e Segnalazioni per regione che adesso sono tutti verdi...

**Comment by Pinzauti** [comment]
Giustissimo, per le segnalazioni se mi date il via posso fare io.

**Comment by iltempe** [comment]
@Pinzauti vai. hai vinto te ;-)

**Comment by avivace** [comment]
Aspetterei upgrade a Bootstrap 4 e discuterei preliminarmente di questo tipo di cambiamenti così radicali (tipo utilizzare il blu di facebook ovunque e annullare le modifiche fatte da altri prima)

**Comment by cristigalas** [comment]
> Aspetterei upgrade a Bootstrap 4 e discuterei preliminarmente di questo tipo di cambiamenti così radicali (tipo utilizzare il blu di facebook ovunque e annullare le modifiche fatte da altri prima)

Vabbè, ora il blu di Facebook... il blu è blu, come il mare, la nazionale azzurra, la Comunità europea, ecc. 😜

**Comment by Pinzauti** [comment]
> Aspetterei upgrade a Bootstrap 4 e discuterei preliminarmente di questo tipo di cambiamenti così radicali (tipo utilizzare il blu di facebook ovunque e annullare le modifiche fatte da altri prima)

Il blu di Facebook è #3b5998 mentre quel blu che ti ha triggerato tanto è #314f96, non si somigliano più di quanto non somiglino al blu della UE; e non è ovviamente stato utilizzato ovunque ma esclusivamente nella navbar.
La possibilità di discutere preliminarmente le modifiche è stata ovviamente data [qui](https://github.com/emergenzeHack/covid19italia/pull/329), inclusa la riduzione di un paio di px di un font di dimensioni abnormi e fuori da ogni logica.
In ogni caso se qualcuno volesse annullare le mie di modifiche (come è già avvenuto e come è normale che avvenga) ne sarei più che felice poiché credo che questo dovrebbe essere lo spirito.
La mia era solo una proposta, si poteva benissimo modificare o chiudere. Può capitare di non essere d'accordo, cerchiamo però di mantenere un clima sereno alla terremotocentroitalia per favore, sennò perde di senso un po' tutto.
Ok per l'attesa di BS4.

**Comment by iltempe** [comment]
@Pinzauti @avivace mi raccomando eh... calma ;-) il merge l'ho fatto io...senza pensarci troppo quindi colpa mia, scusate. A me il blu non dispiace, ma a parte questo, usiamo pure questo issue per discuterne. In ogni caso mi piacerebbe dare "un tono nuovo" rispetto alla grafica di TCI.

**Comment by cristigalas** [comment]
Anch’io credo che usare un altro colore sia importante... e il blu a me piace.

**Comment by avivace** [comment]
@Pinzauti Credo che sia arrivato male il tono delle mie osservazioni.
Ho semplicemente espresso la mia opinione sulle modifiche, non sul tuo operato. Tra l'altro ci eravamo già chiariti in chat e riportavo qui solo per completezza.
1) Sono d'accordo col dover decidere un nuovo accent con cui dare un tocco di colore alla cosa
2) Non mi piace questo blu e lo trovo incredibilmente vicino a quello di facebook, ma ha senso quello che hai fatto. Abbiamo appurato che è stato un semplice merge troppo repentino da parte di altri.
3) " font di dimensioni abnormi e fuori da ogni logica." è una tua opinione. Io ad esempio trovo completamente senza senso le dimensioni della navbar attuale, troppo sottili e piccole. Io però non ho detto che il colore o la dimensione da te scelta erano "fuori da ogni logica e abnormi", ma ho espresso la mia opinione. Ad esempio, nel servizio di RaiNews, metà della logica del sito si sarebbe persa se la navbar avesse la forma attuale.
4)  Tra l'altro queste modifiche non sono state esplicitate ne' nei commit messages ne' nel titolo della Pull Request quindi sono passate "trasparentemente", avendo l'effetto diretto di annullare il lavoro di qualcun altro fatto prima. Non è normale che io faccia una modifica per migliorare l'aspetto **A** e in una Pull Request per modificare l'aspetto **B** tu ci inserisca senza citarla una modifica che riporta l'aspetto **A** ad uno stato precedente.
5) Io tra l'altro non ho dato nessuna colpa o responsabilità a te. Ripeto che tutto questo, come già accennato, nasce dal fatto che se ne sarebbe dovuto discutere in quella PR, eventualmente discutendo di questi cambiamenti stilistici.

**Comment by cristigalas** [comment]
Ragazzi, ma li coloriamo di blu o no questi bottoni del sito? Ormai il blu mi pare che sia acquisito visto che online da un po’...
