### ISSUE TITLE
Portugal Section Activation

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#333]
**Priorità**: media

## Richiesta
Inizio a farlo io insieme a @RobertoCiv ma va previsto menu in alto con la bandierina @Pinzauti, i form in portoghese @avivace 
poi vediamo.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by robertoCib** [comment]
Eccoci. Allora abbiamo le [faq](https://docs.google.com/document/d/1tIV7LY8d_P5xjpySO5CQH30Kxz7Gq0Hk6F_Te0fbF-Y/edit?usp=sharing), poi abbiamo [i form segnalazione più about, menù e qualcos'altro,](https://docs.google.com/document/d/1jdR4Hj0MxXRgZ4zmQJ3nJ4KcmZFFBQjVL4X_W49gIUo/edit?usp=sharing), [le note legali info segnalaz.](https://docs.google.com/document/d/1a4wFsqoLNABXQWUWfnmvaHT5YPf1fBSPEgqTy5Glp3o/edit?usp=sharing), e infine una proposta dei [nomi nelle URL](https://docs.google.com/document/d/1gbFMNHxFqVUoV1c3ZvQQLS35xr-ueSpFLEm3o7qekyA/edit?usp=sharing).

**Comment by iltempe** [comment]
@robertoCib per la Home? Idee? Label di gestione segnalazioni traduciamo quelle italiane ok?

**Comment by robertoCib** [comment]
Ok per le label. Cosa intendi per la home?

**Comment by iltempe** [comment]
la home page. la facciamo come quella italiana tradotta in portoghese?

**Comment by robertoCib** [comment]
Davo per scontato di sì per rendervi le cose più semplici. Che margine di modifica ci sarebbe, in caso?

**Comment by iltempe** [comment]
iniziamo con la home uguale poi ci ragioniamo.

**Comment by iltempe** [comment]
@robertoCib la home potrebbe avere questa forma https://www.covid19italia.help/pt/

**Comment by iltempe** [comment]
@robertoCib mi servirebbe che per ogni documento tradotto lasciassi in google doc SOLO la traduzione portoghese e tu incorporassi i link nel testo. Considera che i link alle pagine ho predisposto per metterci quelli che mi hai indicato tu.

**Comment by robertoCib** [comment]
Ok, cerco di farlo il prima possibile. Cerco anche di aprire una mail, una pagina fb e un account twitter, così possono essere incorporati anche quelli.

**Comment by robertoCib** [comment]
> @robertoCib la home potrebbe avere questa forma https://www.covid19italia.help/pt/

@iltempe  perdonami, ho già le prime richieste di correzione dell'home page
![Screenshot from 2020-03-27 17-40-11](https://user-images.githubusercontent.com/6884178/77784277-2d6d7a00-7052-11ea-818a-9f9de736e164.png)
![Screenshot from 2020-03-27 17-39-44](https://user-images.githubusercontent.com/6884178/77784321-3c542c80-7052-11ea-8c3a-a50d95a47c82.png)

e infine sostituire 'todas as iniciativas' con 'as nossas iniciativas'

possiamo fare noi questi cambiamenti da qualche parte senza farti perdere tempo?

**Comment by robertoCib** [comment]
@iltempe  Ok, creato pagina e gruppo FB e account Twitter e sistemato la [pagina delle FAQ](https://docs.google.com/document/d/1tIV7LY8d_P5xjpySO5CQH30Kxz7Gq0Hk6F_Te0fbF-Y/edit?usp=sharing) secondo le tue indicazioni.

**Comment by robertoCib** [comment]
fatta anche quella delle [note legali per le segnalazioni](https://docs.google.com/document/d/1a4wFsqoLNABXQWUWfnmvaHT5YPf1fBSPEgqTy5Glp3o/edit)

**Comment by iltempe** [comment]
una volta pronto il vostro branch proviamo a spiegarvi come editare da soli il sito.

**Comment by iltempe** [comment]
abbiamo canale slack. proseguiamo li.
