### ISSUE TITLE
Greece Section Activation

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#335]
**Priorità**: alta

## Richiesta
To be activated a section for greek people. Here put your translation and information.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by dchatzoglou** [comment]
> **Priorità**: alta
> 
> ## Richiesta
> To be activated a section for greek people. Here put your translation and information.
> 
> ## Risolto?
> * [ ]  Ho verificato che il problema è stato risolto

Thank you, I have started collecting the Greek translation..

**Comment by iltempe** [comment]
i think we can close.
