### ISSUE TITLE
Importare dati open da https://psicovid19.bedita.net/

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia#336]
**Priorità**: bassa

## Richiesta
Importare questo dataset: https://gitlab.com/bedita/covid19/supporto-psicologico-covid-19/-/blob/master/static/list.json

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by sessen-daniel** [comment]
Non so se serva il dataset in csv. In ogni caso è qui:<br/><https://docs.google.com/spreadsheets/d/1DhKot56yYLckhx7hQmHdIdO9dRieSRSZr5pP6uArwws/edit?usp=sharing>

**Comment by avivace** [comment]
In questo caso non serviva perchè il json era già processabile, serviva solamente uno script che generasse le issue (creato qui: https://github.com/emergenzeHack/covid19italia_form/blob/master/importBedita.py)
