### ISSUE TITLE
Documento volontari cinesi di Asqwe Pokiuk: Traduzione in Inglese, traduzione link dal cinese.

### ISSUE THREAD

**Issue by RobertoRettura** [emergenzeHack/covid19italia#337]
Il link è questo
https://docs.google.com/document/d/1kWBo8ff5UNz5ROWH1J1wRLA2N-WnN2JFZXmiO9ji5a8/edit# 
E gli utenti che lo condividono sono tutti anonimi, se sono cinesi e stanno usando un VPN per poter poi usare google drive ha senso... Come non avrebbe senso che qualcuno si prende la briga di creare un documento per darci informazioni diverse (di che tipo? Sono dei novax?). Però il fatto che sono dei grassroots diventa meno facile per noi.
Matteo @iltempe  se non hai modo di leggere il documento lo faccio io domani mattina.
FONTI per verificare: ho un contatto indiretto con un giornalista a Pechino, domani dovrebbe dirmi qualcosa.
Mi ha scritto una Federica su TG, ha un contatto giornalistico le ha detto che pare siano state 5 studentesse di wuhan, poi medici e volontari ad avere messo un gruppo che si chiama NPC sul twitter cinese (weibo che nel documento è citato più volte). "Ci sono vari articoli ma tutta roba tipo blog, nessun giornale... solo che magari in Asia è pure normale.." (da conversazione di Federica) ma pare ci siano anche altri doc che altri ragazzi hanno di consigli utili.
I siti citati nel documento sono shimo.is e weibo.cn (c'è anche .com).

**Comment by iltempe** [comment]
grazie @RobertoRettura io lo leggerò senz'altro a titolo informativo e faccio verificare due cose sull'immagine in cinese (qui a Prato), ma grazie tu procedi pure con le tue fonti e facci sapere. E' importante per il progetto capire questo contributo quanto sia attendibile specie per il modo con cui è arrivato (per me toccante). Grazie ancora.

**Comment by iltempe** [comment]
Mi confermano fonti attendibili pratesi che il volantino è ben fatto ed è effettivamente la descrizione in cinese di misure da adottare per evitare contagio.

**Comment by RobertoRettura** [comment]
Ottima notizia.
Io ancora nessuna novità, ma traducendolo mi sembra comunque utile, diciamo senza controindicazioni.
Nel frattempo io ne ho tradotto metà ma inizio a condividerlo. Le parti più interessanti sono link a siti web e andrebbero coinvolte persone che leggono cinese e che ce lo traducano.
Questa la traduzione https://docs.google.com/document/d/1NfpRLh2enV3EGqYFFRFKU1cFWXI_VYZOWTmGYd76Oio/edit?usp=sharing

**Comment by iltempe** [comment]
facciamo che se mi copi le parti in cinese in questa traduzione poi le passo ai miei contatti e vediamo se riusciamo a tradurre anche quelle.

**Comment by RobertoRettura** [comment]
Ok sto facendo fatica perché alcune pagine web non si copiano proprio, ci riprovo, preparo un documento dove per le parti mancanti inserisco il link.

**Comment by RobertoRettura** [comment]
Il casino è che essendo pagine web, ci sono altri link e barcode e parti grafiche che portano ad altri moduli, pagine. Qualcosa adesso (non so come) sto riuscendo a tradurla con deepl. Però meglio farlo fare a loro. Ecco il doc da girare. Su quello di traduzione ho segnato le "note/link" di riferimento.
https://docs.google.com/document/d/1NfpRLh2enV3EGqYFFRFKU1cFWXI_VYZOWTmGYd76Oio/edit?usp=sharing

**Comment by encosianima** [comment]
> Il casino è che essendo pagine web, ci sono altri link e barcode e parti grafiche che portano ad altri moduli, pagine. Qualcosa adesso (non so come) sto riuscendo a tradurla con deepl. Però meglio farlo fare a loro. Ecco il doc da girare. Su quello di traduzione ho segnato le "note/link" di riferimento.
> https://docs.google.com/document/d/1NfpRLh2enV3EGqYFFRFKU1cFWXI_VYZOWTmGYd76Oio/edit?usp=sharing

a che punto sei con la traduzione? Posso aiutarti cominciando dal fondo ( magari facendo la parte 4 e la parte 5)?

Aspetto che rispondi prima d'iniziare :D

**Comment by RobertoRettura** [comment]
Mi sono fermato,  ma riprendo domani, oggi giornata un pò complicata per me. Se vuoi partire nessun problema, teniamoci aggiornati qui così non facciamo doppioni, anche a me a un certo punto deepl mi permetteva di tradurre qualcosa. Per le pagine non fattibili, visto che un altro ragazzo cinese è entrato in chat chiederei se ci dà una mano.

**Comment by iltempe** [comment]
ciao non ho capito se è rimasto qualcosa da tradurre dal cinese. fatemi sapere.

**Comment by RobertoRettura** [comment]
Si il [mio](https://docs.google.com/document/d/1NfpRLh2enV3EGqYFFRFKU1cFWXI_VYZOWTmGYd76Oio/edit?usp=sharing) documento è tradotto a metà. L'[originale](https://docs.google.com/document/d/1kWBo8ff5UNz5ROWH1J1wRLA2N-WnN2JFZXmiO9ji5a8/edit#) che si trova in testa alla issue

**Comment by jules-94** [comment]
Ciao, è rimasto ancora qualcosa da tradurre dall'inglese o se ne sta occupando @encosianima? Nel caso potrei partire con una revisione o allineare le due traduzioni, fatemi sapere!

**Comment by RobertoRettura** [comment]
C'è questo issue https://github.com/emergenzeHack/covid19italia/issues/337
Commentate lì che parti di testo scegliete di tradurre prima di farlo, così
è più facile coordinarsi.


Il giorno mar 31 mar 2020 alle ore 11:44 Giulia <notifications@github.com>
ha scritto:

**Comment by RobertoRettura** [comment]
Allora, ho copiato il testo in inglese ancora da tradurre sul doc in italiano in modo che vedete direttamente cosa manca. Commentate qui se state per avviare una traduzione in modo che non facciamo due persona la stessa. Oltre alla traduzione, va bene anche se fate una revisione ed eventuali modifiche commentando nel doc stesso.

**Comment by jules-94** [comment]
Intanto inizio dal fondo con la Parte 4, se poi non ho aggiornamenti proseguo con la 3!

**Comment by ringhyacinth** [comment]
> The link is this
> https://docs.google.com/document/d/1kWBo8ff5UNz5ROWH1J1wRLA2N-WnN2JFZXmiO9ji5a8/edit#
> And the users who share it are all anonymous, if they are Chinese and are using a VPN to be able to use google drive then it makes sense ... How would it not make sense that someone takes the trouble to create a document to give us different information (what type? Are they novaxes?). But the fact that they are grassroots becomes less easy for us.
> Matteo @iltempe if you have no way of reading the document, I will do it tomorrow morning.
> SOURCES to verify: I have indirect contact with a reporter in Beijing, tomorrow should tell me something.
> A Federica wrote to me on TG, she has a journalistic contact told her that it seems that 5 students from Wuhan, then doctors and volunteers to have put a group called NPC on the Chinese twitter (weibo that is mentioned in the document several times) . "There are various articles but all blog-like stuff, no newspapers ... just that maybe in Asia it is also normal .." (from Federica's conversation) but it seems there are also other docs that other guys have useful advice.
> The sites mentioned in the document are shimo.is and weibo.cn (there is also .com).

HI! Here is the link of translation in Italian.
"Progetti di mutuo soccorso utili in risposta al Covid-19:esperienze di volontari cinesi in risposta alla crisi del coronavirus a Wuhan"
https://docs.google.com/document/d/1kCVcwSfXCaNXoizKWCpyIyQ7IPB3C7jW33FSgB9drt4/edit

**Comment by ringhyacinth** [comment]
HI! Here is the link of translation in Italian.
"Progetti di mutuo soccorso utili in risposta al Covid-19:esperienze di volontari cinesi in risposta alla crisi del coronavirus a Wuhan"
https://docs.google.com/document/d/1kCVcwSfXCaNXoizKWCpyIyQ7IPB3C7jW33FSgB9drt4/edit

**Comment by iltempe** [comment]
I propose to publish this document online in italian directly with a specific post.

**Comment by iltempe** [comment]
fatto. è online. chiudo.

**Comment by favoeva** [comment]
arriva anche questo (tramite nostro gruppo FB) https://www.flipbookpdf.net/web/site/6453502e03637642516004441070263217a149cd202004.pdf-bbf59e51c7795b09095316c020f45f61c6fd4b86.html?fbclid=IwAR3L3u2ywQLf1k8ly4aW-u7jdpWWoO6V4OeGNh0xQtSgLqKsTAOuDjsO0tk
@iltempe @cristigalas @RobertoRettura @ringhyacinth

**Comment by cristigalas** [comment]
@favoeva ho fatto qualche ricerca e non ho trovato nulla su questo manuale...

**Comment by favoeva** [comment]
> @favoeva ho fatto qualche ricerca e non ho trovato nulla su questo manuale...

Si anch’io non ho trovato nulla. Ho chiesto maggiori dettagli a chi lo ha segnalato
