### ISSUE TITLE
Visualizzazione errata su MOBILE

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#346]
**Priorità**: alta

## Richiesta
Da sistemare sia per errata visualizzazione su smartphone che su tablet
![2020-03-28 21 56 14](https://user-images.githubusercontent.com/6368214/77833601-f628c700-713e-11ea-969d-cfbab274ffca.jpg)

![2020-03-28 22 09 02](https://user-images.githubusercontent.com/6368214/77833859-c11d7400-7140-11ea-91a8-dba3cb8c4a43.jpg)

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by marco-acorte** [comment]
faccio io

**Comment by marco-acorte** [comment]
dovrei aver fatto. arriva pull
![immagine](https://user-images.githubusercontent.com/6375935/77834302-0becbb00-7144-11ea-8f86-af23d1192cc5.png)

**Comment by marco-acorte** [comment]
![immagine](https://user-images.githubusercontent.com/6375935/77834317-2161e500-7144-11ea-963e-7b6dc2c7d87c.png)

**Comment by marco-acorte** [comment]
anche search-box andata ok
![immagine](https://user-images.githubusercontent.com/6375935/77834481-49057d00-7145-11ea-810a-bff06d6b31fb.png)
