### ISSUE TITLE
SLACK o NO?

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#358]
**Priorità**: media

## Testo della comunicazione
In alcuni mi hanno chiesto se si possa pensare di migrare su Slack. Il mio parere è che (crescendo molto il progetto) Telegram non basti più per il coordinamento e quindi potrebbe essere una buona soluzione per migliorare come gestire le cose e come fare comunicazioni estemporanee più tracciabili. 
Mi piacerebbe raccogliere il parere di altri per decidere. Diamoci tempo qualche giorno per raccogliere un po' di pareri qui sotto. 
Grazie

**Comment by Albertopi78** [comment]
+1 per Slack. Per me utilissimo per tutte le funzionalità che ha.

**Comment by Pinzauti** [comment]
Anche io approvo 👌

**Comment by amerlo94** [comment]
Ma qualcosa di aperto e che si possa hostare? Tipo:

* https://zulipchat.com/
* https://rocket.chat/

Sono solo suggerimenti, dato che non faccio parte del team di coordinamento.

**Comment by drizzt** [comment]
Slack non lo sopporto proprio. L'applicazione in electron ti sega gb di ram per niente, inoltre hanno una politica (per il piano free) abbastanza "mafiosa" (del tipo, tutti i tuoi dati sono nostri e se non vi va bene pagate). Che funzionalità ha in più, che servono, rispetto a Telegram?

**Comment by avivace** [comment]
Concordo con @drizzt ma sono disposto a scendere a compromessi se vuol dire avere più organizzazione. Guarderei Riot e/o Mattermost.

I bridge sono semplici da installare e permettono di mantenere quello che abbiamo già su Telegram.

**Comment by cristigalas** [comment]
Anche secondo me ci serve qualcosa che faciliti e organizzi la discussione e il lavoro. Non ho nulla contro Slack ma sono aperta a tutte le soluzioni che riteniamo più idonee. Da profana pensavo anche a Discourse, con Ricostruzione Trasparente l’abbiamo usata e non era male. E poi è open source :)

**Comment by favoeva** [comment]
> con Ricostruzione Trasparente l’abbiamo usata e non era male. E poi è open source :)

Concordo @cristigalas 
La necessità di una comunicazione di progetto strutturata e asincrona c’è tutta. 
ho dato una prima occhiata qui (zulip vs slack) https://zulipchat.com/why-zulip/  e , da profana anch’io , zulip mi sembra ottimo

**Comment by iltempe** [comment]
a me sta bene anche uno strumento alternativo a SLACK se ci pare più adeguato.  Se è per il solo fatto di essere open vorrei che non prevedesse limitazioni se non pagando RIOT mi pare una valida alternativa in questo https://about.riot.im/ . Dall'altra parte non vorrei scegliere uno strumento OPEN solo perchè ci piace, non ho mai usato RIOT e quindi non saprei fare una comparazione vs SLACK. @drizzt mi sai dire qualcosa di più?

**Comment by dontyna** [comment]
+1 per Slack, che permette di dividere le conversazioni in diversi canali e soprattutto è molto utile se qualcuno non accede per un'intera giornata e vuole recuperare le cose fatte e dette. Permette condivisione di file e chiamate interne.

**Comment by iltempe** [comment]
ciao a tutti, valutando le espressioni qui sopra riportate e facendo un rapido conteggio di chi è a favore o comunque favorevole a SLACK direi di provare intanto a migrare li. poi vedremo. qui il link di invito. chiudo.  https://join.slack.com/t/covid19peoplehelp/shared_invite/zt-d82w48yo-D5CtSAL2RdN99AzcA5uJ0g

**Comment by drizzt** [comment]
> a me sta bene anche uno strumento alternativo a SLACK se ci pare più adeguato. Se è per il solo fatto di essere open vorrei che non prevedesse limitazioni se non pagando RIOT mi pare una valida alternativa in questo https://about.riot.im/ . Dall'altra parte non vorrei scegliere uno strumento OPEN solo perchè ci piace, non ho mai usato RIOT e quindi non saprei fare una comparazione funzionale vs SLACK. @drizzt mi sai dire qualcosa di più?

Volendo posso mettere un'istanza di mattermost o rocketchat su un mio server che è praticamente uguale a slack, ma senza i problemi e le limitazioni della versione free di slack

**Comment by iltempe** [comment]
ciao a tutti per ora chiudo questo, se volessimo nuovamente migrare apriamo issue dedicata.
