### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#36]
Passare il layout su Bootstrap 4.
Esistono le card che vanno a sostituire i panel

## To do

- [ ] Verificare se usiamo Popper
- [ ] getboostrap.com suggerisce di usare jQuery `v3.4.1` mentre noi usiamo ora jQuery `v3.1.1`. Verificare che non ci siano regressioni.
- [ ] Verificare che Bootstrap Social (`v.5.0.0`) funzioni. L'ultima stable è `v.5.1.1.` (https://github.com/lipis/bootstrap-social)
- [ ] In `/_layouts/minimal.html` vengono importate delle versioni locali degli asset di Bootstrap mentre in `_layouts/base.html` vengono importati gli asset remoti. Verificare perché.

## Maptune

- [ ] Anche `maptune/maptune_{embed,flat1}.html` importano degli asset locali di Bootstrap in `maptune/assets/{css,js}/`.
- [ ] In `maptune/assets/css/`, `bootstrap.css` è `v3.0.3` mentre `bootstrap.min.css` è `v3.3.6`.
- [ ] _Maptune_ dipende da _Bootstrap DateTimePicker_.

**Comment by iltempe** [comment]
chiudo.
