### ISSUE TITLE
Instagram?? 

### ISSUE THREAD

**Issue by elim95** [emergenzeHack/covid19italia#360]
Salve a tutti! 
Come faccio a contribuire, aggiungendo contenuti sulla pagina Instagram? Grazie!

**Comment by chiccap** [comment]
Ciao! 

Puoi iscriverti al gruppo telegram e segnalare la tua disponibilità: https://t.me/joinchat/BgW6eBM4lxLxJlf_AWKDDw
Dopodichè verrai inserita nel gruppo di lavoro Instagram. Ti aspettiamo!
