### ISSUE TITLE
Semplificazione pagina  "Tutte le segnalazioni"

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#364]
La pagina con tutte le segnalazioni (https://www.covid19italia.help/issues/ ) inizia a diventare un po' lunga e pesante (è quasi 8MB, ci sono +2000 segnalazioni)

Proposte:
1. Eliminare la lista e lasciare solo la mappa e i bottoni con le categorie, magari mettendoli accanto
2. Semplificare la lista inserendo meno dati
3. Eliminare la lista e lasciare solo quelle per regioni, che poi rimandano alle liste per categorie
4. ...

**Comment by Albertopi78** [comment]
In effetti così com'è la lista non serve a molto. 
Si può "paginare"?

**Comment by cristigalas** [comment]
> La pagina con tutte le segnalazioni (https://www.covid19italia.help/issues/ ) inizia a diventare un po' lunga e pesante (è quasi 8MB, ci sono +2000 segnalazioni)
> 
> Proposte:
> 
> 1. Eliminare la lista e lasciare solo la mappa e i bottoni con le categorie, magari mettendoli accanto
> 2. Semplificare la lista inserendo meno dati
> 3. Eliminare la lista e lasciare solo quelle per regioni, che poi rimandano alle liste per categorie
> 4. ...

4. Io fare così: solo bottoni e mappa ma con solo una decina di segnalazioni visibili perché danno subito l’idea all’utente di ciò che può trovare. E semmai queste 10 segnalazioni sarebbe meglio fossero le ultime inserite, piuttosto che le prime 10 della categoria Raccolte fondi. Infine, credo sia assolutamente necessaria una ricerca almeno per categorie altrimenti diventano inconsultabili... e questa funzione possiamo inserirla in home.

**Comment by chiccap** [comment]
> 1. fare così: solo bottoni e mappa ma con solo una decina di segnalazioni visibili perché danno subito l’idea all’utente di ciò che può trovare. E semmai queste 10 segnalazioni sarebbe meglio fossero le ultime inserite, piuttosto che le prime 10 della categoria Raccolte fondi. Infine, credo sia assolutamente necessaria una ricerca almeno per categorie altrimenti diventano inconsultabili... e questa funzione possiamo inserirla in home.

Quoto Cristina. Aggiungo solo che forse nelle pagine regioni e province metterei una sorta di legenda colori per navigare la mappa.

**Comment by cristigalas** [comment]
@mfortini poi comunque aprirei anche una discussione sui campi che sono visibili sul sito per ciascuna scheda. Ora alcuni sono inutili o ridondanti, vedi ad esempio in questa immagine (tipologia Supporto psicologico) ma sono un po’ tutte così... 
![FA663D19-A68F-47E8-989E-B19DFCAB7D8A](https://user-images.githubusercontent.com/21283775/78039836-e7285b80-736e-11ea-89ee-7a9c36d4f502.jpeg)

Eventualmente apriamo nuova issue su questo punto?

**Comment by mfortini** [comment]
Sì, apriamo nuova issue, perché considera che nella scheda di una segnalazione per ora sono riportati tutti i campi in modo "acritico", si possono organizzare in modo più "intelligente'

**Comment by mfortini** [comment]
Una prima versione è in http://covid19italia.help/issues_new ma ci sono dei problemi CSS da risolvere (il blocco <h2> finisce a coprire il link "Altre segnalazioni")

**Comment by cristigalas** [comment]
@mfortini ok Matteo, attendo fiduciosa ;)

**Comment by Pinzauti** [comment]
Con https://github.com/emergenzeHack/covid19italia/commit/62e5ce395422f0ec295bc9e772763f6299f1fc64 dovremmo esserci.

**Comment by cristigalas** [comment]
@mfortini @Pinzauti ottimo lavoro! 👏👏 grazie!
