### ISSUE TITLE
Modello autodichiarazione per firma fisica e/o digitale

### ISSUE THREAD

**Issue by tailot** [emergenzeHack/covid19italia#37]
Ciao in queste ore stanno circolando su web vari modelli di autodichiarazione (tipo questo https://www.asaps.it/downloads/files/autodichiarazione_post_DPCM_9_marzo_2020.pdf) da stampare con un dispendio di carta incredibile per tutta la nazione (speriamo non sia troppo tardi). Valutare se necessario creare un modello digitale facilmente configurabile per firma digitale ed evitare questo scempio di spreco di risorse cartacee con mini campagna su social network per incentivare l'utilizzo della firma digitale e salvare qualche albero.

Elenco dei servizi con firma digitale gratuita per persone fisiche:

- Dike GoSign: https://www.firma.infocert.it/prodotti/dikegosign.php

**Comment by favoeva** [comment]
Impossibile purtroppo va esibito in caso di controlli fisici . Presupporrebbe necessità di invio a sistema al quale agenti polizia hanno accesso durante il controllo .

**Comment by tailot** [comment]
@favoeva è un vero peccato! :-(

**Comment by favoeva** [comment]
chiuderei questa issue e risolverei la disponibilità del modello ministeriale in  fonti istituzionali issue #30  se sei daccordo @tailot

**Comment by favoeva** [comment]
comunque questo è il PDF editabile di Ministero interno https://www.interno.gov.it/sites/default/files/allegati/modulo_autodichiarazione_10.3.2020.pdf
