### ISSUE TITLE
Eliminare la visualizzazione di alcuni campi inutili nelle schede delle segnalazioni

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#375]
@mfortini come ho scritto qui #364, bisognerebbe fare una riflessione sui campi che sono visibili sul sito per ciascuna scheda. Ora alcuni campi sono inutili o ridondanti, vedi ad esempio in questa immagine (tipologia Supporto psicologico) ma sono un po’ tutte così... Chiedo consiglio anche al team editors @chiccap @favoeva 
![D6DC21F2-63B1-441B-BA56-281A189EE721](https://user-images.githubusercontent.com/21283775/78073030-6b470700-73a0-11ea-8522-205b8caa6e94.jpeg)

**Comment by chiccap** [comment]
> @mfortini come ho scritto qui #364, bisognerebbe fare una riflessione sui campi che sono visibili sul sito per ciascuna scheda. Ora alcuni campi sono inutili o ridondanti, vedi ad esempio in questa immagine (tipologia Supporto psicologico) ma sono un po’ tutte così... Chiedo consiglio anche al team editors @chiccap @favoeva
> ![D6DC21F2-63B1-441B-BA56-281A189EE721](https://user-images.githubusercontent.com/21283775/78073030-6b470700-73a0-11ea-8522-205b8caa6e94.jpeg)

Sono d'accordo a livello di visyalizzazione se fosse possibilepotremmo eliminare alcuni campi così risulterebbe anche più abile la consultazione!

**Comment by mfortini** [comment]
Decidiamo quali, attualmente c'erano tutti per evitare di dimenticare delle informazioni

**Comment by chiccap** [comment]
> Decidiamo quali, attualmente c'erano tutti per evitare di dimenticare delle informazioni

Io toglierei sicuramente:
- Natura
- Tipo di soggetto
- Titolo

@cristigalas che ne dici?

**Comment by iltempe** [comment]
questa è facile da fare non appena siamo d'accordo su quali togliere ;-)

**Comment by cristigalas** [comment]
@chiccap concordo! Ho fatto una verifica su tutte le tipologie di segnalazione e sono quei tre i campi superflui e quindi da eliminare. Secondo me @iltempe puoi procedere.

**Comment by cristigalas** [comment]
@iltempe qui ci siamo quasi... se togli dalla visualizzazione sul sito i campi indicati da @chiccap, puoi chiudere. Tra l’altro si tratta di una modifica importante per migliorare la fruibilità delle segnalazioni.
