### ISSUE TITLE
File Richieste di aiuto - aggiornamento automatico

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/covid19italia#380]
Per meglio gestire le richieste di aiuto abbiamo creato questo file: https://docs.google.com/spreadsheets/d/1QKfgaJTQVhEIrsKSpPU2hikg3x8T_hp2u7Ahv8QBh4s/edit#gid=0

E' possibile creare una sorta di automatismo per cui quando le richieste di aiuto vengono accettate vengono riversate su questo file?

Grazie!

@avivace @cristigalas @luciroma @claudiamazzantiact @polva13

**Comment by avivace** [comment]
Imposterei un Issue Tracker privato per gestire meglio (e con le priorità) quello che state facendo. Basta un account su https://gitlab.com 

Fammi sapere se/quando provare a fare questo test

**Comment by chiccap** [comment]
> Imposterei un Issue Tracker privato per gestire meglio (e con le priorità) quello che state facendo. Basta un account su https://gitlab.com
> 
> Fammi sapere se/quando provare a fare questo test

Grazie @avivace! @luciroma @claudiamazzantiact @polva13 secondo voi può funzionare con le territoriali?

**Comment by luciaroma** [comment]
Ciao, io per prima non conosco come funziona il sistema ma ... possiamo fare un test e capire di coseguenza se può funzionare con le altre, ho qualche dubbio, perchè alcune di loro non si sono nemmeno approcciate a github ma tentar non nuoce.
Dobbiamo registrarci a gitlab quindi, giusto? Che altro? :-)

**Comment by cristigalas** [comment]
@iltempe questa issue secondo me si può chiudere, perché @avivace ha attivato un Issue Tracker per le Richieste di Aiuto che stiamo usando già da una decina di giorni.
