### ISSUE TITLE
Issue fields and labels in English

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#383]
For internationalization, we may need to take care of many different international words, in particular:
* "accepted" label
* "position" label
These are just two that are treated specially.
I propose that we keep:
* field names
* labels
in English to avoid errors

Just to make it clear: this words will be seen in English **just in the backend** and not in the website

**Comment by dchatzoglou** [comment]
For me, there is no problem at all to use the English text to avoid mistakes. I think, it would be very helpful for you, otherwise, you would need to keep another file for the field and label translations.

**Comment by iltempe** [comment]
@robertoCib has translated all labels from italian in english here. https://docs.google.com/spreadsheets/d/1a3N9kTjEs3FCzfw0_MmxYXq8z87m12kR-BndiFQfNEU/edit#gid=0 should be very important converge on 1 list.

**Comment by mfortini** [comment]
Ok let's do it. I will close the issue as soon as I'm done.

**Comment by iltempe** [comment]
@avivace on your side please configure the webforms with this label for international versions.  Italian version i think can be  managed with italian +  english label version (since many reports are already present...).

**Comment by iltempe** [comment]
@mfortini @avivace for future repo we should also put the labels as default here https://github.com/organizations/emergenzeHack/settings/labels or maybe once one repo is setup it is enough  an existing repo.

**Comment by avivace** [comment]
I agree on this. Labels and column_names should stay in a standard language. It will help the backend logic, too

**Comment by iltempe** [comment]
ne apro un altro sulla lista delle label.
