### ISSUE TITLE
Aggiungere “regione_manuale: tutte” alle segnalazioni di interesse nazionale 

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#387]
Grazie a @mfortini da oggi possiamo inserire la dicitura _**regione_manuale: tutte**_ dentro le segnalazioni di interesse nazionale così compaiano anche nelle [pagine](https://www.covid19italia.help/issues/regione/) dedicate a ciascuna regione. @gloriaschiavi ha fatto una prova con [questa segnalazione](https://www.covid19italia.help/issues/337/) e funziona. È un modo per popolare anche le pagine delle Regioni che hanno poche segnalazioni, come ad es. il Molise.

Il punto è **come selezionare le segnalazioni di interesse nazionale?**
Gloria suggeriva di selezionare “quelle istituzionali, oppure pensiamo alle grosse associazioni che sono presenti su tutto il territorio e controlliamo che servizi a livello nazionale siano segnalati in tutte le regioni (tipo croce rossa ecc).”

Che ne pensate @chiccap @favoeva @luciaroma e tutte/tutti editors?

**Comment by favoeva** [comment]
@cristigalas Mi sembra ottima come impostazione. Procediamo ! 

> Grazie a @mfortini da oggi possiamo inserire la dicitura _**regione_manuale: tutte**_ dentro le segnalazioni di interesse nazionale così compaiano anche nelle [pagine](https://www.covid19italia.help/issues/regione/) dedicate a ciascuna regione. @gloriaschiavi ha fatto una prova con [questa segnalazione](https://www.covid19italia.help/issues/337/) e funziona. È un modo per popolare anche le pagine delle Regioni che hanno poche segnalazioni, come ad es. il Molise.
> 
> Il punto è **come selezionare le segnalazioni di interesse nazionale?**
> Gloria suggeriva di selezionare “quelle istituzionali, oppure pensiamo alle grosse associazioni che sono presenti su tutto il territorio e controlliamo che servizi a livello nazionale siano segnalati in tutte le regioni (tipo croce rossa ecc).”
> 
> Che ne pensate @chiccap @favoeva @luciaroma e tutte/tutti editors?

**Comment by chiccap** [comment]
Ma è una bellissima novità! Grazie a tutt*! Sono molto d'accordo anche io. Aggiorno le policy con questa nuova funzione.

**Comment by cristigalas** [comment]
Ok allora partiamo! Come suggeriva @gloriaschiavi potremmo quindi aggiungere la dicitura alle segnalazioni partendo innanzitutto da:

- **associazioni nazionali** 
- **notizie utili di interesse nazionale**

Aggiungerei poi segnalazioni di interesse nazionale contenute in:

- **Donazioni beni e Offerte servizio** (in particolare per le segnalazioni di piattaforme web, servizi online, ho visto che un po’ ci sono)
- **Sostegno lavoro/imprese**
- **Raccolte fondi nazionali** (che comunque credo sia poche, al momento mi viene in mente solo quella lanciata dal Dipart. naz. Protezione Civile)

Escluderei tutte le altre categorie perché o non contengono info di interesse nazionale oppure propongono servizi e attività online e telefoniche (vedi ad es. supporto psicologico o attività ricreative) a cui naturalmente chiunque può accedere indipendentemente da dove si trovi. 

@chiccap allerti tu i nuovi editors?

**Comment by chiccap** [comment]
> Ok allora partiamo! Come suggeriva @gloriaschiavi potremmo quindi aggiungere la dicitura alle segnalazioni partendo innanzitutto da:
> 
> * **associazioni nazionali**
> * **notizie utili di interesse nazionale**
> 
> Aggiungerei poi segnalazioni di interesse nazionale contenute in:
> 
> * **Donazioni beni e Offerte servizio** (in particolare per le segnalazioni di piattaforme web, servizi online, ho visto che un po’ ci sono)
> * **Sostegno lavoro/imprese**
> * **Raccolte fondi nazionali** (che comunque credo sia poche, al momento mi viene in mente solo quella lanciata dal Dipart. naz. Protezione Civile)
> 
> Escluderei tutte le altre categorie perché o non contengono info di interesse nazionale oppure propongono servizi e attività online e telefoniche (vedi ad es. supporto psicologico o attività ricreative) a cui naturalmente chiunque può accedere indipendentemente da dove si trovi.
> 
> @chiccap allerti tu i nuovi editors?

Già avvisare e insistito in policy! :)

**Comment by cristigalas** [comment]
> > Ok allora partiamo! Come suggeriva @gloriaschiavi potremmo quindi aggiungere la dicitura alle segnalazioni partendo innanzitutto da:
> > 
> > * **associazioni nazionali**
> > * **notizie utili di interesse nazionale**
> > 
> > Aggiungerei poi segnalazioni di interesse nazionale contenute in:
> > 
> > * **Donazioni beni e Offerte servizio** (in particolare per le segnalazioni di piattaforme web, servizi online, ho visto che un po’ ci sono)
> > * **Sostegno lavoro/imprese**
> > * **Raccolte fondi nazionali** (che comunque credo sia poche, al momento mi viene in mente solo quella lanciata dal Dipart. naz. Protezione Civile)
> > 
> > Escluderei tutte le altre categorie perché o non contengono info di interesse nazionale oppure propongono servizi e attività online e telefoniche (vedi ad es. supporto psicologico o attività ricreative) a cui naturalmente chiunque può accedere indipendentemente da dove si trovi.
> > @chiccap allerti tu i nuovi editors?
> 
> Già avvisate e inserito in policy! :)

Sei troppo efficiente! 😘

**Comment by favoeva** [comment]
ho aggiunto dicitura regione_manuale: tutte anche a questa fake news https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/2418

in generale sulle fake ... farei una riflessione: forse è importante che appaiano anche nelle ricerche per Regione, ma ditemi (caso mai tolgo ;) )

**Comment by cristigalas** [comment]
@favoeva non so... le bufale hanno una loro categoria ben in evidenza in home. Però forse sì, comunque merita una riflessione.

**Comment by cristigalas** [comment]
@iltempe secondo me questo issue si può chiudere. Stiamo usando ormai da tempo questa funzione.
