### ISSUE TITLE
Home Page Errata gestione rimozione icona

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#389]
**Priorità**: media

## Richiesta
Se nella home non si vuole un logo di quelli configurati di default si ottiene questo https://gr.covid19people.help con un "buco" vuoto. Sarebbe cosa buona gestire dinamicamente la spaziatura tra i loghi configurati.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by edge33** [comment]
posso farla io questa

**Comment by iltempe** [comment]
prova pure. sarebbe bene sempre passare da pull request. grazie.

**Comment by iltempe** [comment]
@edge33 possiamo provarla sul branch della grecia?

**Comment by edge33** [comment]
Ho aperto la pr anche per il sito PT, se funziona, possiamo chiudere la issue
