### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by edge33** [emergenzeHack/covid19italia#391]
Ciao, vorrei contribuire al progetto, il mio nickname telegram è @edge33

**Comment by iltempe** [comment]
ciao @edge33 recentemente ci siamo spostati su slack. il link di invito lo trovi qui  https://join.slack.com/t/covid19peoplehelp/shared_invite/zt-dbg7ctmp-ta7ZYJN5Lvvse1w0eCymMQ
