### ISSUE TITLE
Informazioni su donazioni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#4]
un'idea di @dontyna : riservare una sezione per informazioni dettagliate e validate sulle possibilità di donazione.

**Comment by dontyna** [comment]
Intanto metto qui questo che può esserci utile https://docs.google.com/spreadsheets/d/1GmyjJYiJQ0VSvePvgbzaggBOIXeQKGtYC2oLO37LCmk/edit?usp=sharing

**Comment by cristigalas** [comment]
> Intanto metto qui questo che può esserci utile https://docs.google.com/spreadsheets/d/1GmyjJYiJQ0VSvePvgbzaggBOIXeQKGtYC2oLO37LCmk/edit?usp=sharing

Intanto ho inserito nel file un paio di segnalazioni...

**Comment by cristigalas** [comment]
Segnalo questo https://www.ilpost.it/2020/03/10/raccolte-fondi-ospedali-coronavirus/

**Comment by iltempe** [comment]
@dontyna @cristigalas ha ancora senso tenerlo aperto? abbiamo il form giusto?

**Comment by cristigalas** [comment]
@iltempe si, puoi chiudere.
