### ISSUE TITLE
Integrare servizi gratuti segnalati ad agid con quelli segnalati a covid19italia 

### ISSUE THREAD

**Issue by tailot** [emergenzeHack/covid19italia#41]
Al fine di fare convergere i servizi gratuiti in un unico punto è necessario aggiornare le segnalazione effettuate a covid9italia offerte anche dai singoli cittadini (all'interno dei comuni) a quelle segnalate dalle aziende verso le istituzioni al link: https://solidarietadigitale.agid.gov.it/#/

**Comment by iltempe** [comment]
@tailot ma come si fa? @napo che dici? se ogni segnalazione la inviamo ad AGID non vorrei ci bannassero ;-)

**Comment by iltempe** [comment]
chiudo, al momento il progetto ha presto un'altra piega. in caso serva riapriamo più avanti.
