### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by giulio93** [emergenzeHack/covid19italia#42]
I want to contribute as a developer.
My telegram profile: gpilotz

**Comment by avivace** [comment]
Ciao! Ti ho aggiunto al gruppo Telegram degli sviluppatori e tecnici che stanno lavorando al progetto. Nel frattempo, guardati [attorno](https://github.com/emergenzeHack/covid19italia/issues) e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare fammelo sapere :)
