### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by agofilo** [emergenzeHack/covid19italia#44]
Telegram profile: 
agofilo

Thank you!

**Comment by avivace** [comment]
Ciao @agofilo! Ti ho aggiunto al gruppo Telegram degli sviluppatori e tecnici che stanno lavorando al progetto. Nel frattempo, guardati attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare fammelo sapere :)
