### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by marcomb** [emergenzeHack/covid19italia#45]
marcomb

**Comment by avivace** [comment]
Ciao @marcomb! Ti ho aggiunto al gruppo Telegram degli sviluppatori e tecnici che stanno lavorando al progetto. Nel frattempo, guardati attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare faccelo sapere :)
