### ISSUE TITLE
Manca il luogo nella form chiedi aiuto

### ISSUE THREAD

**Issue by tailot** [emergenzeHack/covid19italia#46]
Nella form "chiedi aiuto" https://ee.humanitarianresponse.info/x/#aozLp5mz manca l'informazione riguardante il luogo
https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/15

**Comment by avivace** [comment]
Puoi aprire qui? https://github.com/emergenzeHack/covid19italia_form
