### ISSUE TITLE
Kobo iframe too large

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#463]
**Priorità**: alta

## Richiesta
Emmbedding IFRAME of KOBO in greeek branch we have too many "empty spaces" ;-)
https://gr.covid19people.help/anebase-pliroforia/%CE%B4%CF%89%CF%81%CE%B5%CE%AC-%CE%B1%CE%B3%CE%B1%CE%B8%CF%8E%CE%BD-%CF%85%CF%80%CE%B7%CF%81%CE%B5%CF%83%CE%B9%CF%8E%CE%BD
In Italian version everything is good. WHy?
## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by dchatzoglou** [comment]
The same problem is with Portugal's webforms.

**Comment by avivace** [comment]
@olistik Can you help us on this?

**Comment by olistik** [comment]
@avivace I'll do my best. 🙂
When I load the link I get an Nginx error page.
Is there another working link available?

**Comment by avivace** [comment]
It should be back online

**Comment by olistik** [comment]
@avivace Unfortunately I still see an error:

<img width="495" alt="Screenshot 2020-04-11 at 17 18 26" src="https://user-images.githubusercontent.com/21038/79047689-86bfd680-7c18-11ea-884b-337f238ba9aa.png">

[link](https://gr.covid19people.help/anebase-pliroforia/%CE%B4%CF%89%CF%81%CE%B5%CE%AC-%CE%B1%CE%B3%CE%B1%CE%B8%CF%8E%CE%BD-%CF%85%CF%80%CE%B7%CF%81%CE%B5%CF%83%CE%B9%CF%8E%CE%BD)

Also:

<img width="981" alt="Screenshot 2020-04-11 at 17 22 11" src="https://user-images.githubusercontent.com/21038/79047770-0c438680-7c19-11ea-9f6d-ba253051e3bf.png">

[link](https://gr.covid19people.help/anebase-pliroforia/fundraising/)

Is this expected?
Do you think it's related? 🤔

**Comment by avivace** [comment]
@dchatzoglou Any idea about this?

**Comment by iltempe** [comment]
now it's seems work.

**Comment by dchatzoglou** [comment]
No idea about the error and I havent touched the forms. I have only added the hyperlink a couple of minutes ago. Sorry, i have to link the issues witn an email notification to respond quickly. Still two forms have the 404 error. It seems the ones that have a Greek hyperlink. The second and the fourth, 
here, https://gr.covid19people.help/anebase-pliroforia/

**Comment by dchatzoglou** [comment]
The forms are back and all the links are functional. The lots of space below remains.

**Comment by iltempe** [comment]
@olistik but for italian version how we hade removed blank space?

**Comment by avivace** [comment]
@olistik can you help us on this?

**Comment by olistik** [comment]
@iltempe @avivace Sorry for te delay. We arbitrarily set the height to a value so that forms could fit vertically.

**Comment by olistik** [comment]
@avivace @iltempe Could you provide a working link showing the undesired behavior?

**Comment by olistik** [comment]
You can see in this example:

https://github.com/emergenzeHack/covid19italia/blob/master/_segnalazioni/chiedi-aiuto.html#L8

That we're using a CSS class to set the height of the iframe: `iframe-embed--v200`. This class is defined here: https://github.com/emergenzeHack/covid19italia/blob/6e47f1713dd56237db6f58cf85850f5c1439b6b5/css/responsive_iframes.css#L8

This class has worked fine so far but if we need to adjust a specific iframe, we can create new classes and put them in the required context.

**Comment by iltempe** [comment]
https://www.covid19italia.help/segnala/chiedi-aiuto/

**Comment by olistik** [comment]
@iltempe @avivace Please take a look at #526 to verify if the proposed solution solves the issues.
I created a CSS class for each page so that every iframe fits nicely.

**Comment by iltempe** [comment]
@olistik is possible to pull request also on gr_branch and pt_branch? Thanks

**Comment by dchatzoglou** [comment]
Excellent, it works for the gr branch forms. thank you all

**Comment by avivace** [comment]
Thank you @olistik !

**Comment by iltempe** [comment]
i close. thanks @olistik !
