### ISSUE TITLE
Need to update schema markup in portugal branch

### ISSUE THREAD

**Issue by Pinzauti** [emergenzeHack/covid19italia#468]
As it can be seen from [here](https://github.com/emergenzeHack/covid19italia/blob/lang_pt/index.html) the JSON-LD is still the same as the italian branch. It should be translated and updated with the new links.
A complete list of where the markup was applied is visible here: https://github.com/emergenzeHack/covid19italia/pull/324/.

**Comment by iltempe** [comment]
@Pinzauti fatto?

**Comment by Pinzauti** [comment]
Nope, anzi andrebbe fatto anche sulla versione in greco.

**Comment by iltempe** [comment]
te lo assegno?

**Comment by Pinzauti** [comment]
Non posso farlo perché se vedi è necessario tradurre nelle rispettive lingue
