### ISSUE TITLE
Estrarre casi di infezioni asintomatiche.

### ISSUE THREAD

**Issue by tailot** [emergenzeHack/covid19italia#47]
Dalle varie mappe che circolano in rete non emerge il valore dei casi di infezione senza sintomi (asintomatici). Capire da chi ha creato le mappe, dai dati in rete e/o da segnalazioni in che percentuale questi casi si manifestano. Essendo una malattia nuova probabilmente si potrebbe escludere l'iniziale l'immunità di gregge https://it.wikipedia.org/wiki/Immunit%C3%A0_di_gregge (fallisce se ci si può riammalare), avere il dato degli asintomatici risulterebbe molto importante.

**Comment by tailot** [comment]
Effettuata richiesta a pcm-dpc https://github.com/pcm-dpc/COVID-19/issues/106

**Comment by iltempe** [comment]
chiudo?
