### ISSUE TITLE
Cannot add Greek characters at Kobo forms

### ISSUE THREAD

**Issue by dchatzoglou** [emergenzeHack/covid19italia#480]
As you can see from the image, we cannot add a Greek character to the Data Columnn Name. when you try to save it show an _ sign. If you type English or latin characters it works.

![image](https://user-images.githubusercontent.com/62565862/78842394-85b85a80-7a08-11ea-8a61-ed50f628b04d.png)

**Comment by favoeva** [comment]
try to comment here @dchatzoglou

**Comment by dchatzoglou** [comment]
It would be ideal if we could add Greek text.

**Comment by favoeva** [comment]
> It would be ideal if we could add Greek text.

let's ask devs if this is possible @mfortini @iltempe @avivace ;)

**Comment by avivace** [comment]
This is related to Kobo and we can't help more than Google on that.. Apparently the "Column Name" has to be plain characters.. We can however add a "mapping mechanism" on the top of that

**Comment by dchatzoglou** [comment]
I will do a search as well..

**Comment by iltempe** [comment]
@dchatzoglou is solved or not?

**Comment by dchatzoglou** [comment]
I have used Latin characters and then translated on Green at GitHub issue. We can close the issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
