### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by nicoloalabastro** [emergenzeHack/covid19italia#49]
nicoloalabastro

Thanks!

**Comment by iltempe** [comment]
ciao che skill hai?

**Comment by nicoloalabastro** [comment]
Full stack developer, BE Java FE angularjs/angular
Più info: nicoloalabastro.com

**Comment by iltempe** [comment]
hai un account telegram?

**Comment by nicoloalabastro** [comment]
Si! Avevo lasciato il nickname: nicoloalabastro
Grazie!
