### ISSUE TITLE
github2CSV.py: fetch only modified issues

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#492]
scripts/github2CSV.py is fetching all issues everytime. This leads to a lot of API calls.
There's a parameter, "since" which allows to fetch only issues modified since some time (
Change the script behavior to get only those and update _data/issues.csv _data/issuesjson.json _data/issues.geojson instead of rewriting them completely

> Only issues updated at or after this time are returned. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.

**Comment by avivace** [comment]
Should we move this script to the backend repo?

**Comment by trampfox** [comment]
Hi, I would like to take a shot on this if no one else is working on this issue.

**Comment by avivace** [comment]
Hi @trampfox 
Sure, go ahead! If you need any help or clarification don't hesitate to ask (here or on Slack)
