### ISSUE TITLE
Link diretto in homepage moduli autodichiarazione aggiornati

### ISSUE THREAD

**Issue by Marethyu6** [emergenzeHack/covid19italia#497]
**Priorità**: media (?)

## Richiesta

Inserire collegamento diretto in homepage ai moduli autodichiarazione per gli spostamenti aggiornati, almeno all'ultimo del 26 Marzo, e agli altri che (pur sperando di no) verranno. 

Non mi sembra che ci sia tra i vari 'bottoni' della homepage e penso possa essere utile. 

Ho provato a cercare nelle issue se questa cosa fosse già stata proposta, e ce n'era solo una chiusa sulla creazione di un modulo compilabile online, dunque non penso sia relativa. 
L'idea mi è sorta nel momento in cui, dovendo uscire di casa e trovandomi davanti a svariati moduli circolati a caso o già datati, ho capito che il metodo più sicuro è andare a prescindere a scaricare l'ultimo modulo pubblicato sul sito ufficiale del governo. 
Detto questo, in pratica sarebbe da aggiungere un 'bottone' in homepage con il titolo "Modulo Autocertificazione" che faccia entrare in una pagina con la breve indicazione scritta di cliccare sul link indicato sotto (quello del governo) e magari uno screenshot della pagina del governo che segnala in freccia rossa e ovale la zona della pagina dove c'è il link cliccabile per il modulo scaricabile (sarebbe forse ottimale separare le indicazioni tra "Da computer" e "Da smartphone").

Allego screenshot di quello che immaginavo:
![Example_for_HelpCovid19Italia help-github_issue1](https://user-images.githubusercontent.com/62665165/79054100-77558300-7c42-11ea-9c05-41d489883620.jpg)

Se questa proposta è ridondante, impraticabile o comunque sia non di aiuto chiudetela pure senza esitare (abbiamo tutti da fare e lo capisco), ma sarei felice di avere una breve spiegazione... 

P.S.: Grazie di tutto!! 

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by iltempe** [comment]
ciao @Marethyu6 capisco il tuo problema nel cercare rapidamente la documentazione ma nel nostro progetto cerchiamo di non sovrapporci ai siti istituzionali. Anche perchè saremmo costretti a tenere aggiornati i moduli di autocertificazione e monitorare costantemente la documentazione istituzionale...il rischio di avere documenti non aggiornati è alto e sarebbe fuorviante. Stiamo invece cercando di riorganizzare la sezione fonti istituzionali in modo da riferire i siti istituzionali dove si possa trovare questi documenti. chiedo a @cristigalas e @chiccap se possono fare un controllo nella sezione delle fonti istituzionali se abbiamo un issue relativa ai moduli di autocertificazione con un LINK. grazie

**Comment by cristigalas** [comment]
@iltempe in Fonti Istituzionali ci sono tutte le varie edizioni del modulo fino all’ultimo del 26 marzo scorso ma per trovarlo bisogna passare al motore di ricerca in home. Questa come sai è una pagina da sistemare, perché cosi è poco consultabile...

**Comment by Marethyu6** [comment]
Vi ringrazio per le risposte, capisco la problematica e le motivazioni, spero che riusciate a trovare una soluzione per la consultabilità delle pagine (alla quale purtroppo io non potrei aiutare con le mie attuali capacità...)

**Comment by iltempe** [comment]
chiudo io. la pagina dobbiamo sistemarla...work in progress.  grazie a tutti.
