### ISSUE TITLE
Segnalazione Doppia Regione 

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#505]
**Priorità**: bassa

## Richiesta
Lavorando alle API del sito noto che c'è una segnalazione con questi campi
{
Comune: "Arquata del Tronto",
Posizione: "42.7723609 13.2965826 0 0",
Provincia: "Ascoli Piceno",
Regione: "Marche",
chi: "Comitato San Mamiliano",
comune: "Isola del Giglio",
contatti: "Stefania 3290245553, Filippo 3286934513, Fabio 3338179662, Andrea 3402612926",
descrizione: "commisioni (alimenti e farmaci)",
destinatari: "anziani e malati",
fonte: "https://www.ilgiunco.net/2020/03/10/la-solidarieta-ai-tempi-del-coronavirus-sono-michele-del-terzo-piano-se-volete-vado-a-farvi-la-spesa/",
provincia: "Grosseto",
regione: "Toscana",
tag: "Consegne e commissioni"
}

Perchè il campo regione è doppio? e perchè è diverso?
Idem per il campo Provincia 
Grazie

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by favoeva** [comment]
https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/124
