### ISSUE TITLE
Aggiungere Servizi e Iniziative Solidali nel titolo pagina “Migranti e Rifugiati”

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#512]
Per rendere più chiara la pagina dedicata a [Migranti e Rifugiati](https://covid19italia.help/migranti-rifugiati/), propongo di modificare il titolo così: **Servizi e iniziative solidali per migranti e rifugiati** (del resto un po’ tutte le pagine hanno un titolo più esplicativo). Oppure _Migranti e Rifugiati - Servizi e Iniziative solidali_. Ovviamente label, bottone e link rimangono lì stessi che ci sono adesso. 
Che ne dite @mfortini @Saraveg?

**Comment by mfortini** [comment]
Per me ok

**Comment by iltempe** [comment]
fatto. tra qualche minuto online.
