### ISSUE TITLE
Home page on mobile

### ISSUE THREAD

**Issue by dchatzoglou** [emergenzeHack/covid19italia#516]
Dear friends,

if you open the Greek version on a mobile it hides half of the page title. It makes blue navigation bar bigger and the menu drop-down is left instead of right as the italian one.
![image](https://user-images.githubusercontent.com/62565862/79264816-d4994080-7e9d-11ea-8feb-352af98dc0ca.png)

**Comment by iltempe** [comment]
@Pinzauti ci dai una mano su questo?

**Comment by iltempe** [comment]
@dchatzoglou is it ok now?

**Comment by dchatzoglou** [comment]
It is perfect! thank you so much for the quick fix. You saved my life.
