### ISSUE TITLE
Home page portogallo - link icona "relatorios" non funziona

### ISSUE THREAD

**Issue by robertoCib** [emergenzeHack/covid19italia#517]
**Priorità**: media

## Richiesta
nella versione portoghese, in home page il link relativo alla grande icona "relatorios" non funziona. Sembra un errore legato ad un accento nel permalink. Solo che lo stesso permalink nella barra di navigazione funziona.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by iltempe** [comment]
è a posto. chiudo.
