### ISSUE TITLE
Add members to moderating team

### ISSUE THREAD

**Issue by dchatzoglou** [emergenzeHack/covid19italia#519]
Can you please add the below Github accounts to the Greek moderating team so they can edit gr issues?

dimitris-actionaid
machi-actionaid
angelina-actionaid

**Comment by dchatzoglou** [comment]
i am sorry for the urgent label, as we are going live today and we have a lot of issues to edit. thanks

**Comment by dchatzoglou** [comment]
now, they can access the gr issues but still they cannot edit.

**Comment by favoeva** [comment]
You need to ask @mfortini to have the mantainer credentials for the issues on github and be able to manage labels

**Comment by dchatzoglou** [comment]
machi-actionaid and dimitris-actionaid can edit fine. Still, angelina-actionaid has login issues even if she has accepted the invitation..

**Comment by dchatzoglou** [comment]
As the problems persists, i have added angelina with a new username. she has verified her account and please add her on Greece editors team. Her Github account is atsakiri-actionaid.

**Comment by avivace** [comment]
We should be good now
