### ISSUE TITLE
Label Bollettino 

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#52]
Su TCI abbiamo sempre usato una label Bollettino che se veniva messa su un ISSUE allora abilitavamo l'invio della notizia su Telegram e Twitter in automatico. Che dite?

**Comment by favoeva** [comment]
Funzionava bene e facilitava di molto il lavoro sui social

**Comment by cristigalas** [comment]
Da fare assolutamente! Occhio però che se attiviamo bollettino dobbiamo scrivere i titoli delle issue in modo che siano leggibili in un tweet...

**Comment by favoeva** [comment]
Giusto! @cristigalas ci ricordi quanti caratteri max?

**Comment by cristigalas** [comment]
Se pensiamo a Twitter direi che il massimo è 240 ma dobbiamo lasciare spazio per link e hashtag... anzi dobbiamo decidere che hashtag usare. Apro issue.
