### ISSUE TITLE
Update lunr.js to get search in all languages

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#522]
Search is not working for Greek. The lunr version we're using had problems with utf-8
Replace lunr with the newest release or another js search engine.

**Comment by iltempe** [comment]
segnalo questo. https://github.com/olivernn/lunr.js/issues/232

**Comment by mfortini** [comment]
I just pushed a version for Greek language I took from the minimal-mistakes project https://github.com/mmistakes/minimal-mistakes
The query function they use might be useful for other languages, too

**Comment by dchatzoglou** [comment]
I have tested with a couple of queries and it seems to be working.

**Comment by iltempe** [comment]
ok so can we close?

**Comment by dchatzoglou** [comment]
I think, yes, we can close.. thanks
