### ISSUE TITLE
Fabebook link

### ISSUE THREAD

**Issue by dchatzoglou** [emergenzeHack/covid19italia#523]
Hi again,

When we click to share a post on Facebook, it keeps the below image that is related to actionaid italia. How can we change that? 
![image](https://user-images.githubusercontent.com/62565862/79338373-d875a300-7f2f-11ea-8ca2-f98f5271909f.png)

**Comment by iltempe** [comment]
yes this is cause you have to update the reference to your logo (if you have one). Put the logo in png format in "image" folder and then update the "/images/covid19italia-full.png" links in the head.html file (see lines 85 and 91). let me know if you need an hand.

**Comment by iltempe** [comment]
done by @dchatzoglou . it's ok.
