### ISSUE TITLE
Apertura pagina Linkedin

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/covid19italia#525]
Ciao!

Abbiamo accennato all'apertura di una pagina Linkedin anche per facilitare la gestione delle richieste di aiuto rivolte ad aziende.
Che ne pensate?

@cristigalas @iltempe @Albertopi78 @luciaroma @favoeva

**Comment by luciaroma** [comment]
Potrebbe valere la pena tentare in effetti ... costo 0? se no forse va fatto un pensiero costi/benefici

**Comment by cristigalas** [comment]
Nessun costo. Ecco qui https://www.linkedin.com/company/covid19italia-help/
Ho aggiunto come amministratori della pagina @favoeva @chiccap e @Albertopi78. Se qualcun’altro vuole lo aggiungo. Domani provo a fare il primo post con una richiesta di aiuto...

**Comment by chiccap** [comment]
Potremmo provare con la richiesta del Mondino #2385. nella issue ho inserito le aziende già contattate via mail potremmo provare con le stesse via LinkedIn?

**Comment by cristigalas** [comment]
> Potremmo provare con la richiesta del Mondino: [emergenzeHack/covid19italia_segnalazioni#2385](https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/2385). nella issue ho inserito le aziende già contattate via mail potremmo provare con le stesse via LinkedIn?

Ok! Intanto qui chiudo.

**Comment by cristigalas** [comment]
@iltempe potresti, per favore, inserire tra i canali di comunicazione sul sito anche LinkedIn? Qui il link https://www.linkedin.com/company/covid19italia-help/
Grazie!
