### ISSUE TITLE
Import punti sanimapp

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#531]
Il GRIS - Gruppi immigrazione e Salute della Società Italiana di Medicina ha condiviso con noi una mappatura (la Sanimapp) dei presidi sanitari aperti a Roma e nel Lazio

Sono più di 160 punti che potremmo importare in modo automatico, con testo e coordinate.

Che licenza hanno? Li importiamo?

**Comment by iltempe** [comment]
tecnicamente importabili subito. per me ok ad importarli. L'unica cosa chiederei a chi ce li ha forniti la licenza e se non ce l'hanno, se possiamo apporre licenza CC BY  (in sostanza se possiamo ricondividerli rilasciandoli come tutti gli altri dati).

**Comment by mfortini** [comment]
Si stanno informando sulle licenze.

**Comment by mfortini** [comment]
Stefano "Kenji" Iannillo di ARCI ha confermato che possiamo importare come CC-BY

**Comment by mfortini** [comment]
![image](https://user-images.githubusercontent.com/1104926/79968915-11ae9580-8491-11ea-93b0-919d4c7649ed.png)
Questi i dati contenuti

**Comment by mfortini** [comment]
Esempio di issue creata automaticamente https://www.covid19italia.help/issues/2582/

**Comment by mfortini** [comment]
I servizi disponibili sono 'Rilascio STP/ENI ', 'Ambulatorio di medicina generale',
       'Rilascio STP/ENI e Ambulatorio di medicina generale'

**Comment by cristigalas** [comment]
Riporto qui mio commento su Slack:

_Mah non è che sia molto chiara, a partire dal titolo... secondo me è necessario aggiungere un titolo più chiaro e un campo descrizione dove inseriamo un testo di spiegazione, che può essere anche standard e uguale per tutti. Tu devi immaginare che, ad esempio, un utente ne intercetta una e non sa che ce ne sono altre 160 simili e che fa parte di un data set, ecc. e dunque quell’una deve contenere tutte le info che sono necessarie a capire che tipo di segnalazione è._

**Comment by cristigalas** [comment]
Riguardo al titolo, possiamo togliere Fonte e usarla invece come Titolo aggiungendo due paroline, tipo così: _Ambulatorio medico per migranti promosso da GRIS - Gruppi immigrazione e Salute della Società Italiana di Medicina #Roma_

E poi inseriamo a tutte sue righe di descrizione standard, ad esempio un testo tipo:  _Per l’emergenza sanitaria in corso l’ambulatorio è chiuso ma effettua servizio informativo per via telefonica ai numeri e orari indicati._ 
O qualcosa del genere che spieghi cosa sono, cosa servono e soprattutto cosa offrono ora in questa fase di emergenza.

**Comment by chiccap** [comment]
> Riguardo al titolo, possiamo togliere Fonte e usarla invece come Titolo aggiungendo due paroline, tipo così: _Ambulatorio medico per migranti promosso da GRIS - Gruppi immigrazione e Salute della Società Italiana di Medicina #Roma_
> 
> E poi inseriamo a tutte sue righe di descrizione standard, ad esempio un testo tipo: _Per l’emergenza sanitaria in corso l’ambulatorio è chiuso ma effettua servizio informativo per via telefonica ai numeri e orari indicati._
> O qualcosa del genere che spieghi cosa sono, cosa servono e soprattutto cosa offrono ora in questa fase di emergenza.

Assolutamente d'accordo, altrimenti non è chiaro. Si può fare?

**Comment by mfortini** [comment]
Proposta da Stefano "Kenji" Iannillo di ARCI: aggiungere un testo in tutte le segnalazioni di questo tipo:

Sanimapp è una app che fornisce informazioni sull’assistenza sanitaria a Roma e nel Lazio per le persone straniere sprovviste di permesso di soggiorno e per i cittadini comunitari in condizione di fragilità sociale e amministrativa, in 4 lingue, realizzata dal Gris Lazio in collaborazione con Sanità di Frontiera Onlus e Team Dev.

“Sanimapp contiene 3 sezioni:

-la mappa geolocalizzata (realizzata da parte del GrIS Lazio per conto della Regione Lazio) sull’ubicazione e gli orari degli uffici che forniscono il tesserino Stp (Stranieri temporaneamente presenti) o Eni (Europeo non iscritto) e gli ambulatori Stp/Eni.

- lo spazio per gli operatori socio-sanitari che ricorda i loro doveri nei confronti delle persone immigrate, anche se prive di permesso di soggiorno o altri titoli per accedere al Ssn.

-lo sportello digitale, che rimanda al sito della Società Italiana di Medicina delle Migrazioni (S.I.M.M.), dedicato alla normativa nazionale e alle norme della Regione Lazio che garantisce l’assistenza sanitaria alla popolazione straniera e alle indicazioni per la gestione delle problematiche della tutela della salute che possano presentare in particolare le persone straniere vittime di tortura o di violenza o le donne che hanno subito mutilazioni genitali femminili.

**Comment by chiccap** [comment]
> Sanimapp è una app che fornisce informazioni sull’assistenza sanitaria a Roma e nel Lazio per le persone straniere sprovviste di permesso di soggiorno e per i cittadini comunitari in condizione di fragilità sociale e amministrativa, in 4 lingue, realizzata dal Gris Lazio in collaborazione con Sanità di Frontiera Onlus e Team Dev.
> 
> “Sanimapp contiene 3 sezioni:
> 
> -la mappa geolocalizzata (realizzata da parte del GrIS Lazio per conto della Regione Lazio) sull’ubicazione e gli orari degli uffici che forniscono il tesserino Stp (Stranieri temporaneamente presenti) o Eni (Europeo non iscritto) e gli ambulatori Stp/Eni.
> 
> * lo spazio per gli operatori socio-sanitari che ricorda i loro doveri nei confronti delle persone immigrate, anche se prive di permesso di soggiorno o altri titoli per accedere al Ssn.
> 
> -lo sportello digitale, che rimanda al sito della Società Italiana di Medicina delle Migrazioni (S.I.M.M.), dedicato alla normativa nazionale e alle norme della Regione Lazio che garantisce l’assistenza sanitaria alla popolazione straniera e alle indicazioni per la gestione delle problematiche della tutela della salute che possano presentare in particolare le persone straniere vittime di tortura o di violenza o le donne che hanno subito mutilazioni genitali femminili.

Per il titolo lascerei valida la proposta di @cristigalas con però #Lazio.

Per il testo lo alleggerirei così:
La segnalazione deriva dalla colaborazione con Sanimapp, una app che fornisce informazioni sull’assistenza sanitaria a Roma e nel Lazio per le persone straniere sprovviste di permesso di soggiorno e per i cittadini comunitari in condizione di fragilità sociale e amministrativa, in 4 lingue, realizzata dal Gris Lazio in collaborazione con Sanità di Frontiera Onlus e Team Dev.
+ link alla appa da scaricare e alla mappa

**Comment by cristigalas** [comment]
Secondo me quel testo, anche nella versione alleggerita non va bene. Nella segnalazione (vedi [esempio qui](https://www.covid19italia.help/issues/2582/) compare un numero di telefono e degli orari ed è questa informazione che bisogna spiegare e contestualizzare, ovviamente in tre righe. Poi mettiamo questo link a mappa+app per ulteriori info https://www.sanitadifrontiera.org/sanimapp/index.html?l=it

**Comment by Saraveg** [comment]
Scusate non ho capito....ma non possiamo inserire in mappa tutti i punti che ci hanno dato? siamo ok con la licenza ed è utile che siano segnalati i presidi sanitari!
Io propongo di inserire in mappa tutti con questa dicitura:


**titolo**: Ambulatorio medico per migranti promosso da GRIS - Gruppi immigrazione e Salute della Società Italiana di Medicina #Roma #Lazio

**testo**: Presidio sanitario per l'assistenza sanitaria a Roma e nel Lazio per le persone straniere sprovviste di permesso di soggiorno e per i cittadini comunitari in condizione di fragilità sociale e amministrativa, in 4 lingue, realizzata dal Gris Lazio in collaborazione con Sanità di Frontiera Onlus e Team Dev.

All'interno di Sanimapp puoi trovare:


-la mappa geolocalizzata (realizzata da parte del GrIS Lazio per conto della Regione Lazio) sull’ubicazione e gli orari degli uffici che forniscono il tesserino Stp (Stranieri temporaneamente presenti) o Eni (Europeo non iscritto) e gli ambulatori Stp/Eni.

  - lo spazio per gli operatori socio-sanitari che ricorda i loro doveri nei confronti delle persone immigrate, anche se prive di permesso di soggiorno o altri titoli per accedere al Ssn.

-lo sportello digitale, che rimanda al sito della Società Italiana di Medicina delle Migrazioni (S.I.M.M.), dedicato alla normativa nazionale e alle norme della Regione Lazio che garantisce l’assistenza sanitaria alla popolazione straniera e alle indicazioni per la gestione delle problematiche della tutela della salute che possano presentare in particolare le persone straniere vittime di tortura o di violenza o le donne che hanno subito mutilazioni genitali femminili.

**Comment by cristigalas** [comment]
@Saraveg Il testo che proponi è troppo lungo. Se sei d’accordo farei così:

**Titolo**: Ambulatorio medico per migranti promosso da GRIS - Gruppi immigrazione e Salute della Società Italiana di Medicina #Roma #Lazio

**Descrizione**: Presidio sanitario per l'assistenza sanitaria a persone straniere sprovviste di permesso di soggiorno e ai cittadini comunitari in condizione di fragilità sociale e amministrativa, in 4 lingue, realizzata dal Gris Lazio in collaborazione con Sanità di Frontiera Onlus e Team Dev. Per ulteriori info vai al link del progetto Sanimapp.

**Link**: https://www.sanitadifrontiera.org/sanimapp/

E poi lascerei i campi che già ci sono (toglierei solo longitudine latitudine e lo farei su tutte le segnalazioni perché c’è già Posizione, così come ci eravamo già detti con @mfortini).

**Comment by Saraveg** [comment]
@cristigalas per me è ok!

**Comment by cristigalas** [comment]
Bene! Allora @mfortini puoi procedere!

**Comment by mfortini** [comment]
Ho importato seguendo le specifiche sopra, tutte le issue sono taggate anche con la label "Sanimapp", quindi si possono anche eliminare in blocco se non dovessero andar bene

**Comment by cristigalas** [comment]
@mfortini @Saraveg @chiccap ho dato un’occhiata e ho visto che molte hanno ancora il titolo _Rilascio STP/ENI per migranti promosso da GRIS - Gruppi immigrazione e Salute della Società Italiana di Medicina_ che andrebbe sostituito con quello concordato e che in alcune appare.
Poi, secondo me, bisognerebbe trovare il modo di spalmare tutte queste segnalazioni nella pagina e non farle apparire tutte in blocco ad inizio pagina perché praticamente ‘sotterrano’ tutte le altre segnalazioni e chi arriva sulla pagina non si rende conto di cosa c’è davvero in questa sezione del sito. Oppure, mettiamole in fondo alla lista... Insomma mi inventerei qualcosa. Sembra quasi un errore, visto che praticamente sono tutte uguali...
Non so, continuo ad essere perplessa di fronte a questo tipo di operazioni.

**Comment by mfortini** [comment]
Cristina ho interpretato che il titolo fosse ambulatorio quando il servizio era quello, se in uno dei posti il servizio è solo rilascio stp/eni mi sembrava giusto mettere quello, altrimenti l'informazione è sbagliata.
Per l'ordine non saprei come fare al volo, siccome sono ordinate dalla più recente alla più vecchia

**Comment by cristigalas** [comment]
> @cristigalas ho interpretato che il titolo fosse ambulatorio quando il servizio nella tabella era quello, se in uno dei posti il servizio è solo rilascio stp/eni mi sembrava giusto mettere quello, altrimenti l'informazione è sbagliata.
> Per l'ordine non saprei come fare al volo, siccome sono ordinate dalla più recente alla più vecchia

Ok. Pensavo che tutti gli ambulatori rilasciassero il codice... vabbè lasciamo così anche se non è proprio chiarissimo.

Riguardo invece all’ordine, non possiamo mettere a tutti di default una data tipo 10 marzo, così vanno senz’altro in fondo alla pagina?

**Comment by chiccap** [comment]
> > @cristigalas ho interpretato che il titolo fosse ambulatorio quando il servizio nella tabella era quello, se in uno dei posti il servizio è solo rilascio stp/eni mi sembrava giusto mettere quello, altrimenti l'informazione è sbagliata.
> > Per l'ordine non saprei come fare al volo, siccome sono ordinate dalla più recente alla più vecchia
> 
> Ok. Pensavo che tutti gli ambulatori rilasciassero il codice... vabbè lasciamo così anche se non è proprio chiarissimo.
> 
> Riguardo invece all’ordine, non possiamo mettere a tutti di default una data tipo 10 marzo, così vanno senz’altro in fondo alla pagina?

Anche secondo me purtroppo non è chiarissimo. Anche perchè con la label stranieri compare anche in Juma map giusto? Per chi trova la segnalazione da quella mappa è ancora meno chiaro.
L'idea della data per mandarle in fondo alla pagina è ottima!
