### ISSUE TITLE
Portale portoghese - link non funzionante

### ISSUE THREAD

**Issue by robertoCib** [emergenzeHack/covid19italia#533]
**Priorità**: bassa

## Richiesta
 nella pagina delle segnalazioni ([relatorios](https://pt.covid19people.help/relat%C3%B3rios/)) il link corrispondente a "[comunique entrega ao domicilio](https://pt.covid19people.help/relatorios/domic%C3%ADlio)" non funziona, probabilmente a causa della presenza di un carattere particolare nel permalink. provato a dare un'occhiata a segnala.md ma non sono riuscito a capire il problema. Grazie.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by iltempe** [comment]
è a posto adesso.
