### ISSUE TITLE
Issue risolte label e sito

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/covid19italia#536]
Ciao!

Abbiamo iniziato a parlare di inserire label risolta/non più attiva che possa essere visualizzata anche sul sito - diverso da chiusa.
Possiamo preocedere?

**Comment by iltempe** [comment]
Proposte? In che modo la vogliamo visualizziamo sul sito?

**Comment by mfortini** [comment]
Dopo il meet di sabato 18 Aprile dove abbiamo chiarito un po' l'implementazione, ho inserito una label 'Risolta'. Vedi ad esempio https://www.covid19italia.help/issues/2332/

**Comment by chiccap** [comment]
A me piace! Che ne dici @cristigalas ?

**Comment by cristigalas** [comment]
@chiccap @mfortini secondo me va bene ma come compare la scritta risolta nell’elenco delle segnalazioni di una certa categoria o che si genera con una ricerca?

**Comment by chiccap** [comment]
Sì hai ragione, si può fare?
