### ISSUE TITLE
Passare da Disqus a Facebook per i commenti sulle issue

### ISSUE THREAD

**Issue by Pinzauti** [emergenzeHack/covid19italia#537]
**Priorità**: bassa

## Richiesta
Per aumentare l'interazione sulle segnalazioni tramite i commenti sul sito proporrei di cambiare piattaforma passando da Disqus a Facebook che ha il plus di sincronizzare i commenti del post sulla pagina Facebook con la sezione commenti della segnalazione sul sito. Inoltre non richiederebbe agli utenti di creare un nuovo account in quanto più o meno tutti hanno un account Facebook.

**Comment by iltempe** [comment]
io sono favorevole ma ho due domande:
- dobbiamo avere account developer facebook o basta la pagina facebook?
- cosa viene visualizzato esattamente sulla pagina Facebook? 

@Albertopi78 dicci la tua.

**Comment by Pinzauti** [comment]
> * dobbiamo avere account developer facebook o basta la pagina facebook?

È necessario l'account developer.
> * cosa viene visualizzato esattamente sulla pagina Facebook?

Nel momento in cui posti una issue su Facebook i commenti sul post e i commenti sul box della pagina della issue vengono sincronizzati.

Comunque in realtà anche con Facebook sono sicuro l'interazione rimarrà bassa, tuttavia non essendo una modifica che richiede troppo sforzo può essere un plus in più.

**Comment by favoeva** [comment]
domanda  @Pinzauti : le nostre risposte ai commenti su fb  andrebbero anche come commenti sulla issue Github?

**Comment by Pinzauti** [comment]
Nope su GitHub no

**Comment by favoeva** [comment]
Quindi rischieremmo di avere un pezzo di storia della issue solo su Fb o solo su github. 😕

**Comment by Pinzauti** [comment]
Tramite le API Facebook forse è possibile fare qualcosa, comunque anche adesso i commenti Disqus e Github non vengono sincronizzati
