### ISSUE TITLE
Aggiornare sezione wiki "Diventa contributore"

### ISSUE THREAD

**Issue by trampfox** [emergenzeHack/covid19italia#541]
**Priorità**: bassa

## Richiesta
Aggiornare la sezione `Diventa un contributore` nella pagina https://www.covid19italia.help/wiki/, dove si dice di aprire una issue per l'iscrizione fornendo lo username Telegram. 

Si potrebbe mettere un link a [questa](https://www.covid19italia.help/canali/) pagina, come mi è stato detto nella issue #538.

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by iltempe** [comment]
dovrebbe essere a posto adesso. controlla tra pochi minuti, il tempo di buildare il sito.

**Comment by iltempe** [comment]
fatto.
