### ISSUE TITLE
Forms from site dont generate an issue on Github

### ISSUE THREAD

**Issue by dchatzoglou** [emergenzeHack/covid19italia#549]
When you try and upload something choosing a form https://covid19greece.help/anebase-pliroforia/entertainment/, it doesnt generate an issue on Github.

**Comment by dchatzoglou** [comment]
Please, forget it. It takes more time to generate the issue and I was afraid that it was not working.

**Comment by Pinzauti** [comment]
I'm gonna close this then, feel free to reopen it if something goes wrong.
