### ISSUE TITLE
Il logo e il nome sito collidono ad un viewport medio (>960px)

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia#56]
![image](https://user-images.githubusercontent.com/14352721/76368734-825e8000-6331-11ea-8ab0-f9fa93c1e4da.png)

**Comment by tailot** [comment]
@avivace se va bene così il @iltempe  fa una chiusura della issue!

**Comment by iltempe** [comment]
chiudo

**Comment by avivace** [comment]
Grazie @tailot 🎉  , va benissimo!
