### ISSUE TITLE
Link utili FASE 2

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/covid19italia#566]
Ciao!

A questo [link ](https://www.finpiemonte.it) troviamo vari bandi e interventi per sostenere lavoro e imprese in Piemonte. 
L'inserimento di questa tipologia di bandi potrebbe essere una delle strategie per lo sviluppo delle informazioni nella piattaforma in Fase 2.

Ci diamo un ordine per inserire delle nuove segnalazioni con le info di questa piattaforma?

@cristigalas @luciaroma @favoeva

**Comment by cristigalas** [comment]
@chiccap da quel sito piemontese ho già inserito qualcosa io... è un sito che varie sezioni, non proprio chiaro, bisogna un po’ navigarlo... comunque io direi p, prima di inserire qualcosa, di verificare sempre bene che non ci sia già.

Bisognerebbe capire se esistono siti simili anche per altre regioni, almeno quelle più colpite... innanzitutto Lombardi, Veneto e EmiliaR.

**Comment by Saraveg** [comment]
Trasferiamo tutte questo tipo di informazioni in altra issue
