### ISSUE TITLE
Miglioramento pagina RACCOLTE FONDI

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/covid19italia#568]
@luiciaroma cosigliava di mettere un pochino in ordine la pagina Raccolte Fondi. 
Infatti ad oggi è possibile visualizzarle su mappa e in elenco da scorrere sono davvero tante e di tutte le diverse tipologie senza una distinzione. 
Potremmo invece darne una visualizzazione più semplice con possibilità di filtro per macro categorie es. strutture ospedaliere, associazioni, etc... anche in vista della collaborazione con Italia Non Profit (issue #377)

Che ne pensate? @cristigalas @avivace @mfortini @favoeva

**Comment by mfortini** [comment]
È una cosa "facile", bisogna soltanto però mettere le label per categorizzarle

**Comment by cristigalas** [comment]
@mfortini @chiccap se è facile e serve ‘solo’ mettere label, allora mettiamo su una squadra e lo facciamo. Che dite? Secondo me sarebbe molto utile. Nel caso come categorizziamo? Per causa, beneficiari o promotori? Direi per beneficiari, tipo:

- Ospedali e aziende sanitarie 
- Associazioni ed enti non profit
- Comuni, Regioni, enti pubblici
- Università e scuole

Che ne dite?

**Comment by mfortini** [comment]
Allora, direi così: raccolte fondi resta label per la categoria altrimenti tutto si rompe.
Poi si definiscono "sotto label" tipo rf/Ospedali
rf/....

**Comment by chiccap** [comment]
Ah ma che belle le cose semplici @mfortini ! Ok lasciare label raccolte fondi. 
Per me le sotto-categorie beneficiari evidenziate da @cristigalas vanno benissimo, se eventualmente nella categorizzazione dovessimo trovarne altre le aggiungiamo. 
Scrivo su editors per la task force :)

**Comment by chiccap** [comment]
Davanti alle nuove label delle dotto-categorie ho inserito la sigla "RF" come riferimento alle raccolte fondi. Se non è chiaro modifichiamo!

**Comment by michelerestuccia** [comment]
Nelle raccolte fondi i cui beneficiari sono soggetti quali Caritas e Croce Rossa, metto label 'Ospedali e aziende sanitarie' oppure 'Associazioni ed enti non profit'? 
Dal mio punto di vista, essendo queste donazioni finalizzate ad attività sanitaria, userei la prima label (ospedali)... @cristigalas @chiccap @mfortini  @favoeva

**Comment by chiccap** [comment]
@michelerestuccia io metterei associazioni e enti non profit ma decidiamolo insieme @cristigalas @luciaroma

**Comment by luciaroma** [comment]
Sì teniamo "Associazioni ed enti non profit" perchè di fatto sono loro i titolari della raccolta fondi

**Comment by luciaroma** [comment]
invece le raccolte fondi delle Fondazioni Ospedaliere, le mettiamo sempre sotto Ospedali e Aziende ospedaliere? @cristigalas @chiccap

**Comment by cristigalas** [comment]
Se partiamo dai beneficiari e non dai promotori della raccolta fondi, allora procederei così: quando i beneficiari sono associazioni/non profit usiamo etichetta Associazioni. Cioè se chiedono i fondi per potenziare le proprie attività di associazioni a supporto dell’emergenza allora usiamo etichetta Associazioni. Se invece chiedono i soldi per sostenere gli ospedali allora usiamo etichetta Ospedali. Non so se mi sono spiegata. La ragione della raccolta fondi è fondamentale, quindi un occhio alla descrizione va dato prima di mettere la label.

Per i privati (singoli) stessa cosa. Se Cristina raccoglie fondi, come cittadina, per l’ospedale di Livorno, va sotto ospedali. Questa etichetta vale anche per le fondazioni ospedaliere o medico-sanitarie.

Per rispondere a @luciaroma: Rotary è un ente non profit, enti privati è una definizione generica che non spiega la ragione sociale che è quella che ci interessa, cioè profit/non profit. 

Per Protezione Civile Nazionale ha ragione @michelerestuccia: è ente pubblico. Per le protezioni civili locali dobbiamo valutare per chi raccolgono i fondi: per se stesse e allora usiamo label Associazioni o per Ospedali, ecc. 

Comunque in caso di dubbi ci consultiamo al volo su Slack/Editor.

**Comment by luciaroma** [comment]
tutto chiaro, in effetti mi era poi venuto questo dubbio nel mentre che le facevo e che avesse ragione @michelerestuccia .
Grazie
procedo così intanto

**Comment by chiccap** [comment]
Attenzione però perché enti come croce rossa e Caritas ad esempio (nell’ultimo mese) spesso fanno raccolte fondi non per ospedali ma cibo o denaro per associazioni non profit! Facciamo sempre riferimento ai beneficiari come dice @cristigalas

**Comment by luciaroma** [comment]
> È una cosa "facile", bisogna soltanto però mettere le label per categorizzarle

Quindi, una volta categorizzate tutte le raccolte fondi con le sotto-etichette, verranno visualizzate in elenchi differenti anche in frontend? oppure serve comunque lavoro aggiuntivo per la visualizzazione per sotto categorie nella pagina raccolte fondi? @mfortini

**Comment by michelerestuccia** [comment]
Bene, grazie per il chiarimento a tutte!

**Comment by chiccap** [comment]
Chiuderei, grazie a tutte e tutti!
