### ISSUE TITLE
covid19greece.help not working

### ISSUE THREAD

**Issue by dchatzoglou** [emergenzeHack/covid19italia#574]
Dear friends, it seems that our https://covid19greece.help/ is not working. Can you help please?

Thanks

**Comment by dchatzoglou** [comment]
I want to ask for your help as still it is not working even if I have used the new IP address. The comms team is using the platform as a homework/assignment to a University in a couple of presentations. https://www.panteion.gr/en/. It is not good not to have available the URL and ask them to access the alternatives https://gr.covid19people.help/ and https://www.covid19greece.help/

**Comment by avivace** [comment]
Looks like it's working. Reopen if necessary.
