### ISSUE TITLE
Proposta Festival della Partecipazione

### ISSUE THREAD

**Issue by Saraveg** [emergenzeHack/covid19italia#575]
**Priorità**: media

## Testo della comunicazione

Care e cari
come sapete ogni anno organizziamo, insieme ad altri, il Festival della Partecipazione.
Dopo quattro anni a L'Aquila ci sposteremo nella città di Bologna e quest'anno, causa emergenza, sarà quasi del tutto online.
Tra i vari eventi avremmo pensato a questo di cui vi allego una prima bozza.

Che dite? Potrebbe essere utile? Partecipereste?

baci assai e....buon agosto!!

Domenica 18 ottobre: 
TEMA: 
Come il CIVIC HACKING agisce nelle emergenze e come può essere utile, anche all’Italia
Portiamo le esperienze di Civic hacking più avanzate a livello internazionale per confrontarsi su come l’attivismo che usa e modifica il digitale può offrire un nuovo spazio di collaborazione con comunità e istituzioni.
TIPOLOGIA EVENTO:
1,5 ora nella mattina di presentazione delle esperienze di Code for America, Code for France, Covid19Italia.help e Terremotocentroitalia.info, Covid19Greece.hel, Covid19Portogalli, Frena la Curva (es) si presentano rispondendo alla sollecitazione dei punti di forza e criticità delle diverse esperienze

A seguire
3/4 ore di 2 stanze di lavoro partecipate dalle rispettive comunità per far emergere raccomandazioni alle istituzioni su come riconoscere e agevolare i risultati del lavoro dei civic hacker e un “prontuario” per mobilitarsi nel digitale per risolvere problematiche delle comunità
2 moderatori/facilitatori
Strumenti digitali da utilizzare mentimeter, miro., mural

In chiusura o in un altro momento si riportano le conclusioni che verranno diffuse tramite sito e social. Sarebbe auspicabile una interlocuzione istituzionale con la Ministra Pisano (o Dadone?) e un ente locale (Comune di Bologna?)
PARTECIPANTI DA COINVOLGERE: 
Code for America
Code for France
Piattaforma Grecia
Piattaforma Italia
Piattaforma Portogallo
Frena la Curva in Spagna
Altri invitati da Pescare: https://civictech.guide/listing-category/civic-hacking-meetups/

**Comment by michelerestuccia** [comment]
@Saraveg io ci sono per parlarne quando torniamo operativi. Penserei anche a come coinvolgere organizzazioni ed enti che hanno usato la piattaforma, tipo CSV Messina e Lombardia, Arci etc.

**Comment by iltempe** [comment]
@Saraveg non credo di riuscire ad esserci in prima persona, ma se hai un'informativa in inglese posso girarla ai miei contatti internazionali e chiedere loro se vogliono contribuire. Sull'italia il tema lo trattano secondo me molto bene Matteo e Elena e secondo me posso dare un contributo importante.

Matteo

**Comment by Saraveg** [comment]
qui: https://drive.google.com/drive/u/2/folders/1MU48gatB_bGalVuBejLMJ4pc0PbHJ2DP
(nella cartella condivisa) concept e lettere
