### ISSUE TITLE
Aprire pdf e mappare punti tampone Regione Lombardia

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#577]
@mfortini @michelerestuccia [A questo link](https://www.lombardianotizie.online/wp-content/uploads/2020/09/PUNTI-TAMPONE-lombardia.pdf) il pdf dei punti dove è possibile effettuare il tampone in Lombardia. Purtroppo il pdf è un file immagine e non sono riuscita ad aprirlo per estrarre i dati con http://tabula.ondata.it/

**Comment by mfortini** [comment]
è normale che tabula non funzioni, si tratta di un PDF fatto di immagini e tra l'altro pertanto "non accessibile'

**Comment by mfortini** [comment]
Qui c'è la pagina con i link https://www.regione.lombardia.it/wps/portal/istituzionale/HP/DettaglioRedazionale/servizi-e-informazioni/cittadini/salute-e-prevenzione/coronavirus/gestione-casi-covid-19

ma i link pare portino alle homepage delle ATS, dove in alcuni casi non ho trovato info

**Comment by mfortini** [comment]
# ATS Bergamo

Coronavirus: Tamponi per gli studenti, docenti e non docenti A seguito della circolare prot. 0052118 del 14/09/2020 di Regione Lombardia, l’Agenzia di Tutela della  Salute  di  Bergamo  sta  organizzando,  insieme  alle  ASST,  le  modalità  per  l’esecuzione  del tampone  agli  studenti  e  al  personale  docente  e  non docente  della  scuola  che  presenteranno sintomi (soprattutto febbre a 37,5°) durante l’orario scolastico. I tamponi saranno ad accesso libero (ovvero senza prenotazione). E’ obbligatorio contattare il proprio medico curante o il pediatra prima di presentarsi all’esame. E’ obbligatorio presentarsi all’esame con l’autodichiarazione compilata e con la tessera sanitaria. Il servizio è attivo da lunedì a sabato, presso le seguenti sedi: ASST Papa Giovanni XXIII •Presidio medico avanzato della Fiera di Bergamo, da lunedì a sabato, dalle 9 alle 14. Restare in macchina e seguire le indicazioni che conducono all'ingresso riservato. •al Punto prelievi dell'Ospedale di San Giovanni Bianco,da lunedì a sabato, dalle 10 alle 14. Link al sito: http://www.asst-pg23.it/2020/09/_linea_tamponi_scuola/ASST Bergamo Ovest •Drive - Through presso l’Ospedale di Treviglio, Piazzale ospedale n°1 dalle ore 09.00 alle ore 13.00, da lunedì a sabato [attivo dal 16/09] •Presso l’Unità d’offerta di Ponte San Pietro in via Adda n. 18 al piano terra dalle ore 09.00 alle ore 13.00, da lunedì a venerdì [attivo dal 17/09] •Drive - Through a Martinengo in Via Gramsci (di fronte alla Sede degli Alpini) dalle ore 09.00 alle ore 13.00, da lunedì a venerdì [attivo dal 25/09] •Drive - Through a Dalmine in Piazzale Piscine dalle ore 09.00 alle ore 13.00,da lunedì a sabato [attivo dall'01/10] Link al sito: http://www.asst-bgovest.it/54.ASP?jump=newsArticle.asp&id=1290ASST Bergamo Est •Ospedali di Seriate, Alzano Lombardo e Piario: tende adiacenti all'ingresso dalle 9 alle 14. •Ospedale di Lovere: zona adiacente al Pronto Soccorso dalle 9 alle 14. Link al sito: http://www.asst-bergamoest.it/user/Default.aspx?SEZ=51&PAG=111&NOT=2339Per maggiori informazioni si consiglia di consultare direttamente i siti delle ASST ai link riportati.Le  persone  afferenti  alla  collettività  scolastica  si  recheranno  negli  orari  sopra  indicati,  nei  punti prelievo più vicini al proprio plesso scolastico. Il referto sarà disponibile dopo le ore 23.00 sul FSE (Fascicolo Sanitario Elettronico) personale per i maggiorenni e in quello indicato dai genitori per i minorenni.

**Comment by mfortini** [comment]
# ATS Brescia

https://www.ats-brescia.it/identificazione-tempestiva-dei-casi-di-covid-19-a-scuola

**Comment by mfortini** [comment]
#ATS Brianza

https://www.ats-brianza.it/it/azienda/news-online/2267-avvio-attivita-scolastiche-e-servizi-educativi-dell-infanzia-gestione-di-casi-e-focolai-di-covid-19.html

**Comment by mfortini** [comment]
# ATS Città metropolitana Milano

https://www.ats-milano.it/portale/EMERGENZA-CORONAVIRUS/RIPARTENZA-SCUOLE-Scuole-e-insegnanti

**Comment by mfortini** [comment]
# ATS Insubria

https://www.ats-insubria.it/news/6154-punti-tampone-accessibili-all-utenza-per-attivita-di-testing-in-ambito-scolastico-e-servizi-educativi-dell-infanzia-attivi-presso-le-asst-del-territorio-di-ats-insubria

**Comment by mfortini** [comment]
# ATS montagna

https://www.ats-montagna.it/covid-a-scuola-in-sicurezza/

**Comment by mfortini** [comment]
# ATS Pavia

https://www.ats-pavia.it/rientro-a-scuola

**Comment by mfortini** [comment]
# ATS Valpadana

https://www.ats-valpadana.it/scuole

**Comment by mfortini** [comment]
@cristigalas sarebbe utile fare una tabella su un foglio elettronico condiviso con tutte le info in colonna, esempio

* ATS
* Luogo
* Orari

in modo da avere una lista unica come base per una mappa

**Comment by cristigalas** [comment]
@mfortini qui il file che ho creato su GDrive https://docs.google.com/spreadsheets/d/11QDyMJ-K1I3q3Yk9BgoIaMYxjjiMUtMl9f8t-7xHND8/edit

Per ora ho inserito Bergamo, Brescia, Brianza. Poi continuo ma intanto dimmi se è ok.

**Comment by cristigalas** [comment]
Fatto! La mappa è qui https://covid19italia.help/mappe/Lombardia/tamponi/

Chiudo.
