### ISSUE TITLE
Dati Drive-in tamponi Regione Lazio da inserire in mappa

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#578]
@mfortini @michelerestuccia [Qui i file csv](https://github.com/emergenzeHack/covid19italia_segnalazioni/files/5433344/_reg_lazio_elenco_drivein_tamponi_20201022.csv.zip) (zippati) che [ha fatto Michele](https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/4005) con i punti drive-in per i tamponi della Regione Lazio. Elenco ottenuto copiando a mano le tre voci presenti nella pagina https://www.salutelazio.it/elenco-tamponi-drive-in

Informazioni aggiornate al 28 ottobre 2020.

**Comment by cristigalas** [comment]
@michelerestuccia ho aperto il file Csv Lazio ma ci sono solo una piccola parte delle postazioni segnalate sul sito della Regione. Possibile?

**Comment by michelerestuccia** [comment]
C'era stato un problema con il csv, ho creato una nuova [tabella in Drive](https://docs.google.com/spreadsheets/d/1qD9MjPe3dLO-UOQpJtPcM6kbdsNFxfJpBtkLGRVkDjs/edit#gid=1262204356) con i dati. Restano da inserire le coordinate (io posso rimettermici venerdì)

**Comment by cristigalas** [comment]
@mfortini ho completato con le coordinate anche il file Lazio. È pronto! Lo trovi qui https://docs.google.com/spreadsheets/d/1qD9MjPe3dLO-UOQpJtPcM6kbdsNFxfJpBtkLGRVkDjs/edit

**Comment by cristigalas** [comment]
Mappa online https://covid19italia.help/mappe/Lazio/tamponi/

Chiudo.
