### ISSUE TITLE
Dati laboratori e punti tampone in Piemonte da mappare

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#579]
@mfortini @michelerestuccia [Porto qui i file Csv](https://github.com/emergenzeHack/covid19italia_segnalazioni/files/5433153/reg_piemonte_laboratori_tamponi.zip) (zippati) [creati da Michele](https://github.com/emergenzeHack/covid19italia_segnalazioni/issues/4003) con i laboratori e i punti prelievo tamponi della Regione Piemonte.

Qui la fonte dei dati: https://www.regione.piemonte.it/web/temi/sanita/accesso-ai-servizi-sanitari/tamponi-covid-19-molecolari-pagamento

**Comment by cristigalas** [comment]
Ho ripulito il file Csv creato da Michele da piccoli errori, refusi, ecc. Quello ripulito ora è qui https://drive.google.com/file/d/1rOskZF-FyJSgM2sFG-xLiV32w82nmXHU/view?usp=drivesdk
Bisogna solo aggiungere le coordinate.

**Comment by gloriaschiavi** [comment]
Yay, grazie. Coordinate ne faccio un po' ora ! 

Gloria 
 
  El mié., oct. 28, 2020 a 20:36, Cristina Galasso<notifications@github.com> escribió:   


@michelerestuccia @gloriaschiavi Ho ripulito i due file creati da Michele da piccoli errori, refusi, ecc. e poi li ho uniti in un unico file. Quello ripulito ora è qui https://docs.google.com/spreadsheets/d/15OIwan-Ja9WThFlqFQcsclDgQn3f5BzW_aWdcKNA5dA/edit

Bisogna solo aggiungere le coordinate.

**Comment by cristigalas** [comment]
Ottimo @gloriaschiavi! Io sto facendo il Lazio, quindi va benissimo se tu fai il Piemonte, così lavoriamo su due file in parallelo 💪😜

**Comment by cristigalas** [comment]
@gloriaschiavi ha aggiunto tutte le coordinate. File pronto @mfortini!
https://docs.google.com/spreadsheets/d/15OIwan-Ja9WThFlqFQcsclDgQn3f5BzW_aWdcKNA5dA/edit 

Ho aggiunto anche link alla fonte.

**Comment by cristigalas** [comment]
Mappa online https://covid19italia.help/mappe/Piemonte/tamponi/

Chiudo.
