### ISSUE TITLE
Messaggio per pagine in costruzione

### ISSUE THREAD

**Issue by tailot** [emergenzeHack/covid19italia#59]
Al fine di dare un messaggio all'utente sulle pagine in costruzione si è deciso di cambiare la label per la pagina 404 e renderla più generica possibile.

"Pagina non disponibile o in costruzione
È possibile che il link che hai seguito sia stata rimossa o che la pagina sia in costruzione.

**Comment by Ibernato93** [comment]
E' semplice da risolvere, posso farlo io

**Comment by iltempe** [comment]
@tailot è fatta giusto'?

**Comment by tailot** [comment]
@iltempe si
