### ISSUE TITLE
Quali categorie tracciare?

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#6]
Decidiamo quali categorie vogliamo tracciare

**Comment by iltempe** [comment]
@dontyna suggeriva #4 Donazioni

**Comment by favoeva** [comment]
Normativa nazionale 
Ordinanze regionali
donazioni (come donare)
Bufale 
Associazioni / Social street
Richiesta aiuti

**Comment by Saraveg** [comment]
numeri verdi regioni
link x dati e notizie ufficiali

(sulle ordinanze ci sarebbero anche quelle comunali...)

**Comment by cristigalas** [comment]
Aggiungerei anche servizi di prossimità, come consegne a domicilio di spesa e farmaci.

**Comment by iltempe** [comment]
fake news?

**Comment by iltempe** [comment]
potremmo fare in modo che si possano segnalare "Realtà" reali o virtuali dove condividere informazioni ed aggiungerle ad una lista di CANALI ASTRATTA da usare per rilanciare info.

**Comment by olistik** [comment]
@favoeva 

> Normativa nazionale
> Ordinanze regionali
> donazioni (come donare)
> Bufale
> Associazioni / Social street
> Richiesta aiuti
> Scuola didattica a distanza
> Smart working esperienze
> Iniziative governo (esempio questa https://solidarietadigitale.agid.gov.it/#/)

Una suddivisione delle informazioni tra nazionale, regionale e comunale?

Una persona potrebbe voler partire dal sapere lo stato del suo Comune (ereditando le informazioni regionali e nazionali).

**Comment by iltempe** [comment]
@olistik la suddivisione viene a livello di LABEL sugli issue github dirretamente da li. 

Ricapitolo

- Normativa nazionale
- Ordinanze regionali
- Donazioni 
- Fake News
- Associazioni / Social street
- Richiesta Aiuti
- Didattica a distanza esperienze e strumenti
- Smart working esperienze e strumenti
- Iniziative governo
- Contatti utili (numeri verdi regioni)
- Links Utili (x dati e notizie ufficiali)


@mfortini io inizierei con queste poi aggiustiamo il tiro.

**Comment by RocknRollAllNight** [comment]
Dobbiamo decidere la data zero di catalogazione. Sugli atti ufficiali è importante (io partirei dal decreto legge pubblicato sabato 7 marzo ad esempio, per non confondere le persone con il precedente)

**Comment by mfortini** [comment]
Ho creato le categorie

**Comment by cristigalas** [comment]
Scusate ma l’offerta di aiuti e servizi come la classifichiamo? Non vedo nessuna label specifica. Con @Saraveg stiamo lavorando a questa mappatura https://github.com/emergenzeHack/covid19italia/issues/3 e una o più label ci servirebbero...

**Comment by cristigalas** [comment]
Un’altra cosa: @favoeva la categoria associazioni/social Street mi convince poco. Io categorizzerei le tipologie di segnalazioni non il ‘chi’, non so se mi spiego... Suggerisco di riaprire issue e ragionarci un attimo...

**Comment by dontyna** [comment]
Segnalo questa raccolta di iniziative solidali in tutta Italia: https://docs.google.com/spreadsheets/d/1GmyjJYiJQ0VSvePvgbzaggBOIXeQKGtYC2oLO37LCmk/edit?fbclid=IwAR0Ej_FIkGZ5d5WzSJK23v3R-Qeluvq6eWmYAf6vcpcKrC5HJt6HsX-cWCA#gid=0
Aggiungerei come dice @cristigalas le categorie di aiuti e servizi. 

- consegna a domicilio
- supporto psicologico
- servizi tecnologici gratuiti
...

**Comment by cristigalas** [comment]
@dontyna @Saraveg a questo punto unirei i due file, quello tuo Donata e quello che con @Saraveg abbiamo aperto qui https://docs.google.com/spreadsheets/d/17dyXTy5LZGlLhYXBq4Qb4jiOsbqrGhPPhEZcqzo68Ow
Che ne dite?

**Comment by cristigalas** [comment]
Penserei alle label da adottare anche in base alla form ‘Segnala’ che andremo a costruire. Ho proposto qui un elenco di campi per la form: https://github.com/emergenzeHack/covid19italia/issues/18#issuecomment-596640802

**Comment by cristigalas** [comment]
Pensando anche alla gestione label Tci e alla eventuale form ‘Segnala’, propongo queste label:

- Normativa nazionale
- Ordinanze regionali
- Donazioni materiali/strumenti
- Raccolte fondi
- Fake News
- Dati utili
- Richiesta Aiuto
- Offerta aiuto
- Servizi e iniziative solidali 
- Consegna farmaci/spesa/altro
- Didattica a distanza esperienze e strumenti
- Smart working esperienze e strumenti
- Contatti utili (numeri verdi regioni)
- Giochi/intrattenimento bambini

E poi prevederei label per Regioni con le quali classificare ogni segnalazione (come abbiamo fatto per le promesse elettorali), così l’utente può rintracciare le segnalazioni sul suo territorio.

**Comment by Saraveg** [comment]
> @dontyna @Saraveg a questo punto unirei i due file, quello tuo Donata e quello che con @Saraveg abbiamo aperto qui https://docs.google.com/spreadsheets/d/17dyXTy5LZGlLhYXBq4Qb4jiOsbqrGhPPhEZcqzo68Ow
> Oppure aspettiamo e inseriamo tutto insieme sul sito quando è pronto così evitiamo un doppio passaggio? Che ne dite?

scusa avevo scitto di là. io ci sto per unire se serve.

**Comment by Saraveg** [comment]
> * Normativa nazionale
> * Ordinanze regionali
> * Donazioni materiali/strumenti
> * Raccolte fondi
> * Fake News
> * Dati utili
> * Richiesta Aiuto
> * Offerta aiuto
> * Servizi e iniziative solidali
> * Consegna farmaci/spesa/altro
> * Didattica a distanza esperienze e strumenti
> * Smart working esperienze e strumenti
> * Contatti utili (numeri verdi regioni)
> * Giochi/intrattenimento bambini

Offerta aiuto, Servizi e iniziative solidali, Consegna farmaci/spesa/altro forse queste non so troppo simili?

**Comment by cristigalas** [comment]
> > * Normativa nazionale
> > * Ordinanze regionali
> > * Donazioni materiali/strumenti
> > * Raccolte fondi
> > * Fake News
> > * Dati utili
> > * Richiesta Aiuto
> > * Offerta aiuto
> > * Servizi e iniziative solidali
> > * Consegna farmaci/spesa/altro
> > * Didattica a distanza esperienze e strumenti
> > * Smart working esperienze e strumenti
> > * Contatti utili (numeri verdi regioni)
> > * Giochi/intrattenimento bambini
> 
> Offerta aiuto, Servizi e iniziative solidali, Consegna farmaci/spesa/altro forse queste non so troppo simili?

Pensando anche a Tci e alle segnalazioni che ho visto finora, ho pensato che fossero necessarie label più specifiche per le segnalazioni più frequenti e utili (appunto le consegne a domicilio) e label più generali per ciò che non rientra nelle label più specifiche. Dobbiamo pensare che poi le label possono funzionare come tag per la ricerca interna. Ovviamente se lavoriamo sul modello Tci.

**Comment by Saraveg** [comment]
> > @dontyna @Saraveg a questo punto unirei i due file, quello tuo Donata e quello che con @Saraveg abbiamo aperto qui https://docs.google.com/spreadsheets/d/17dyXTy5LZGlLhYXBq4Qb4jiOsbqrGhPPhEZcqzo68Ow
> > Oppure aspettiamo e inseriamo tutto insieme sul sito quando è pronto così evitiamo un doppio passaggio? Che ne dite?
> 
> scusa avevo scitto di là. io ci sto per unire se serve.


> Segnalo questa raccolta di iniziative solidali in tutta Italia: https://docs.google.com/spreadsheets/d/1GmyjJYiJQ0VSvePvgbzaggBOIXeQKGtYC2oLO37LCmk/edit?fbclid=IwAR0Ej_FIkGZ5d5WzSJK23v3R-Qeluvq6eWmYAf6vcpcKrC5HJt6HsX-cWCA#gid=0
> Aggiungerei come dice @cristigalas le categorie di aiuti e servizi.
> 
> * consegna a domicilio
> * supporto psicologico
> * servizi tecnologici gratuiti
>   ...

scusate se continuo a chiedere....io e @chicca possiamo mettere a posto il file unendo. incolliamo tutto nel file segnalato da @dontyna? se ci dite proviamo a renderci utili :)

**Comment by cristigalas** [comment]
> scusate se continuo a chiedere....io e @chicca possiamo mettere a posto il file unendo. incolliamo tutto nel file segnalato da @dontyna? se ci dite proviamo a renderci utili :)

Per me va bene.

**Comment by Saraveg** [comment]
> > scusate se continuo a chiedere....io e @chicca possiamo mettere a posto il file unendo. incolliamo tutto nel file segnalato da @dontyna? se ci dite proviamo a renderci utili :)
> 
> Per me va bene.

anche se io ancora non ho capito di chi è quel file e se sono onboard o no...

**Comment by dontyna** [comment]
Normativa nazionale
    Ordinanze regionali
    Donazioni materiali/strumenti
    Raccolte fondi
    **Fake News** (questa è critica perché 1. una persona potrebbe pensare che se non è stata catalogata qui come FN allora non lo è 2. Gli diamo ulteriormente spazio)
    **Dati utili ** (forse meglio dati ufficiali)
    Richiesta Aiuto
    Offerta aiuto
    Servizi e iniziative solidali
    Consegna farmaci/spesa/altro
    Didattica a distanza esperienze e strumenti
    Smart working esperienze e strumenti
    Contatti utili (numeri verdi regioni)
    Giochi/intrattenimento bambini
Iniziative culturali

**Comment by dontyna** [comment]
@mfortini secondo me è difficile catalogare ora tutti i tipi di richieste di aiuto e di offerte, cominciamo così

**Comment by iltempe** [comment]
quoto @dontyna. iniziamo con queste poi aggiustiamo il tiro.

**Comment by cristigalas** [comment]
@dontyna la segnalazione bufale però per Tci ha funzionato bene. Io credo sia importante, e poi la popoliamo anche noi e le fonti non mancano per farlo. Io la prevederei. Ok per dati ufficiali.

**Comment by chiccap** [comment]
Ciao!

AA insieme a @cristigalas ha rivisto e modificato le label:

Fonti istituzionali
Offerta aiuto
Raccolta fondi
Fake News
Informazioni utili
Richiesta aiuto
Donazioni materiali/strumenti
Servizi e iniziative solidali private
Servizi e iniziative solidali pubbliche
Consegne e commissioni
Didattica a distanza
Sostegno al lavoro
Contatti utili
Giochi/intrattenimento bambini
Intrattenimento adulti/attività culturale
Supporto psicologico

Fateci sapere cosa ne pensate!

**Comment by iltempe** [comment]
@mfortini @avivace procedo con le pagine o già ci lavorate voi?

**Comment by luciaroma** [comment]
@mfortini @iltempe @avivace piccola modifica su due etichette, che si fondono e diventano una: 
giochi/intrattenimento bambini + intrattenimento adulti/attività culturali DIVENTANO UNICA ETICHETTA: iniziative culturali/ricreative.

Questo perché nel form andrà messa una sezione "destinatari" (come nel file mappatura) in modo da includere tutti i target di persone. Poi scrivo anche sulla issue del form.

Vi fila? :-)

**Comment by avivace** [comment]
@luciaroma ha senso, aggiorno i form!

**Comment by avivace** [comment]
@luciaroma non vedo ancora la label nel repository. Creala con `iniziative culturali e ricreative`

**Comment by luciaroma** [comment]
@avivace non sono capace :-)

**Comment by iltempe** [comment]
posso chiudere?

**Comment by Albertopi78** [comment]
Ho replicato queste categorie sul gruppo Facebook. Anche lì i post sono tutti categoralizzabili dagli admin seguendo la medesima tassonomia. 
<img width="524" alt="Schermata 2020-03-12 alle 21 58 26" src="https://user-images.githubusercontent.com/42850988/76566277-b27e5e00-64ac-11ea-8073-abdddaacfe6f.png">

**Comment by avivace** [comment]
@luciaroma Faccio io!

**Comment by Albertopi78** [comment]
@chiccap chiedono dal gruppo Facebook
<img width="506" alt="Schermata 2020-03-13 alle 10 44 23" src="https://user-images.githubusercontent.com/42850988/76609513-c90dcf00-6517-11ea-9703-15989ce2c9df.png">

Ne parliamo? Io ho qualche dubbio, perché potrebbero venir fuori petizioni di qualunque genere.

**Comment by chiccap** [comment]
@Albertopi78 questa nello specifico io la metterei in iniziative solidali. dobbiamo certamente stare attent* e verificarle e valutare bene ogni volta. @cristigalas Tu che ne pensi?

**Comment by cristigalas** [comment]
@Albertopi78 mi metti qui link al post che così capisco meglio di cosa si tratta? Grazie!
Comunque possiamo senz’altro accettare appelli e petizioni valutando bene, come diceva @chiccap, di volta in volta. Ma non la metterei sotto iniziative solidali (che cosa offre?) semmai Notizie e forse potremmo anche immaginare una label ad hoc (petizioni), se ne arrivano altre. Tu @chiccap perché volevi inserire questa sotto Iniziative solidali? Però forse non capisco perché non so di cosa si tratti...

**Comment by chiccap** [comment]
@cristigalas ti metto qui il link: https://jacobinitalia.it/reddito-e-solidarieta-la-crisi-sanitaria-non-sia-pagata-da-chi-non-lavora/

L'avrei messa sotto iniziative solidali in ottica di proposta dal basso di richiesta misure emergenziali su tematiche sociali e lavorative. Forse anche in notizie in effetti. Sicuramente se dovessero arrivare altre petizioni aggiungerei label! Ad ogni modo l'accetterei.

**Comment by Albertopi78** [comment]
@chiccap @cristigalas vi dico cosa non mi convince (al di là del contenuto) di questa nello specifico. Chiedono di sottoscrivere un blocco di proposte molto generiche (che posso anche condividere nel merito, ma non è questo il punto, per me ;) ) per una generica "battaglia" sul tema. Chiedono di mandare mail per adesione. Non dicono come useranno quella mail né i dati. Per questo non la condividerei.

**Comment by avivace** [comment]
Sono d'accordo @Albertopi78 , servirebbe una policy con qualche punto da controllare per questo tipo di iniziative

**Comment by Albertopi78** [comment]
@avivace ottima idea. Esistono altre policy simili/linee guida per altre segnalazioni? Intanto preparo una bozza di questa.

**Comment by cristigalas** [comment]
Allora, ho letto l’appello in questione e non lo accetterei, mi pare troppo generico e allo stesso tempo ho paura che sotto traccia voglia parlare d’altro (vedi questione reddito di cittadinanza _versus_ reddito di solidarietà). Io accetterei appelli più specifici e attinenti all’emergenza, oltre che più chiari nelle modalità di adesione, trattamento dati, ecc.

**Comment by chiccap** [comment]
Ho notato numerose segnalazioni di CAV e supporto a donne vittime di violenza. Mi piacerebbe ci fosse una label apposita, che ne pensate? @cristigalas @favoeva @Saraveg

**Comment by cristigalas** [comment]
> Ho notato numerose segnalazioni di CAV e supporto a donne vittime di violenza. Mi piacerebbe ci fosse una label apposita, che ne pensate? @cristigalas @favoeva @Saraveg

Uhmm... possiamo inserire nuova label #Donne se pensiamo che ci siano altri servizi ad hoc. Non so, label #antiviolenza mi pare molto molto specifica e poi non la useremo molto. Ma parliamone meglio...

**Comment by chiccap** [comment]
> > Ho notato numerose segnalazioni di CAV e supporto a donne vittime di violenza. Mi piacerebbe ci fosse una label apposita, che ne pensate? @cristigalas @favoeva @Saraveg
> 
> Uhmm... possiamo inserire nuova label #Donne se pensiamo che ci siano altri servizi ad hoc. Non so, label #antiviolenza mi pare molto molto specifica e poi non la useremo molto. Ma parliamone meglio...

Sì sì sono d'accordo su label donne.

**Comment by luciaroma** [comment]
anche io d'accordo su label donne

**Comment by cristigalas** [comment]
Sentiamo anche @favoeva @Saraveg... che dite su label #Donne? La attiviamo subito o aspettiamo di vedere se arrivano altre segnalazioni che possiamo marcare con questa label?

**Comment by favoeva** [comment]
> Sentiamo anche @favoeva @Saraveg... che dite su label #Donne? La attiviamo subito o aspettiamo di vedere se arrivano altre segnalazioni che possiamo marcare con questa label?

Avvierei da subito

**Comment by cristigalas** [comment]
Ok! allora aggiungo label #Donne e la attribuisco alle notizie sui Cav.

**Comment by cristigalas** [comment]
Fatto.

**Comment by chiccap** [comment]
Ci sono numerose segnalazioni di traduzioni documenti ufficiali e servizi dedicati a persone di origine straniera. Vogliamo creare una label apposita e poi eventualmente prevedere una sezione specifica del sito dove poter trovare queste info? Magari tradotta in inglese (è in previsione la traduzione #227).
@Saraveg @luciaroma @cristigalas @favoeva

**Comment by luciaroma** [comment]
io sono d'accordo, sia per label che per una sezione che aiuta a trovare i testi tradotti, penso sia un servizio molto utile per chi ne deve beneficiare e anche per raffinare la ricerca dei servizi per categorie. 
Per la label possiamo metere: traduzioni in lingue?

**Comment by cristigalas** [comment]
> Ci sono numerose segnalazioni di traduzioni documenti ufficiali e servizi dedicati a persone di origine straniera. Vogliamo creare una label apposita e poi eventualmente prevedere una sezione specifica del sito dove poter trovare queste info? Magari tradotta in inglese (è in previsione la traduzione #227).
> @Saraveg @luciaroma @cristigalas @favoeva

Mi sembra un’ottima idea! Ci pensi tu alla label ad hoc?

**Comment by chiccap** [comment]
Ci sono numerose segnalazioni di traduzioni documenti ufficiali e servizi dedicati a persone di origine straniera. Vogliamo creare una label apposita e poi eventualmente prevedere una sezione specifica del sito dove poter trovare queste info? Magari tradotta in inglese (è in previsione la traduzione di alcune

> > Ci sono numerose segnalazioni di traduzioni documenti ufficiali e servizi dedicati a persone di origine straniera. Vogliamo creare una label apposita e poi eventualmente prevedere una sezione specifica del sito dove poter trovare queste info? Magari tradotta in inglese (è in previsione la traduzione #227).
> > @Saraveg @luciaroma @cristigalas @favoeva
> 
> Mi sembra un’ottima idea! Ci pensi tu a creare label ad hoc?

Sì creo io e la attribuisco alle segnalazioni riguardanti nello specifico persone di origine straniera. @luciaroma sì mettiamo un generico "stranieri" tanto per il momento serve a noi poi eventualmente discuteremo di come inserire questa categoria di segnalazioni sul sito! Grazie!

**Comment by iltempe** [comment]
chiudo. in caso riapriamo su specifica categoria da gestire.
