### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by Ibernato93** [emergenzeHack/covid19italia#63]
Ciao, @Raffa93 è il mio user per TG

**Comment by avivace** [comment]
Ciao @Ibernato93 ! Ti ho aggiunto al gruppo Telegram degli sviluppatori e tecnici che stanno lavorando al progetto. Nel frattempo, guardati attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare e faccelo sapere :)
