### ISSUE TITLE
Pagine Segnalazioni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/covid19italia#65]
Quando si clicca su una segnalazione non si trova la relativa pagina. problema sulla generazione delle pagine in jekyll.

**Comment by daemonzone** [comment]
Gli slug delle pagine linkate in home non corrispondono ai permalink. Ad esempio la normativa-nazionale. Ma il contenuto della pagina non è (ancora) presente, servono ulteriori indicazioni prima di pubblicare...

**Comment by iltempe** [comment]
@tailot è fatta?
