### ISSUE TITLE
Attivare meccanismo di conversione issue Github

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#7]
Usiamo il vecchio script oppure altri sistemi?

**Comment by iltempe** [comment]
a me non dispiace affatto il repo degli issue per generare i dati come approccio. ma vorrei sentire gli altri che ne pensano....

**Comment by olistik** [comment]
@mfortini mi ricordi come vengono gestite? Nel repo https://github.com/emergenzeHack/terremotocentro_segnalazioni e in https://github.com/emergenzeHack/terremotocentro non vedo a colpo d'occhio gli automatismi.

**Comment by mfortini** [comment]
https://github.com/emergenzeHack/covid19italia/wiki/Come-funziona-(in-breve)-il-%22metodo-TCI%22

**Comment by olistik** [comment]
@mfortini Il backend comprende anche l'app Heroku, giusto? 

https://terremotocentroitalia.herokuapp.com/segnalazioni/ 

Ce la portiamo dietro as-is (eventualmente con un parametro di contesto)?

**Comment by iltempe** [comment]
qui il buon @napo proponeva AWS...

**Comment by olistik** [comment]
> qui il buon @napo proponeva AWS...

@iltempe Diciamo che un'istanza Heroku free non mi sembra brutta, dato che le hit sul sito non dovrebbero corrispondere alle hit sull'applicazione.

A questo proposito vedo che invece https://www.terremotocentroitalia.info/segnala/ include via iframe e quindi per ogni visita contatta anche l'app Heroku.

Possiamo replicare tutto in questo progetto ma se volete possiamo anche solo trattare l'istanza Heroku (o vattelapesca) come un API server che viene contattato dal sito web e lasciare sul sito web un rendering statico del form (con i vari JS per la mappa, ovviamente) che spedisce i dati all'API server solo al submit.

A meno che non entrino in giochi automatismi server-side particolari durante la composizione della form. Ve ne risulta qualcuno?

**Comment by olistik** [comment]
Un dubbio sulla conversione.
Avete già valutato in passato di creare direttamente i file dei post a partire dai dati invece di basarsi solo su query ajax?

**Comment by olistik** [comment]
Scusate, vedo ora la issue #18 
Quindi questa riguarda il trasferimento issue GitHub -> dati sito.
Sposto nell'altra issue i commenti pertinenti.

**Comment by iltempe** [comment]
direi che è a posto.
