### ISSUE TITLE
New Homepage

### ISSUE THREAD

**Issue by Saraveg** [emergenzeHack/covid19italia#71]
* Modificare l'homepage #73 
* Barra in alto a dx #74 
* Dentro ABOUT cambiare alcune parti di testo #75 
* Navbar #76 
* Loghi #77

Qui i nostri suggerimenti: https://docs.google.com/document/d/1nQUAHVj6kB4KXdTh9mpXkTUwCUs6JfSqHKkHj_M7LgA/edit

**Comment by mfortini** [comment]
HOME PAGE
https://www.covid19italia.help/

TESTO IN HOME PAGE

Un progetto per condividere informazioni e attivarsi a supporto dell'emergenza COVID19

Barra in alto a dx

Resta “segnala” 
Resta “progetto” e relativo menù a tendina; cambiare “contribuisci” con “partecipa!”
PARTECIPA!: cliccando si apre menù a tendina con opzioni per partecipare:
Aderisci a gruppo Telegram
Contribuisci su Github
Rilancia informazioni sui social 

Dentro ABOUT cambiare alcune parti di testo, vedi in giallo:

“Questo è un progetto non profit, organizzato interamente da volontari e volontarie. È nato per condividere informazioni utili e verificate sull’evento di CoronaVirus diffusosi in Italia nel 2020. 
Il progetto, laddove lo si ritenga utile, è usabile da organizzazioni, associazioni, gruppi informali, persone ed anche pubbliche amministrazioni che avessero bisogno di un servizio per informare e attivarsi per rispondere all’emergenza covid19 su quanto sta avvenendo a seguito della diffusione del virus.) 
Mettere “Link utili” come etichetta principale al posto di “servizi” e nel  menù a tendina: iniziative solidali e opendata
Togliere raccolte
Togliere aggiornamenti

Loghi centrali
Segnala
Iniziative solidali
Fonti istituzionali (che pesca da QUI)
Partecipa!

(normativa nazionale e fake news per ora spegniamoli, li attiviamo quando le cose ci sono)

MAPPA (in futuro prevedere mappa quando si avrà la geolocalizzazione)

**Comment by iltempe** [comment]
chiudo perchè già splittato in tanti ISSUE
