### ISSUE TITLE
Barra in alto a dx

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#74]
Related #71 

Resta “segnala”
Resta “progetto” e relativo menù a tendina; cambiare “contribuisci” con “partecipa!”
PARTECIPA!: cliccando si apre menù a tendina con opzioni per partecipare:
Aderisci a gruppo Telegram
Contribuisci su Github
Rilancia informazioni sui social

**Comment by Jolsty** [comment]
@mfortini a cosa dovrebbe puntare "Rilancia informazioni sui social" ?

**Comment by Jolsty** [comment]
Intanto ho aggiornato altre cose.
Attendo risposta per il gruppo telegram da usare e "Rilancia informazioni sui social" (che per ora ho nascosto)

**Comment by luciaroma** [comment]
@Jolsty rilancia sui social è pensato per chi vuole partecipare in forma leggera ovvero divulgando la piattaforma e via via le segnalazioni. Se pensi che si possa usare un termine migliore, più appropriato, vai pure. Tipo: condividi? ;-)

**Comment by iltempe** [comment]
@Jolsty @luciaroma chiudiamo? che si fa?

**Comment by luciaroma** [comment]
mettiamo pulsante condividi, e per me si può chiudere :-)

**Comment by luciaroma** [comment]
se per voi ha senso, se no, che viene spontaneo condividere, basta quello che c'è

**Comment by iltempe** [comment]
@Jolsty che famo?

**Comment by Jolsty** [comment]
@iltempe @luciaroma non ho capito a cosa deve puntare il pulsante "Condividi".. è un share su qualche social specifico?

**Comment by iltempe** [comment]
@luciaroma dicci tutto ;-)

**Comment by Jolsty** [comment]
@iltempe che facciamo lasciamo così? chiudo ?

**Comment by iltempe** [comment]
Per me possiamo. Chiudere
