### ISSUE TITLE
Dentro ABOUT cambiare alcune parti di testo

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#75]
Related #71 

“Questo è un progetto non profit, organizzato interamente da volontari e volontarie. È nato per condividere informazioni utili e verificate sull’evento di CoronaVirus diffusosi in Italia nel 2020.
Il progetto, laddove lo si ritenga utile, è usabile da organizzazioni, associazioni, gruppi informali, persone ed anche pubbliche amministrazioni che avessero bisogno di un servizio per informare e attivarsi per rispondere all’emergenza covid19 su quanto sta avvenendo a seguito della diffusione del virus.)

**Comment by tailot** [comment]
https://github.com/emergenzeHack/covid19italia/pull/79

**Comment by luciaroma** [comment]
"su quanto sta avvenendo a seguito della diffusione del virus." questa ultima frase va tolta (è rimasta come refuso)

**Comment by tailot** [comment]
> @iltempe @mfortini @tailot "su quanto sta avvenendo a seguito della diffusione del virus." questa ultima frase va tolta (è rimasta come refuso)

si si è stata tolta!

**Comment by iltempe** [comment]
fatto? Chiudo?
