### ISSUE TITLE
Navbar homepage

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#76]
Related #71 

Mettere “Link utili” come etichetta principale al posto di “servizi” e nel  menù a tendina: iniziative solidali e opendata
Togliere raccolte
Togliere aggiornamenti

**Comment by tailot** [comment]
@mfortini "Link utili"  e "Servizi" vanno scambiati ? Se no, che fine fa servizi ?

**Comment by luciaroma** [comment]
sì esatto, "servizi" va tolto e va scambiato con "link utili"

**Comment by iltempe** [comment]
fatto?

**Comment by tailot** [comment]
@luciaroma mi dici se va bene così chiudiamo questa?

**Comment by tailot** [comment]
@iltempe in teoria netlify offre il servizio di preview, bisogna controllare prima del merge!

**Comment by tailot** [comment]
@luciaroma mi dici se va bene così chiudiamo questa?

**Comment by luciaroma** [comment]
sì va bene
