### ISSUE TITLE
Loghi centrali

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#77]
Related #71 

Segnala
Iniziative solidali
Fonti istituzionali (che pesca da QUI)
Partecipa!

(normativa nazionale e fake news per ora spegniamoli, li attiviamo quando le cose ci sono)

MAPPA (in futuro prevedere mappa quando si avrà la geolocalizzazione)

**Comment by mfortini** [comment]
NB Stiamo parlando di modificare _data/logos.yml
Serviranno probabilmente delle nuove icone in img/icone/

**Comment by Saraveg** [comment]
Cmq intanto già se togliamo "private" da iniziative solidali è meglio

**Comment by luciaroma** [comment]
Fonti istituzionali (che pesca da QUI). Il QUI sarebbe il file "Fonti istituzionali" creato e condiviso da Damiano

**Comment by RocknRollAllNight** [comment]
Fonti istituzionali pesca da questo:
https://docs.google.com/spreadsheets/d/1EXiPYuAzudFmLMGWGmU_PKilqgZ4guH0q-6ecNV1i4g/edit#gid=0

**Comment by luciaroma** [comment]
> Cmq intanto già se togliamo "private" da iniziative solidali è meglio

sì, togliamolo altrimenti occupa troppo spazio e può anche confondere @mfortini

**Comment by iltempe** [comment]
PRIVATE è rimosso.

**Comment by iltempe** [comment]
@cristigalas FONTI ISTITUZIONALI sono una label? @avivace ci sono nel form? @RocknRollAllNight segnala un gdrive ...direi di mettere anche questi dati no?

**Comment by iltempe** [comment]
me la sono smazzata io. chiudo.
