### ISSUE TITLE
Pulsanti form

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/covid19italia#80]
Relativo a https://github.com/emergenzeHack/covid19italia_form/issues/16
@cristigalas ha scritto:
Segnalo poi che i bottoni della form adesso sono troppo stretti e non si leggono i testi fino in fondo.

**Comment by mfortini** [comment]
Ho tolto report-btn che rompeva le cose. Se possiamo usiamo le classi di bootstrap.
Resta il problema degli spazi, forse bisogna usare div separati per ogni btn.

**Comment by avivace** [comment]
UUps, sorry, `report-btn` aggiungeva solo 1 px di margine per evitare si attaccassero tutti, se non ricordo male

**Comment by olistik** [comment]
Di quale form stiamo parlando?
Avete una URL/screenshot come riferimento del problema?

**Comment by avivace** [comment]
https://www.covid19italia.info/segnala/
Dovrebbe essere fixato

**Comment by iltempe** [comment]
a posto? chiudo?

**Comment by avivace** [comment]
Sì, dovrebbe essere a posto
