### ISSUE TITLE
Menu a tendina IL PROGETTO - canali

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/covid19italia#84]
Ciao!

E' possibile mettere nel menu a tendina IL PROGETTO i canali del progetto? Come avevamo fatto per TCI qui: https://terremotocentroitalia.info/canali/

Grazie!

**Comment by iltempe** [comment]
i contatti sono tutti in ABOUT, facciamo anche questa pagina?

**Comment by Jolsty** [comment]
in teoria è già fatta (https://www.covid19italia.info/canali/) , bisogna solo aggiungere il riferimento nel menù a tendina

**Comment by Jolsty** [comment]
@chiccap, ho riaggiunto il link a /canali

Chiudo il ticket
