### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by rokity** [emergenzeHack/covid19italia#89]
Salve

Richiedo l'accesso per contribuire . 
Username Telegram : @riccardoamadio

**Comment by avivace** [comment]
Ciao @rokity  ! Ti ho aggiunto al gruppo Telegram degli sviluppatori e tecnici che stanno lavorando al progetto. Nel frattempo, guardati attorno e se c'è qualche Issue o task a cui pensi di riuscire a lavorare o su cui vorresti collaborare e faccelo sapere :)

**Comment by rokity** [comment]
Ciao @avivace ! Grazie per avermi accettato. Entro stasera guardo ai task per sviluppatori .
Grazie Mille
