### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/covid19italia#9]
Creare un logo e convertirlo in tutte le dimensioni esempio con https://icoconvert.com/

**Comment by iltempe** [comment]
non mi dispiace la filosofia del team di hackivisti cinesi che segnala napo, loghi positivi...!

**Comment by olistik** [comment]
Una prova veloce con canva.com:

<img width="350" alt="covid19italia-logo1" src="https://user-images.githubusercontent.com/21038/76202721-91d8ae80-61f5-11ea-9e8b-56108d4c5ce5.png">

**Comment by iltempe** [comment]
@dontyna ha scritto ci stava lavorando...

**Comment by dontyna** [comment]
![Schermata 2020-03-09 alle 11 58 08](https://user-images.githubusercontent.com/6824007/76217014-e853e600-6211-11ea-894d-aaaa5b5790b6.png)

**Comment by dontyna** [comment]
![bozzalogo](https://user-images.githubusercontent.com/6824007/76217097-16392a80-6212-11ea-84c3-142eaf190cd0.jpg)

**Comment by dontyna** [comment]
![bozzalogo2](https://user-images.githubusercontent.com/6824007/76217225-51d3f480-6212-11ea-8a84-9725f0dc40e6.jpg)

**Comment by cristigalas** [comment]
Per me il primo o il quarto! Tra i due, meglio il quarto.

**Comment by olistik** [comment]
Concordo con @cristigalas 🙂🎩

**Comment by luciaroma** [comment]
io voto il primo

**Comment by Saraveg** [comment]
tra questi voto l'ultimo anche se rilancio @iltempe su meta messaggio positivo. forse diminuendo un po' il font?

**Comment by iltempe** [comment]
io voto il primo. sul motto positivo del tipo "insieme ce la faremo" (come hanno fatto in cina) anche se un po' politico a me piace. potremmo metterlo come sottotitolo nel portale anche se non è nel logo.

**Comment by dontyna** [comment]
![covidlogo](https://user-images.githubusercontent.com/6824007/76256920-01c85280-6251-11ea-9e22-7a44aa01216b.jpg)

**Comment by dontyna** [comment]
![Logo 1 covid](https://user-images.githubusercontent.com/6824007/76262363-65a44880-625c-11ea-8a63-d16fd5cbdd7a.png)

**Comment by dontyna** [comment]
@mfortini @iltempe @Saraveg @cristigalas e il resto della cumpa: 2 opzioni, votate!

**Comment by Saraveg** [comment]
> @mfortini @iltempe @Saraveg @cristigalas e il resto della cumpa: 2 opzioni, votate!

1. da' senso di comunità che argina. o almeno...mi sembra! :)

**Comment by mfortini** [comment]
Anche per me 1, servirebbe un testo un pelo più marcato perché quello lì rischia di diventare troppo illeggibile

**Comment by luciaroma** [comment]
anche io voto 1, stesse motivazioni di @Saraveg, concordo con @mfortini che va evidenziato meglio il font

**Comment by dontyna** [comment]
Anche io preferisco l'1, ma aspettavo le vostre indicazioni :)

**Comment by iltempe** [comment]
@dontyna quando hai i png definitivi condividi pure almeno aggiorniamo sito. grazie

**Comment by dontyna** [comment]
> @dontyna quando hai i png definitivi condividi pure almeno aggiorniamo sito. grazie

sì, stiamo facendo una prova con font diverso come richiesto

**Comment by tailot** [comment]
Sembrano tutti molto carini siete bravissimi ragazzi, se avete scelto isolerei la parte "grafica" dal testo. L'attuale layout ha il logo "scorporato" dal testo.

**Comment by dontyna** [comment]
![Logo 1](https://user-images.githubusercontent.com/6824007/76307276-d08b6900-62c8-11ea-9a1c-aebe363b544f.png)

@luciaroma @mfortini la accendiamo?

**Comment by luciaroma** [comment]
accendiamo :-)

**Comment by Pinzauti** [comment]
@dontyna Mi passeresti il vettoriale?
