### ISSUE TITLE
Che hashtag usiamo per tweet e Bollettino?

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/covid19italia#90]
Pensando a Twitter e anche al Bollettino che hashtag usiamo? #Covid19Italia? 
@favoeva @Saraveg @chiccap @dontyna @albertopi

**Comment by favoeva** [comment]
Per me ok

**Comment by Saraveg** [comment]
si per ora si. inizierei un ragionamento su un hashtag su modello wuhan #insiemecelafacciamo che è terribile. ma magari con un brainstorming ci vengono idee che incitino ad aiutare, organizzarsi, attivarsi.

**Comment by cristigalas** [comment]
Si, @Saraveg sarebbe meglio... proposta: per ora inseriamo in tweet, post Telegram e Bollettino quello più usato, ovvero #coronavirusItalia, così come suggerisce @favoeva e poi vediamo se e come cambiare. Va bene?

**Comment by favoeva** [comment]
> si per ora si. inizierei un ragionamento su un hashtag su modello wuhan #insiemecelafacciamo che è terribile. ma magari con un brainstorming ci vengono idee che incitino ad aiutare, organizzarsi, attivarsi.

Inizio con brainstorming:
#distantimainsieme 
?

**Comment by favoeva** [comment]
Per I gruppo pensate potrebbe essere utile post fissato in alto con un minimo di istruzioni per condivisone segnalazioni ?

**Comment by cristigalas** [comment]
> Per I gruppo pensate potrebbe essere utile post fissato in alto con un minimo di istruzioni per condivisone segnalazioni ? Aiuterebbe di molto il lavoro degli amministratori

Per Fb e altri canali social c’è issue #10. Scrivi di la. Questa issue la chiuderei per evitare casini... Ok?

**Comment by cristigalas** [comment]
Riepilogo: hashtag per Twitter (e altri social) e Bollettino è #CoronavirusItalia. Poi vedremo...
